### ISSUE TITLE
First time trying. Found one Inconsistency on the PSX clonelist

### ISSUE THREAD

**Issue by dxzdxz1** [unexpectedpanda/retool#1]
After run the latest psx.dat from redump.org with your tool (using -g switch), I saw that one game on the list was repeated.

1Xtreme (USA), ESPN Street Games (Japan) and ESPN Extreme Games (USA) are the same game.

Looking on the Playstation json I found the inconsistency

"ESPN Street Games" is referenced as a clone to "1Xtreme" but "ESPN Street Games" is referenced as a clone to "ESPN Extreme Games" too

1Xtreme is an updated version to ESPN Extreme Games after they lost the licensing to use ESPN logo/name/etc.

Thanks for this great tool :)

**Comment by unexpectedpanda** [comment]
Thanks for picking up the dupe!

Looks like aside from the rename, 1Xtreme also removes ESPN-specific content. With that in mind, I've set 1Xtreme to be a clone of ESPN Extreme Games, as that has more content.
