### ISSUE TITLE
Other filters like rating or players or publisher or kids

### ISSUE THREAD

**Issue by MaXGitteR** [unexpectedpanda/retool#10]
This request goes beyond the information in the DAT files and I am not sure if it is the focus of this project.
Nevertheless I would consider the functionality as very useful.

On several GamesDB pages additional information like: <rating> <releasedate> <developer> <publisher> <genre> <players> <kids> ... with tools like Skraper you can create a gamelist.xml from it and work with it in the finished rom set.
It would be nice to have the possibility to access the information (online or from a gamelist.xml) in the ReTool , to have more filters for DAT files.

**Comment by unexpectedpanda** [comment]
Thanks for the suggestion :) This is way beyond scope I'm afraid. You're best off approaching the original dat groups.
