### ISSUE TITLE
[NES] Clone of Mega Man 2 treated as a separate game

### ISSUE THREAD

**Issue by iGom** [unexpectedpanda/retool#100]
## Dat
Nintendo - Nintendo Entertainment System (20210701-022637).dat

## Issue
Retool treats [one clone of Mega Man 2](https://datomatic.nointro.org/index.php?page=show_record&s=45&n=3162) as a separate game, thus creating a DAT with two copies of Mega Man 2.

from add-remove list
```
+ Mega Man 2 (USA) (Mega Man iam8bit 30th Anniversary) (Aftermarket) (Unl)
+ Mega Man 2 (World) (Mega Man Legacy Collection)
	- Mega Man 2 (Europe)
	- Mega Man 2 (Europe) (Virtual Console)
	- Mega Man 2 (USA)
	- Mega Man 2 (USA) (Virtual Console)
	- Rockman 2 - Dr. Wily no Nazo (Japan)
	- Rockman 2 - Dr. Wily no Nazo (Japan) (Virtual Console)
```

**Comment by unexpectedpanda** [comment]
Ah yet another modern rip to contend with. Added to `internal-config.json`. If you update your clone lists, you should see the benefits.

Cheers for the heads up!
