### ISSUE TITLE
Feature request: Option to create dat from removed items

### ISSUE THREAD

**Issue by zambobway** [unexpectedpanda/retool#104]
Hi, first I would like to thank you for creating the project :) but was wondering if it would be difficult to create a dat from the removed items? This way I could have compete sets split up ( 1g1r, [removed][others] ).

**Comment by unexpectedpanda** [comment]
It should be easy enough to do. My focus is on refactoring Retool at the moment, but I'll add it as a feature when I get to that part.

**Comment by ldolse** [comment]
I was also looking for this too so I've created a fork and made the basic changes for this [here](https://github.com/unexpectedpanda/retool/compare/main...ldolse:retool:main#diff-71d7cdc1b4cf47cb7de6aa3649eb89fc8a445852df53150dc1f12210abbb1463).  I'm not sure if this fits in with your refactoring plans.   If it is something you'd be willing to pull in let me know, at the moment it defaults to always creating a second DAT, would need a bit more work to fit it into your user options - so I didn't submit a pull.  I haven't tested too extensively yet will do that as well.

**Comment by unexpectedpanda** [comment]
Awesome stuff, love to see people building on top of the base :)

From this side the feature is built and functioning well in v2, with the options built in as well. The v2 codebase is a radical departure, so future PRs based on v1 aren't likely to gel well. I'm pushing to get v2 out around the end of the month, although since life happens, I should perhaps hedge that by saying mid-Feb.

**Comment by ldolse** [comment]
Awesome, look forward to V2, I won't try and wrap my head around the user options then, thanks!  I'll keep the V2 branch in mind if I want to do other tweaks in the future, I didn't see it until after I'd done the fork.

**Comment by unexpectedpanda** [comment]
Heads up that the v2 branch here is way behind. I work mostly in a private repo then move things across to GitHub. I've only been using the v2 branch here for occasional testing to make sure things are wired up properly.

**Comment by unexpectedpanda** [comment]
This is now available in v2.
