### ISSUE TITLE
Sega - 32X - 1 Addition to Clone List

### ISSUE THREAD

**Issue by FoxyMonty** [unexpectedpanda/retool#116]
## Dat
Sega - 32X (20210707-115620)

## Issue
Motherbase (Europe) needs adding as a clone of Parasquad, as seen in the No-Intro P/C DAT:

game name="Motherbase (Europe)" cloneof="Parasquad ~ Zaxxon's Motherbase 2000 (Japan, USA)"

Source - https://segaretro.org/Zaxxon%27s_Motherbase_2000

**Comment by unexpectedpanda** [comment]
Thanks! This will be in the next clone list update.
