### ISSUE TITLE
Using Include in custom filters does not keep titles that are not present in clone lists

### ISSUE THREAD

**Issue by AeonX** [unexpectedpanda/retool#117]
**Describe the bug**
Several games I put in Include are removed, either in global or system filters. The few that are kept are those that have different names from the titles of other regions and are therefore on the clone lists.

**To reproduce**
1. Click on Choose single dat and select Sega - Mega Drive no-intro dat.
2. In the Custom system filters tab in Include add the title "Where in Time Is Carmen Sandiego (Brazil) (Es,Pt)". With or without the pipe (|) it produces the same result.

In the auto keep-remove list the title appears as removed as a clone of "Where in Time Is Carmen Sandiego (USA, Europe) (En,Fr,De,Es,It)".

On the other hand, if in Include I add the title "YuYu Hakusho - Sunset Fighters (Brazil)" it is kept even though it is a clone of "Yu Yu Hakusho - Makyou Toitsusen (Japan)".

**Expected behavior**
That all titles added in Include are kept. I want to add some games that are clones but that have my native language (Portuguese).

**Operating system**
- [x] Windows 10 (older versions not supported)
- [ ] Ubuntu
- [ ] Other (please specify)

**Retool edition**
- [x] retool-gui.exe
- [ ] retool.py
- [ ] retool-gui.py

**Retool version**
Retool GUI: 0.11
Retool CLI: 0.98

**Are you using custom global or system filters? If so, list them below**
With just the ones mentioned above I get the unexpected behavior.

**What other settings are you using?**
All in default except the Exclusions tab where I select the following items:

- Applications
- Bad dumps
- Demos, kiosks, and samples
- Manuals
- Pirate
- Preproduction
- Promotional
- Unlicensed
- Video

**Comment by unexpectedpanda** [comment]
Cheers for filing this. I'm looking into it now.

**Comment by unexpectedpanda** [comment]
This has been addressed in v0.99. Thanks!

**Comment by AeonX** [comment]
Thank you very much! Your program is amazing :)
