### ISSUE TITLE
Atari 2600 - Both Space Tunnel (USA) and Le Tunnel de L'Espace (Europe) are included in the dat. 

### ISSUE THREAD

**Issue by katarak** [unexpectedpanda/retool#118]
## Dat
Atari 2600 using the latest no-intro.

## Issue
In my list I have both Space Tunnel (USA) and Le Tunnel de L'Espace (Europe).
ScreenScraper has them together: https://www.screenscraper.fr/gameinfos.php?gameid=87895&action=onglet&zone=gameinfosinfos
https://atariage.com/software_page.php?SoftwareID=4038
Here's the Launchbox link with even more similar names: https://gamesdb.launchbox-app.com/games/details/83257

In the end it might be because No-Intro has the wrong name for the game using "L'Espace" instead of "L'Estace" There was clearly  a typo when they made this game. Estace is not a french word. But it might have been corrected in the France release

So yeah. they did eventually fix it: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjjtpz6CxModMeSKwmTuxb1qOFjpZHHFEGOS7IGNw9AMD_FAcWIzpqoV6QpZ24jR--hJ4&usqp=CAU

**Comment by unexpectedpanda** [comment]
Thanks, clone list updated :)
