### ISSUE TITLE
Filter Problem "(notgame)" - ZZZ

### ISSUE THREAD

**Issue by MaXGitteR** [unexpectedpanda/retool#12]
ReTool keeps some files , but should filter them out before.
Maybe a filter is missing for exclusion?

  <game id="155336" source="ScreenScraper.fr">
    <path>./Aging Cartridge (World).zip</path>
    <name>ZZZ(notgame):Aging Cartridge [WOR]</name>
  </game>
  <game id="83561" source="ScreenScraper.fr">
    <path>./e-Reader (USA).zip</path>
    <name>ZZZ(notgame):E-reader [US]</name>
  </game>
  <game id="85071" source="ScreenScraper.fr">
    <path>./Game Boy Advance Video - Codename - Kids Next Door - Volume 1 (USA, Europe).zip</path>
    <name>ZZZ(notgame):Game Boy Advance Video - Codename - Kids Next Door [EU,US]</name>
  </game>
  <game id="85072" source="ScreenScraper.fr">
    <path>./Game Boy Advance Video - Shark Tale (USA) (Rev 6).zip</path>
    <name>ZZZ(notgame):Game Boy Advance Video - Shark Tale [US]</name>
  </game>
  <game id="85073" source="ScreenScraper.fr">
    <path>./Game Boy Advance Video - Shrek (USA) (Rev 6).zip</path>
    <name>ZZZ(notgame):Game Boy Advance Video - Shrek [US]</name>
  </game>
  <game id="85074" source="ScreenScraper.fr">
    <path>./Game Boy Advance Video - Shrek 2 (USA) (Rev 6).zip</path>
    <name>ZZZ(notgame):Game Boy Advance Video - Shrek 2 [US]</name>
  </game>
  <game id="84294" source="ScreenScraper.fr">
    <path>./Nintendo MP3 Player (Europe) (En,Fr,De,Es,It).zip</path>
    <name>ZZZ(notgame):Nintendo Mp3 Player [EU]</name>
  </game>

**Comment by unexpectedpanda** [comment]
Where is this data coming from? It doesn't appear to be related to No-Intro or Redump dats.

**Comment by MaXGitteR** [comment]
yes you are right, this seems to be a problem in ths data quality of the dat file.

DAT File / datomatic.no-intro.org / ReTool 1g1R:
	<game name="Aging Cartridge (World)">
		<category>Games</category>
		<description>Aging Cartridge (World)</description>
		<release name="Aging Cartridge (World)" region="World"/>
		<rom crc="bbb6a960" md5="9f74b2ad1d33e08e8a570ffe4564cbc3" name="Aging Cartridge (World).gba" sha1="c67e0a5e26ea5eba2bc11c99d003027a96e44060" size="2097152"/>
	</game>

gamelist.xml after skraper.net / ScreenScraper.fr
  <game id="155336" source="ScreenScraper.fr">
    <path>./Aging Cartridge (World).zip</path>
    <name>ZZZ(notgame):Aging Cartridge [WOR]</name>
    <releasedate />
    <image>./media/images/Aging Cartridge (World).png</image>
  </game>

Regards

Henrik

**Comment by unexpectedpanda** [comment]
Ah I see, a Retropie plus scraper thing. I think responsibility for this one lies with the groups who are creating the dats, but I'll make a note to check out the scrapers in the future on the off chance there's an easy way to integrate them.
