### ISSUE TITLE
SNES Human Grand Prix 2 (Beta) is not clone of Human Grand Prix II, nor F1 Pole Position 2

### ISSUE THREAD

**Issue by katarak** [unexpectedpanda/retool#121]
## Dat
Super Nintendo Entertainment System 2021-09-24

## Issue
I just noticed they no intro added Human Grand Prix 2 (Japan) (Beta). Only Human Grand Prix II is listed as a clone of F1 Pole Position.
I expect the name will eventually be changed from 2 to II, but I wanted to flag it anyway.

https://www.wikiwand.com/en/F1_Pole_Position_2

**Comment by unexpectedpanda** [comment]
Cheers, it'll be in the next release.
