### ISSUE TITLE
Interested in PySimpleGUIQt Alpha?  Is the project using PySimpleGUIQt?

### ISSUE THREAD

**Issue by PySimpleGUI** [unexpectedpanda/retool#125]
**Describe the bug**

Wondering if this project uses PySimpleGUIQt anymore.  I don't see anything mentioned in any document except in the WIKI, so my assumption is that you're no longer using it.  But, thought it was worth making direct contact to be sure.

A private Alpha is going to begin shortly for PySimpleGUIQt and I'm looking for existing projects that are interested in participating.

**Comment by unexpectedpanda** [comment]
Still absolutely using it, with a few custom QT calls for styling.

I'm in the middle of a rewrite at the moment, and don't really have an ETA for completion. When I get to the GUI portion, I'm happy to try out the alpha (or whichever version it's up to by then).
