### ISSUE TITLE
Demo-filter should exclude titles with "Demonstration"

### ISSUE THREAD

**Issue by prklx2** [unexpectedpanda/retool#129]
Some examples found using the latest No-Intro datfiles. 
Currently these are included even with Demo filter on.

Mattel - Intellivision:
	Demonstration Cartridge - Blue (USA)
	Demonstration Cartridge - Green (USA)
	Demonstration Cartridge - Red (USA)
	International Demonstration Cartridge (World)

Commodore - 64 (PP):
	Activision Action Demonstration (USA, Europe) (Promo)

RCA - Studio II:
	Demonstration Cartridge (USA)

**Comment by unexpectedpanda** [comment]
It looks like "Demonstration" is only used for demos across the dats that I'm looking at -- but it could be a problem in the future to just exclude titles with the string. Best to add each title individually as a category change, I think.

These will be in the next update, thanks again :)
