### ISSUE TITLE
MAME

### ISSUE THREAD

**Issue by MaXGitteR** [unexpectedpanda/retool#13]
Could you add support for MAME?

**Comment by unexpectedpanda** [comment]
Retool is designed for No-Intro and Redump. I don't intend to expand beyond those sets.

MAME itself has quite a few complications to consider that would make support difficult, mostly concerning merged vs split sets, and how to manage parent ROMs if someone decides to exclude the parent region or language. There's also likely a heck of a lot of manual curation in there with a maintenance burden that will only increase with each release.

One way you could approximate the same result is to pursue split sets, and remove all the clones.
