### ISSUE TITLE
Dreamcast Tee Off (USA) and Golf Shiyouyo (Japan) are not clones 

### ISSUE THREAD

**Issue by katarak** [unexpectedpanda/retool#132]
## Dat
Sega - Dreamcast (2021-09-08 12-25-48) Redump

## Issue
Dreamcast Tee Off (USA) and Golf Shiyouyo (Japan) are not clones 
https://www.wikiwand.com/en/Tee_Off
https://www.mobygames.com/game/dreamcast/tee-off_

**Comment by unexpectedpanda** [comment]
Thanks, corrected :)
