### ISSUE TITLE
GC: SmaBro DX Event-you Disc + Gundam Senshi-tachi no Kiseki - Kadokawa

### ISSUE THREAD

**Issue by rufotheone-fr** [unexpectedpanda/retool#134]
## Dat
GameCube

## Issue

* SmaBro DX Event-you Disc: http://sgadsale.seesaa.net/article/206107309.html
It's a special version of Melee for events. Should we drop it with the rename of Melee or give it a category (like Promotional) ?

* Kidou Senshi Gundam - Senshi-tachi no Kiseki - Kadokawa Shoten Rengou Kikaku Tokubetsu-hen: http://gamekube.html.xdomain.jp/kiseki/kadokawa/kadokawa.html
Seems to be a special version with pilots at max level. Same question as SmaBro.

**Comment by unexpectedpanda** [comment]
Eeps, this one got lost among the other issues. _Promotional_ sounds like a great idea :)
