### ISSUE TITLE
[Feature Request] Keep Revisions

### ISSUE THREAD

**Issue by im4potato** [unexpectedpanda/retool#135]
I'm sorry if this isn't the right place to ask this, or if this is already possible, but I don't see an option for it.
I understand that this tool's primary function is to create 1G1R sets, but it's really useful for other types of filtering. I'd like to use it to filter regions, betas, demos, etc. The issue I'm having is that I'd like to keep revisions. Is that currently possible?
Right now I'm using my own filters in clrmamepro to achieve this, but automating it with Retool would be really convenient for me.

**Comment by unexpectedpanda** [comment]
Just had a thought that might get you to where you want to go:

1. Set your regions.
1. Click **Modes**, then select **Output dat in legacy parent/clone format**.
1. Make sure 1G1R mode is off in your dat manager of choice when you create your set (that is, make sure it ignores parent/clone relationships).

**Comment by unexpectedpanda** [comment]
You can now disable 1G1R filtering in v2, which should keep all the titles and let you use Retool purely as a filter.
