### ISSUE TITLE
"Sony - PlayStation Portable (Redump)" - 3 non-games

### ISSUE THREAD

**Issue by githubanon0** [unexpectedpanda/retool#137]
- "CS Kensa Disc (J1) (Japan)"
  - Application
- "Metal Gear Solid - Digital Graphic Novel (Europe) (En,Fr,De,Es,It)"
  - Multimedia
- "SOCOM - U.S. Navy SEALs - Fireteam Bravo 2 (Europe) (En,Fr,De,Es,It) (Press Disc)"
  - Promotional

> Datfile `Sony - PlayStation Portable - Datfile (2320) (2021-10-31 21-33-12).dat`
> Retool version `1.01`
> Retool options `aAbBcdDemMopPrv`
> Clonelist last updated `22 October 2021`

**Comment by unexpectedpanda** [comment]
I'm going to have to look into _SOCOM_ and exactly what No-Intro means by `(Promo)` (and if it applies to Redump in any way). I might need to catch all `(Press Disc)/(Press Disk)` titles as promotional, and integrate it into the alpha/beta/production versioning.

It's been set as a clone of the production version in the next release though, and the others will be in the next clone list release.

**Comment by unexpectedpanda** [comment]
Looks like `(Press Disc)/(Press Disk)` can either be multimedia or games. Best to keep with Redump's original categorization here I think, and make individual modifications as necessary.
