### ISSUE TITLE
A clone what went unnoticed

### ISSUE THREAD

**Issue by AlvaroBurnett** [unexpectedpanda/retool#14]
Hi! In the Game Boy Advance:

    Mega Man Battle Network 5 - Team Proto Man (USA) (Virtual Console).zip

should be replaced with:

    Mega Man Battle Network 5 - Team Protoman (USA).zip

**Comment by unexpectedpanda** [comment]
Good catch, the standard one had a lower priority in the clone list than the Virtual Console version. Fixed now, although I expect No-Intro will standardize the title at some point :)
