### ISSUE TITLE
"Nintendo - Game Boy" - "InfoGenius"

### ISSUE THREAD

**Issue by githubanon0** [unexpectedpanda/retool#140]
- "InfoGenius Productivity Pak - Berlitz French Translator (USA, Europe)"
  - "Applications" or "Educational"
- "InfoGenius Productivity Pak - Berlitz Spanish Translator (USA, Europe)"
  - "Applications" or "Educational"
- "InfoGenius Productivity Pak - Frommer's Travel Guide (USA)"
  - "Applications" or "Educational"
- "InfoGenius Productivity Pak - Spell Checker and Calculator (USA)"
  - "Applications"
- "InfoGenius Systems - Personal Organizer with Phone Book (Europe)"
  - "Applications"

**Comment by unexpectedpanda** [comment]
Thanks again, it'll be in the next release :)
