### ISSUE TITLE
"Nintendo - Game Boy Color" - "Orbital Diagnostic System"

### ISSUE THREAD

**Issue by githubanon0** [unexpectedpanda/retool#141]
I suggest adding this to ```clonelists\Nintendo - Game Boy Color.json```
```
	"categories": {
		"Orbital Diagnostic System": {
			"match": "short",
			"categories": ["Applications"]
		},
	},
```
For proof that the Orbital Diagnostic System is not a game, please see item 1 on [this Reddit post](https://www.reddit.com/r/gamecollecting/comments/25icz0).

> Datfile `Nintendo - Game Boy Color (Parent-Clone) (20211106-012058)`
> Retool version `1.01`
> Retool options `aAbBcdDemMopPrv`
> Clonelist last updated `22 October 2021`

**Comment by unexpectedpanda** [comment]
Thanks, it'll be in the next release :)
