### ISSUE TITLE
"Watara - Supervision" - "2 in 1" titles

### ISSUE THREAD

**Issue by ghost** [unexpectedpanda/retool#142]
- "2 in 1 - Block Buster + Cross High (USA, Europe)"
  - "Block Buster (USA, Europe)"
  - "Cross High (USA, Europe)"
- "2 in 1 - Hash Blocks + Eagle Plan (USA, Europe)"
  - "Hash Blocks (USA, Europe)"
  - "Eagle Plan (USA, Europe)"

> Datfile `Watara - Supervision (Parent-Clone) (20200126-122631).dat`
> Retool version `1.01`
> Retool options `aAbBcdDemMopPrv`
> Clonelist last updated `22 October 2021`

**Comment by unexpectedpanda** [comment]
Fixed in v2.
