### ISSUE TITLE
Feature request: show NTSC, PAL, SECAM, etc. in Regions filter list

### ISSUE THREAD

**Issue by ghost** [unexpectedpanda/retool#143]
The region filter as it exists right now is helpful to choose games in your preferred language(s). Listing the framerate too will help us pick the best games for our screens. For example, right now Retool tells me to keep Rez (Europe) for Dreamcast which runs at 50 Hz. Rez (Japan) has an English setting and runs at 60 Hz, making it the better choice for me. For some consoles this isn't a concern at all. Most handhelds have 60 Hz screens no matter the region. Maybe Retool could detect the console from the datfile and only show NTSC/PAL/SECAM/etc when it's relevant. Ideally the refresh rate would be tagged by Redump/No-Intro on a per-game basis but I'm guessing that's a tall order for them.

A blanket approach like this will have some false results (Europe-region games that run at 60, etc) but it's better than doing nothing in my opinion.

![example](https://user-images.githubusercontent.com/93097421/138617908-4d14bfae-2eb1-4b8f-9580-b5018b92a8c5.png)

**Comment by unexpectedpanda** [comment]
While this is easier now there are system settings in Retool, I can't see it happening given how long this request has been open. Closing for now.
