### ISSUE TITLE
Save feature for multiple custom filterings?

### ISSUE THREAD

**Issue by rufotheone-fr** [unexpectedpanda/retool#146]
Hi!
Could it be doable to implement a multi save feature in order to call different filtering/exclusions/whatever values?

Thank you for your hard work!

**Comment by githubanon0** [comment]
Retool is portable, supports multiple instances and takes up less than 100 MB. You can keep separate program folders for your different configs. I just tried it myself and it worked.
![Untitled](https://user-images.githubusercontent.com/93097421/140879095-423b70f7-327f-4275-9a7a-8e3cb087e6ae.png)
![Untitled2](https://user-images.githubusercontent.com/93097421/140879113-e2678f1c-0ce2-4900-b595-ebd76d4da822.png)

**Comment by unexpectedpanda** [comment]
While you can't save and load different settings, Retool v2 now lets you save settings at the system level. For example, this means _Sony - PlayStation (Redump)_ can have different settings to _Atari - 2600 (No-Intro)_, which in turn can be different to the global settings applied to all other DAT files.

I'm hoping this new feature scratches this particular itch :)
