### ISSUE TITLE
"Atari - 2600" - "BASIC Programming" [incorrect group]

### ISSUE THREAD

**Issue by githubanon0** [unexpectedpanda/retool#148]
I believe it should be categorized as an [application](https://www.youtube.com/watch?v=RP1M2bgsSWg).

> Datfile `Atari - 2600 (Parent-Clone) (20211016-205407).dat`
> Retool version `1.01`
> Retool options `aAbBcdDemMopPrv`
> Clonelist last updated `22 October 2021`

**Comment by unexpectedpanda** [comment]
Thanks, it'll be in the next update :)
