### ISSUE TITLE
"Nintendo - Game Boy Color" - 5 compilations

### ISSUE THREAD

**Issue by ghost** [unexpectedpanda/retool#149]
- Full Time Soccer & Hang Time Basketball
- Jurassic Boy 2 + Thunder Blast Man
- Pocket Smash Out & Race Time
- Space Invasion & Karate Joe
- Space Invasion & Painter
> Datfile `Nintendo - Game Boy Color (Parent-Clone) (20211106-012058).dat`
> Retool version `1.01`
> Retool options `aAbBcdDemMopPrv`
> Clonelist last updated `22 October 2021`

**Comment by unexpectedpanda** [comment]
Fixed in v2.
