### ISSUE TITLE
3DO Blood Angels (Japan) isn't linked to Space Hulk - Vengeance of the Blood Angels (USA)

### ISSUE THREAD

**Issue by katarak** [unexpectedpanda/retool#15]
When generating the 3DO list with "Use suggested region order for English Speakers" will return both Blood Angels and Space Hulk in the generated dat

Here's the Redump page for Blood Angels: http://redump.org/disc/61605/ It does list the alternate name as Space Hulk

**Comment by unexpectedpanda** [comment]
Cheers, missed this one -- verified it's the same title, so I added it to the 3DO clone list. If you updated the clone lists, it should be taken into account now.
