### ISSUE TITLE
"Nintendo - Super Nintendo Entertainment System" - "Super Bombliss"

### ISSUE THREAD

**Issue by ghost** [unexpectedpanda/retool#150]
"Super Bombliss" is included in "Super Tetris 2 + Bombliss". You might say it's better to keep the standalone title in addition to the compilation. I would argue the precedent for removing it was set by "Super Mario All-Stars + Super Mario World". In that case, the standalone versions of "Super Mario All-Stars" and "Super Mario World" were removed.
> Datfile `Nintendo - Super Nintendo Entertainment System (Parent-Clone) (20211105-085038).dat`
> Retool version `1.01`
> Retool options `aAbBcdDemMopPrv`
> Clonelist last updated `28 October, 2021`

**Comment by unexpectedpanda** [comment]
Fixed in v2 thanks to its new compilations handling.
