### ISSUE TITLE
wii games?

### ISSUE THREAD

**Issue by mathdups** [unexpectedpanda/retool#152]
Any hope to get wii games too  ? I have a recent dat from Redump if needed

**Comment by unexpectedpanda** [comment]
Hey there,

As mentioned in #31, clone lists are only supplied for dats available on Redump's website.

[Come join Discord](https://discord.gg/e5DqwghU) and we can discuss other options like custom clone lists.

**Comment by mathdups** [comment]
> Hey there,
> 
> As mentioned in #31, clone lists are only supplied for dats available on Redump's website.
> 
> [Come join Discord](https://discord.gg/e5DqwghU) and we can discuss other options like custom clone lists.

Well yes i know but there is one redump dat file for wii existing .. People in redump dont make it public because they think the wii is a too new console... Maybe you could link it to another place where people (or I :) ) would update the file from time to time ... Just wondering

**Comment by unexpectedpanda** [comment]
I can only follow Redump on this. Join the Discord using the previous link and we can discuss more.

**Comment by githubanon0** [comment]
Where did you get your Wii datfile? What happens when you try running it through Retool?
