### ISSUE TITLE
New (Application) -tag in No-Intro

### ISSUE THREAD

**Issue by prklx2** [unexpectedpanda/retool#157]
No-Intro has added a new tag in their dats.

This (Application)-tag is used in their newer dats, e.g. "_Apple - IIGS (WIP)_"

Retool currently doesn't filter these out.

**Comment by unexpectedpanda** [comment]
I've just grabbed the daily pack, and the tag isn't used, even in the _Apple - IIGS (WIP)_ dat. Could it have been reverted, or am I missing something?

**Comment by prklx2** [comment]
It seems to have been reverted. It still had it when I posted this issue. Closing this now.
