### ISSUE TITLE
Support for N-Gage and Gizmondo dats

### ISSUE THREAD

**Issue by prklx2** [unexpectedpanda/retool#158]
Retool currently doesn't process correctly these non-datomatic -dats from No-Intro.

Nokia - N-Gage (20081203).dat
Tiger - Gizmondo (20070531).dat

When trying to input the Gizmondo dat, retool crashes immediately without any error messages.

N-Gage -dat works otherwise, but retool misses the unique tags that are only used here, for example _(Review Kit xxx)_ and _(Full Trial)_

**Comment by unexpectedpanda** [comment]
The Gizmondo dat has invalid unicode characters (�) in it that No-Intro needs to fix. Additionally, something in the CLRMAMEPro-style dat also brings Retool 1 to a halt -- this might be fixed in Retool 2 when it's released.

Both N-Gage tags have been added to Retool 1.02.
