### ISSUE TITLE
The Cat in the Hat for GBA clone confusion

### ISSUE THREAD

**Issue by Rolen47** [unexpectedpanda/retool#159]
## Dat
Nintendo - Game Boy Advance (20211206-130404).dat

## Issue
There's 3 Cat in the Hat games in this dat. 2 are the same type, 1 is unique.

These 2 games are the same type:
Dr. Seuss' The Cat in the Hat (USA)
https://i.imgur.com/pMSaYBA.png
https://i.imgur.com/5O4381W.png

Cat in the Hat, The (Europe) (En,Fr,De,Es,It)
https://i.imgur.com/RdlUxBQ.png
https://i.imgur.com/TbMnnmU.png

This 1 is unique and a different type of game:
Cat in the Hat, The (USA)
https://i.imgur.com/xX8hqSU.png
https://i.imgur.com/AoF8DKG.png

**Comment by unexpectedpanda** [comment]
Thanks for the heads up! The GBA clone list will be updated shortly.
