### ISSUE TITLE
Add support for new public Redump dats (360, Wii, PS3)

### ISSUE THREAD

**Issue by retroNUC** [unexpectedpanda/retool#166]
Announcement/discussion:
https://www.reddit.com/r/emulation/comments/rtj4pt/language_matters_a_little_note_about_redumporg/

**Microsoft Xbox 360:**
- http://redump.org/discs/system/xbox360/
- http://redump.org/datfile/xbox360/

**Nintendo Wii:**
- http://redump.org/discs/system/wii/
- http://redump.org/datfile/wii/

**Sony PlayStation 3:**
- http://redump.org/discs/system/ps3/
- http://redump.org/datfile/ps3/

Not sure if changes are needed for support, placeholder clone files, etc, just making you aware. Happy new year!

**Comment by unexpectedpanda** [comment]
Thanks! I'm aware, and the [clone lists](https://github.com/unexpectedpanda/retool/tree/main/clonelists) and [metadata](https://github.com/unexpectedpanda/retool/tree/main/metadata) are already available for the new systems :) Update and you should be good to go.
