### ISSUE TITLE
The UK Region Filter don't work in No-Intro Dats.

### ISSUE THREAD

**Issue by Zombanana** [unexpectedpanda/retool#169]
**Describe the bug**
The Region Filter for (UK), don't work for No-Intro Dats.
Redump UK Region Titles are tagged as (UK).
No-Intro UK Region Titles are tagged as (United Kingdom).
I think this should be the issue.

Not sure if it allways was like this, or if No-Intro did a name changing for the UK Tag.

**To reproduce**
Just get the No-Intro "Nintendo DS" Dat file and try to filter UK Region Titles.
No Titles are found. They are all identified as "Unknown" Region Titles.
If you Filter for "Unknown" Region Titles, all UK Region Titles are identified.
It should be very easy to reproduce.

I found this issue at rebuilding my Nintendo DS Set, as I noticed that I got some United Kingdom Region Clones, which shouldn't be in the set after rebuilding.

**Expected behavior**
Well, expected behavior should be a correct working filter 👍 .
Btw, Keep up the good work. It's the best Tool out there for now.

**Operating system**
- [x] Windows 10 (older versions not supported)
- [ ] Ubuntu
- [ ] Other (please specify)

**Retool edition**
- [x] retool-gui.exe
- [ ] retool.py
- [ ] retool-gui.py

**Retool version**
Retool GUI: 0.11
Retool CLI: 1.03
For the command line edition of Retool, the version is shown when you run it with no other arguments.

For the GUI edition, click **Help**, then **About**.

**Are you using custom global or system filters? If so, list them below**

Global excludes:
-
Global includes:
-
System excludes:
-
System includes:
-
**What other settings are you using?**

**Additional context**

**Comment by unexpectedpanda** [comment]
That discrepancy has been around since I started working on Retool. It's definitely taken into account elsewhere, so I'm surprised to see this issue crop up. I'll look into it.

**Comment by Zombanana** [comment]
Well, I have used a recent No-Intro Dat:
"Nintendo - Nintendo DS (Decrypted) (20220102)".

I have a different Region priority:
Germany > Europe > USA > Australia > Unknown.
Other Regions are excluded.

Languages: German & English.

Normally I would expect that all UK region titles should be excluded. But they are inside the rebuilded set.

Exemple:
007 - Blood Stone (Germany)
007 - Blood Stone (United Kingdom)

Both titles are inside the dat and in the rebuilded set. According to my settings, only the German title should be in the set. But I have both titles.
Somehow it seems, the parent/clone relationship is broken on the (United Kingdom) titles.

I have excluded the Unknown setting as a workaround until the issue is fixed for now.

**Comment by unexpectedpanda** [comment]
Ah, that extra info is useful, thanks! I think I've fixed the issue in 1.04, give it a try :)

**Comment by Zombanana** [comment]
Thanks for the fast fixing. I will test it in some hours after sleeping. I am here in the midfle of the night. :)

**Comment by Zombanana** [comment]
The issue is fixed. Tested it and it works now as expected.
My region filter is now set with this priority: Germany > Europe > USA > UK > Australia
Language filter is set: German + English.

Now it works as expected. United Kingdom (UK) Titles are recognized.
Also the parent clone relationship works as expected.

Issue is now fixed. Thank you very much.
Keep up the good work on this tool 👍  :)
