### ISSUE TITLE
Some 3DO titles missing clone links

### ISSUE THREAD

**Issue by katarak** [unexpectedpanda/retool#17]
Here are a few more I found today.

NFL Madden Football (Japan) is John Madden Football (USA). http://redump.org/discs/quicksearch/nfl-madden-football/
Outer World (Japan) is Another World (Europe) and Out of This World (USA). http://redump.org/disc/39845/
Shanghai - Banri no Choujou - The Great Wall (Japan) (Rev 1) is Shanghai Triple Threat (USA): http://redump.org/discs/quicksearch/triple-threat/
T&E VR Golf - Devil's Course (Japan) is Wicked 18 (USA): http://redump.org/discs/quicksearch/devil's-course/
Virtual Quest - Pharaoh no Fuuin (Japan) is Seal of the Pharaoh (USA); http://redump.org/disc/36316/

Also, both VR Stalker (Europe) (Improved Version) and VR Stalker (USA) are added to the dat which indicates to me they aren't linked together either.

**Comment by unexpectedpanda** [comment]
Many of those look familiar to me -- I must have linked them in other systems and not 3DO. Thanks for the heads up, I'll be able to add them to the 3DO clone list in a few days.

**Comment by unexpectedpanda** [comment]
Thanks, this has been fixed, and will be in the next update.
