### ISSUE TITLE
Add option to not include MIA titles

### ISSUE THREAD

**Issue by updawg** [unexpectedpanda/retool#177]
A lot of the ISO based sets still have MIA games, however, retool will sometimes select these games. Has there been any thought in filtering out games that haven't been dumped?

**Comment by unexpectedpanda** [comment]
Retool can only filter using the information in the DAT itself. So if the DAT indicates a release is MIA, it's possible.

Unfortunately, this usually isn't the case, so this becomes a difficult problem to solve. While keeping a separate MIA list that's referenced by Retool is possible, it also means it's something that has to be kept up to date.

I'll put some more thought into it, but it seems a bit like a non-optimal situation no matter which way you go at this point in time.

**Comment by updawg** [comment]
I appreciate the response! A community effort would be great my initial thought was scraping the following sites below:

http://wiki.redump.org/index.php?title=MIA_Lists
https://datomatic.no-intro.org/report_mia.php

**Comment by unexpectedpanda** [comment]
Ah! I knew about the Redump one, but wasn't aware that No-Intro kept a list. Interesting. I'll keep it under consideration, and see if it's feasible or not.

**Comment by updawg** [comment]
No problem - I appreciate you even considering it!

**Comment by FidoFuz** [comment]
No-Intro is now including [MIA] in the title so it can be filtered out using existing functionality.

**Comment by unexpectedpanda** [comment]
This has now been added in v2.
