### ISSUE TITLE
CD-i has incorrect clone for Zelda - The Wand of Gamelon

### ISSUE THREAD

**Issue by katarak** [unexpectedpanda/retool#179]
## Dat
Redump Phillips CD-I:

## Issue
I'm seeing both of these in the 1G1R output
Zelda - De Toverstaf van Gamelon (Netherlands)
Zelda - The Wand of Gamelon (USA)

Pretty sure it's just a Netherlands translation of the same game.

**Comment by unexpectedpanda** [comment]
Thanks! It's been some time since I've been able to look at the clone lists. With luck perhaps over the next week.

**Comment by unexpectedpanda** [comment]
Fixed in the next update.
