### ISSUE TITLE
Missing Parent/Clone relationships on NEC TurboGrafx CD

### ISSUE THREAD

**Issue by katarak** [unexpectedpanda/retool#18]
Going through the TG CD I found these few issues.

Gate of Thunder (Japan) (FACT, FADT) is included in Gate of Thunder + Bonk's Adventure + Bonk's Revenge (USA)
I understand that the 3 in 1 is clearly a different game and not per se a clone, but in the end one does get the game twice. Here's the moby link: https://www.mobygames.com/game/turbografx-cd/gate-of-thunder-bonks-adventure-bonks-revenge

Makai Eiyuuden - Shape Shifter (Japan) is Shape Shifter (USA): https://www.mobygames.com/game/turbografx-cd/shape-shifter

and lastly
TerraForming (Japan) is Syd Mead's Terraforrming (USA): https://www.mobygames.com/game/turbografx-cd/syd-meads-terraforming

If you rather I send you this data differently, please let me know and I will do so.

**Comment by unexpectedpanda** [comment]
> Gate of Thunder (Japan) (FACT, FADT) is included in Gate of Thunder + Bonk's Adventure + Bonk's Revenge (USA)

Compilations are always a bit weird to deal with, especially when considering the `-c` option. But in this case, your suggestion makes sense. Thanks for the other titles too!

I'll update the clone lists as soon as I can -- #16 has been taking most of my focus of late.

> If you rather I send you this data differently, please let me know and I will do so.

This way works excellently :)

**Comment by unexpectedpanda** [comment]
Okay, in the next update if USA is above Japan, `Gate of Thunder (Japan) (FACT, FADT)` will be a clone of `Gate of Thunder + Bonk's Adventure + Bonk's Revenge (USA)`. If Japan is above USA, you'll get both titles.
