### ISSUE TITLE
World is being selected over USA on certain games

### ISSUE THREAD

**Issue by updawg** [unexpectedpanda/retool#182]
**Describe the bug**
If I filter by region with USA at the top and World underneath, languages set to english, and all exclusions but add-ons are checked, with no custom filters, Forza Motorsport 4 - Essentials Edition (World) is being selected over Forza Motorsport 4 (USA) (En,Ja,Fr,De,Es,It,Nl,Pt,Zh,Ko,Pl,Ru,Cs,Hu) (Disc 1) (Play Disc) and Forza Motorsport 4 (USA) (En,Ja,Fr,De,Es,It,Nl,Pt,Zh,Ko,Pl,Ru,Cs,Hu) (Disc 2) (Content Install Disc)

**To reproduce**
Use the latest redump dat file for xbox 360 (Microsoft - Xbox 360 - Datfile (2819) (2022-03-14 02-38-49).dat).

Use the following options:
![image](https://user-images.githubusercontent.com/10038272/158445714-f4e172f4-ed17-40c7-9497-e6a41371826e.png)
![image](https://user-images.githubusercontent.com/10038272/158445760-0718a3b4-748e-4bf7-b970-b983c51a457e.png)
![image](https://user-images.githubusercontent.com/10038272/158445797-a79b88cb-6351-4a48-aa1e-9e61673faf57.png)

Output a Retool generated dat file.

Open the dat file with a text editor and verify the version of Forza Motorsport 4 selected.

**Expected behavior**
Forza Motorsport 4 (USA) (En,Ja,Fr,De,Es,It,Nl,Pt,Zh,Ko,Pl,Ru,Cs,Hu) (Disc 1) (Play Disc) and Forza Motorsport 4 (USA) (En,Ja,Fr,De,Es,It,Nl,Pt,Zh,Ko,Pl,Ru,Cs,Hu) (Disc 2) (Content Install Disc) are selected.

**Operating system**
- [ ] Windows 10 (older versions not supported)

**Retool edition**
- [ ] retool-gui.exe

**Retool version**
0.11
1.04

**Comment by updawg** [comment]
Thanks! So how do you place a priority on region over language with USA titles always winning out?

**Comment by unexpectedpanda** [comment]
It's not how it works :) Retool is set up to pick the best possible title, which roughly correlates to the latest version/version with the most content.

It's something I can look into supporting for future versions, with the caveat that if you turn it on, you understand you're potentially getting versions with less content.

From what I understand, the only reasons to stick with USA only is older titles that are affected by NTSC vs PAL frame rates, or if you're trying to run something on a region locked platform. Do you have a different reason?

**Comment by updawg** [comment]
I could be assuming incorrectly, but I figured USA first World second would
result in a definitive USA based set. It would place preference on a region
where you are more likely to have played that specific release.

**Comment by unexpectedpanda** [comment]
Ah, I understand where you're coming from. Although given World encompasses USA, I don't see a particular harm here.

There are some changes in Retool 2.0 to accommodate people who have region-specific goals like this one. I'm not sure that this particular use-case is covered, but I'll see what I can do.

**Comment by updawg** [comment]
But I guess that is my question. If there are both a USA and a World
release for a title were both versions actually distributed in the US? Or
is World more of a blanket term for English version in multiple regions?

**Comment by unexpectedpanda** [comment]
My understanding is a World release was made available in USA, Japan, and Europe.

**Comment by updawg** [comment]
Thanks for clarifying. I appreciate the responses!

**Comment by unexpectedpanda** [comment]
Corrected in v2.
