### ISSUE TITLE
DAT crashing Retool

### ISSUE THREAD

**Issue by Sparkrdom** [unexpectedpanda/retool#188]
**Describe the bug**
When running the latest ReTool on a custom Gamecube RVZ Dat, it immediately crashes Retool completely

**To reproduce**
Open ReTool, choose the DAT in question, click run, crash.

**Expected behavior**
It processes the DAT, giving me a new one with all my customizations

**Operating system**
- [x] Windows 10 (older versions not supported)
- [ ] Ubuntu
- [ ] Other (please specify)

**Retool edition**
- [x] retool-gui.exe
- [ ] retool.py
- [ ] retool-gui.py

**Retool version**
1.05 and 1.06

**Are you using custom global or system filters? If so, list them below**
Nothing custom

**What other settings are you using?**
All regions, English only, excluding:
-Apps
-Bad dumps
-BIOS and other chips
-Coverdiscs
-Demos, kiosks, and samples
-Pirate
-Promotional
-Unlicensed

**Additional context**
Works fine with other programs, such as ConvertDat (but this doesn't do as nice a job). 

[Nintendo_-_GameCube_-_RVZ_(1933)_(20220307_190604).dat.txt](https://github.com/unexpectedpanda/retool/files/8500311/Nintendo_-_GameCube_-_RVZ_.1933._.20220307_190604.dat.txt)
![Untitled](https://user-images.githubusercontent.com/22569083/163684076-b91a2927-98dc-4727-a276-d4bb536b9dc6.png)

**Comment by unexpectedpanda** [comment]
Thanks for including the DAT. I'll be able to look into it in the coming week, although the fix might take a little longer as any potential change I'll bundle with #186.

Was the DAT built by you, or is there another source?

**Comment by Sparkrdom** [comment]
No worries about timing!

I'm using Retool to split a complete collection into two separate folders. One folder with just English games for using/playing, the other with everything else that gets removed. Since I have a complete GCN collection right now, the organization is not a big deal.

The DAT file came from [MOBASuite](https://mobasuite.com/), which is mostly used to find/share missing games. Within the forums, there's a sticky post from Loggan that links to his Mega archive, where he hosts said custom DAT. It's the only source of an RVZ based DAT I could find. I think NO-INTRO usually only looks for ISO, which are way bigger.

**Comment by unexpectedpanda** [comment]
Ah, then it's likely generated from some sort of DIR2DAT process. I'll take a look when I next have access to my dev machine :)

**Comment by unexpectedpanda** [comment]
Turns out an empty `<url>` field in the header leads to a crash. This is fixed in Retool 1.07.
