### ISSUE TITLE
Feature Request: Manual Exclusions

### ISSUE THREAD

**Issue by katarak** [unexpectedpanda/retool#19]
I thought it would be a good idea to be able to add a text file (or dat file) of specific games to exclude. 

I go through the retool generated dats for CD systems in order to cull games when they're not the "best version of." This is very visible in the early CD era when DOS, 3DO, TG CD, Sega CD, PSX, Sega Saturn might all have the same game. When this happens I try and only keep a game on one system so as to not duplicate it.

If it would be possible to feed this "exclusions" list I generate back on the next run - when dats are updated - that would be super helpful.

Could just be a text file with the exact name and region could work. The only moment that wouldn't is when they change the name of the games, but that doesn't happen too often.

**Comment by unexpectedpanda** [comment]
This has been implemented in 0.87, which should be out shortly. It's a bit of a power user feature, and as such you can shoot your own foot off with it if you're not careful. Still, here's what you'll be able to do:

- Keep a custom global filter list, which lets you exclude and include titles across all dats using either partial string matches (risky), full string matches (safer), or regex matches (have fun storming the castle!).
- Keep a custom system filter list per dat system, with the same abilities as the global filter list. Like clone lists it works off the `<name>` tag in the dat, so if you say, make a Coleco - ColecoVision system filter list, it'll apply across all ColecoVision dats until No-Intro changes the name.

There are nuances to take into account, and you'll want to read the documentation before you use the feature, but the feature will soon be in your hands.
