### ISSUE TITLE
[Nintendo - Game Boy Advance] Parent/Clone (language priority)

### ISSUE THREAD

**Issue by DiGiCoDe77** [unexpectedpanda/retool#191]
## Dat
Nintendo - Game Boy Advance (20220424-131656)

## Issue
Those two games are parent/clones:
All Grown Up! - Express Yourself (USA, Europe)
Razbitume! - Restez Branches! (Europe) (En,Fr)
https://gamefaqs.gamespot.com/gba/925094-all-grown-up-express-yourself/images/160345
https://www.planete-jeu.fr/Razbitume-Restez-Branches-/jaquette-HD-GBA-Razbitume-Restez-Branches-.jpg

**Comment by unexpectedpanda** [comment]
These are already in the clone list with that exact spelling, and the relationship works for the 20220318-080015 version of the DAT. 

Looks like Dat-o-matic has locked its downloads at the moment, if you could provide a copy of yours I'll take a look.

**Comment by DiGiCoDe77** [comment]
My bad, you're right!
But how to configure Retool to promote "Razbitume! - Restez Branches! (Europe) (En,Fr)" as the parent of "All Grown Up! - Express Yourself (USA, Europe)"?
My current region order is currently like this:
- France
- Europe
- World
- USA

**Comment by unexpectedpanda** [comment]
Related: #160.

For Retool v1, there's nothing you can do short of setting up custom include/exclude filters.

Retool v2 introduces more of a language bias by default, and is meant to resolve this issue. Sadly there's still plenty of work to do before it sees the light of day.

Still, here's a real world example I can test against and build toward :)

**Comment by unexpectedpanda** [comment]
This now works as expected in v2, promoting "Razbitume! - Restez Branches! (Europe) (En,Fr)" over "All Grown Up! - Express Yourself (USA, Europe)".
