### ISSUE TITLE
Sega MegaDrive: European Club Soccer/ World Trophy Soccer and EA Hockey/NHL Hockey not being recognised as clones.

### ISSUE THREAD

**Issue by Samington33** [unexpectedpanda/retool#194]
Wikipedia lists these as localised versions of the sane games. Retool misses them, as does No-Intro's Parent/Clone dat. Is this because the included teams are different?

Thanks for this great tool, saving me so much time☺️!

**Comment by unexpectedpanda** [comment]
Usually I don't pay too much attention to small things like team changes. In this case, both of these are clones I was unaware of. They'll be added to the next clone list update :)

**Comment by Samington33** [comment]
Awesome! I’ll let you know if I find any more, as I’ve just started on my RetroPie project☺️
