### ISSUE TITLE
MIA Dat xml attribute causes crash

### ISSUE THREAD

**Issue by FidoFuz** [unexpectedpanda/retool#197]
Datters have started to introduce a new mia attribute (for example in the Atari ST No-Intro Dat).  If the dat contains this attribute then retool will crash when attempting to load the dat.

**Comment by unexpectedpanda** [comment]
I'll need to redesign the GUI version of Retool so this doesn't look like a crash, and more usefully points out that the DAT doesn't follow standard.

I'll look into the new DTD-violating attribute. Weird to introduce yet another element though, the better choice would have been to use the existing `status` field.

**Comment by unexpectedpanda** [comment]
This is fixed in 1.10. The design changes though will be held until v2.
