### ISSUE TITLE
Nes errors on a fresh Dat from Retool using Clmamepro.

### ISSUE THREAD

**Issue by slider6996** [unexpectedpanda/retool#199]
**Describe the bug**
When creating NES dat from latest updated Dat file from Dat O Matic for NES ( HEADERED ) and using Clmamepro it shows alot of crc32 errors and when running full fix on both left and right side for scan it just dumps all the roms into the backup folder without fixing the errors, i even tried Romulus and it does same thing, just moves the roms into a backup folder without fixing the issues. 

**To reproduce**
Download latest NES dat file for No Intro from Dat O Matic. Create custom dat file using Retool ( default options for English ), put dat file into Clmamepro, select New scan with Check and Fix applied and will see the errors.

**Expected behavior**
To sort and select Roms how its suppose too

**Operating system**
- [ ] Windows 11 (older versions not supported)
- [ ] Ubuntu
- [ ] Other (please specify)

**Retool edition**
- [0.11 ] retool-gui.exe
- [ ] retool.py
- [ ] retool-gui.py

**Retool version**
For the command line edition of Retool, the version is shown when you run it with no other arguments.

For the GUI edition, click **Help**, then **About**.

**Are you using custom global or system filters? If so, list them below**

Global excludes:
Demos etc etc 
Global includes:

System excludes:

System includes:

**What other settings are you using?**

**Additional context**
didnt have this issue before i thought when i used program prior, at least on other systems, maybe im just missing something? When i get back home tomorrow ill do some more tests testing snes and see if it does same thing. 

On a fresh SNES dat download and test there is no errors using Retool then using the created dat with Clmame like the nes, maybe its just a nes thing?

For the error here i just selected Names and Size to show the errors below for the pictures

![error 1](https://user-images.githubusercontent.com/77522568/169630280-04f21828-0334-4b35-94bb-e0cc050866b5.png)

![error 2](https://user-images.githubusercontent.com/77522568/169630289-b2d7f2f9-6c25-4fc5-916b-7611620124b8.png)
.

**Comment by unexpectedpanda** [comment]
This is likely related to the new headered/non-headered DATs. Retool inserts the CLRMAMEPro/RomCenter header skipper lines in the DATs regardless of whether it's needed or not. I'll need to do a little testing.

**Comment by slider6996** [comment]
they are 100% headered as i thought i had headerless by mistake but i double checked to make sure and def headered.

**Comment by unexpectedpanda** [comment]
Okay, confirmed this is to do with the header skipper lines. Retool 1.12 should be up shortly, and it copies across CLRMAMEPro and Romcenter directives from the source DAT.

**Comment by unexpectedpanda** [comment]
Thanks for the heads up, this should be resolved in 1.12. Give a holler if not.

**Comment by slider6996** [comment]
Ok so update, it was bugging me why i was having this issue when i was like 99% sure i didnt have this issue before so i copied all the roms from download back into a folder and started over trying different things and the Parent Clone from Dat o Matic worked fine with the 1g1r mode with no errors but it deleted games it shouldnt hence me likeing the retool but when i made a dat with the retool i would get the error.

So i redid the dat from retool and when imported it into clmamepro i just instantly accepted the pop up about the header question without thinking about it and i think that was my boo boo, will post pic below of the pop up to confirm if im right, well it dont pop up no more unless u import a fresh dat of the nes so ill post pic of selecting the option manually. Honestly my only knowledge of headerless and headered is that the headerless is a no no for emulation so i always avoid it and thats the end of my knowledge and so when that pop up asking to skip the header skipper i just always hit yes.

When i hit no and rerun the scan it actually seems to scan properly and filter out properly so would that of caused the issue i described?


![pop up](https://user-images.githubusercontent.com/77522568/169643692-e5b25839-bbd3-4652-84f0-c62f1cfc7a95.png)

**Comment by unexpectedpanda** [comment]
The header skipper was previously incorrectly inserted by Retool in the headered DAT. Retool 1.12 fixes this. I suspect this is what caused your problem.

By not loading the header skipper on the DAT you created earlier, you've achieved the same effect.

**Comment by slider6996** [comment]
Alright ill retest once im back home and edit this post after updating.
