### ISSUE TITLE
102 Dalmatians - Dreamcast

### ISSUE THREAD

**Issue by dxzdxz1** [unexpectedpanda/retool#2]
Your script is keeping both US and UK (non-EU) version of 102 Dalmatians instead of remove the UK version.

Btw, is there a better way to inform you about the duplicates or should I open a new issue everytime I found a new duplicate?

Oh, and I just create a list of 1g1r for Wii. How can I share this with you?

**Comment by unexpectedpanda** [comment]
Thanks, I'll look into it!

Sometimes a missed clone might be as simple as a missing relationship in a clone list, other times it might be a bug in the program. Best to create a new issue for each problem.

Maybe Discord would be an easier place to chat: https://discord.gg/xsm44C
