### ISSUE TITLE
Suggestion: New Language - English-Friendly

### ISSUE THREAD

**Issue by rafaeldpb** [unexpectedpanda/retool#200]
Hi,

There is a lot of games that, although are in Japanese or European languages, can be played with relative ease. Most of action and puzzle games are in this category.

My suggestion is that a new language is added, "English-friendly". This would make retool a better tool yet, as many people would finally play some imported titles that they filtered before.

**Comment by unexpectedpanda** [comment]
Perhaps it's more "all languages" than "English-friendly", as these sorts of games can be played by most people.

While I appreciate the idea, it's a lot of manual work to maintain and requires going through titles one by one to identify them. Maybe one day as a community project, but today isn't that day.
