### ISSUE TITLE
A few NES clones not being found.

### ISSUE THREAD

**Issue by Samington33** [unexpectedpanda/retool#203]
Hi.

So … Continuing to put together my RetroPie build, and have just finished sorting out my NES set.

I actually found a fair few clones — clones according to Wikipedia — which were missed by Retool. I used v1.12, with all clonelists updated.

Here’s a quick and dirty list of the ones I found, hope it helps in some way.

URL: https://en.wikipedia.org/wiki/List_of_Nintendo_Entertainment_System_games

Original dat file used: "Nintendo - Nintendo Entertainment System (Headered) (20220518-120848).dat" (but also experienced the same result with the headerless dat).

Adventure Island (NA), Adventure Island Classic (EU).

Adventure Island II (NA), Adventure Island Part II (EU).

Al Anser Jr’s Turbo Racing (NA), Turbo Racing (EU).

Alex Demeo’s Race America(NA), Corvette ZR-1 Challenge (EU).

Bad Dudes (NA), Bad Dudes vs Dragon Ninja )EU).

Bomberman II(NA), Dynablaster (EU).

Contra (NA), Probotector (EU).

Super C (NA), Probotector II: Return of the Evil Forces (EU).

Fire ’n Ice (NA), Solomon’s Key II (EU).

Flight of the Intruder (NA), Phantom Air Mission (EU).

Galaga: Demons of Death (NA), Galaga (EU).

Ghosts ’n Goblins (NA), Ghost ’n Goblins (EU).

Goal II (NA), Eric Cantona’s Football Challenge (EU).

Heavy Shreadin’ (NA), Snowboard Challenge (EU).

Indiana Jones and The Last Crusade (Ubisoft), seems to keep both the NA and EU versions.

Joe & Mac (NA), Joe & Mac: Caveman Ninja (EU).

Kiwi Kraze (NA), The New Zealand Story (EU).

Life Force (NA), Life Force Salamander (EU).

N.C. Kids (NA), McDonaldland (EU).

Ninja Gaiden (NA), Shadow Warriors (EU).

Ninja Gaiden II: The Dark Sword of Chaos (NA), Shadow Warriors II (EU).

River City Ransom (NA), Street Gangs (EU).

S.C.A.T (NA), Action in New York (EU).

Shadow of the Ninja (NA), Blue Shadow (EU).

Tecmo Cup Soccer Game (NA), Tecmo Cup Football Game (EU).

Teenage Mutant Ninja Turtles (NA), Teenage Mutant Hero Turtles (EU).

Teenage Mutant Ninja Turtles II: The Arcade Game (NA), Teenage Mutant Hero Turtles II: The Arcade Game (EU).

Teenage Mutant Ninja Turtles: Tournament Fighters (NA), Teenage Mutant Hero Turtles: Tournament Fighters (EU).

Top Players’ Tennis (NA), Four Players’ Tennis (EU).

Track & Field (NA), Track & Field in Barcelona (EU).

Yoshi (NA), Mario & Yoshi (EU).

I'm wondering if this has something to do with the No-Intro dat itself, or maybe I'm doing something wrong? Kind of new to this.

Again, thanks for all your great work on this tool.

Cheers.

**Comment by unexpectedpanda** [comment]
This is a bug on my behalf. Nothing you've done wrong.

Because the headered/headerless NES DAT split is new, Retool isn't taking the (Headered) tag into account and associating it with the correct clone list. I'll need to push out an update to deal with this.

**Comment by unexpectedpanda** [comment]
Grab 1.13, this should fix your issues. Sorry for the oversight, and thanks for the heads up.
