### ISSUE TITLE
Should homebrew be in the Unlicensed category, too?

### ISSUE THREAD

**Issue by rafaeldpb** [unexpectedpanda/retool#208]
Lately, some dats have been adding a lot homebrew games with the tag (Aftermarket)(Homebrew). AFAIK, none of them are licensed, so should them be in the same category of (Unl) games?

**Comment by unexpectedpanda** [comment]
It probably should. I'll take a look when I next update the clone lists, thanks for the heads up.

**Comment by unexpectedpanda** [comment]
This has been addressed as of 1.14, Excluding unlicensed titles now also removes aftermarket and homebrew.
