### ISSUE TITLE
Missing Parent/Clone relationships on Nintendo Gamecube

### ISSUE THREAD

**Issue by katarak** [unexpectedpanda/retool#21]
Here's a few I found going through the listings recently.

These might be part of #20 with the compilation Issues.
2 Games in 1 - Bob L'eponge - Le Film + Tak 2 - Le Sceptre des Reves (France) (Disc 1) (Bob L'eponge - Le Film)
2 Games in 1 - Nickelodeon SpongeBob Schwammkopf - Der Film + Nickelodeon SpongeBob Schwammkopf - Schlacht um Bikini Bottom (Germany) (Disc 1)
2 Games in 1 - Nickelodeon SpongeBob Schwammkopf - Der Film + Nickelodeon SpongeBob Schwammkopf - Schlacht um Bikini Bottom (Germany) (Disc 2)"

Bakuten Shoot Beyblade 2002 - Nettou! Magne Tag Battle! (Japan) is Beyblade VForce - Super Tournament Battle (USA)
https://www.wikiwand.com/en/Beyblade:_Super_Tournament_Battle

Bokujou Monogatari - Shiawase no Uta (Japan) (Rev 1) is Harvest Moon - Magical Melody (USA)
https://www.wikiwand.com/en/Harvest_Moon:_Magical_Melody

Jikkyou World Soccer 2002 (Japan) is International Super Soccer 2002 
https://www.wikiwand.com/en/Jikky%C5%8D_World_Soccer_2002

Viewtiful Joe Revival (Japan) is a rerelease of Viewtiful Joe (USA

Zoids vs. II (Japan) (Rev 1) is Zoids: Battle Legends (US)
https://www.wikiwand.com/en/List_of_Zoids_video_games

Not bad for such a big list :P

**Comment by unexpectedpanda** [comment]
Thanks, greatly appreciate the links too :) I've added most of these to the clone lists, which will be updated shortly. I'll leave these open until I've had the opportunity to look at #20.
