### ISSUE TITLE
Retool chokes on "Microsoft - Xbox One (Digital) (20220703-091911).dat"

### ISSUE THREAD

**Issue by coreyemtp** [unexpectedpanda/retool#210]
**Describe the bug**
Whenever attempting to run the above mentioned dat in the gui, it crashes with a quick java error that I can see flash by in the command screen before it disappears.

**To reproduce**
From Retool GUI, choose either single dat or file of dats that contain the Xbox One (Digital) dat. Select any folder for the output. Click Go!

**Expected behavior**
Expect the DAT to process without crashing

**Operating system**
- [x] Windows 11 (older versions not supported)
- [ ] Ubuntu
- [ ] Other (please specify)

**Retool edition**
- [x] retool-gui.exe
- [ ] retool.py
- [ ] retool-gui.py

**Retool version**
v1.14

**Are you using custom global or system filters? If so, list them below**
No

**What other settings are you using?**
Default from "Use suggested region order for English speakers." Only other change is to have the two txt file results created under the Mode tab. 

**Additional**
This dat is ug-ly. I'm not expecting miracles on it, but thought it might be worth a look-see. For me, definitely not the end of the world if it simply cannot be processed.

**Comment by unexpectedpanda** [comment]
No-Intro has used double quotes and colons in their filenames, which are invalid characters. I'll create a workaround to solve the issue for now, but ultimately this must be fixed at the source.

**Comment by coreyemtp** [comment]
I'm not sure where to address it at the no-intro level, but I'll give it a shot. I figured it was something malformed, or just the sheer length of some of those filenames.

**Comment by unexpectedpanda** [comment]
They can be a little hard to get through to, short of the shoutbox.

I'll likely get this fixed on the next day or so.

**Comment by alvaromunoz** [comment]
Oops, I just did a [PR about this](https://github.com/unexpectedpanda/retool-clonelists-metadata/pull/1). Should I close it?

**Comment by unexpectedpanda** [comment]
Yes please :) Metadata files are auto-generated, so manual fixes will get overwritten with the next clone list update.

**Comment by alvaromunoz** [comment]
Got it. I'll wait for the fix, then. Thanks!

**Comment by unexpectedpanda** [comment]
Fixed in 1.15. Make sure to grab the latest Retool, but also make sure you update your clone lists. You should get an updated `Microsoft - Xbox One (Digital).json` in the `metadata` folder.

**Comment by coreyemtp** [comment]
Not to belabor a closed ticket, but xuom2 just addressed the issue and stated that the DAT is fixed. Woohoo!

**Comment by unexpectedpanda** [comment]
Great it's been fixed at the source :) It's likely No-Intro hasn't added any validation, so the issue might occur in the future.
