### ISSUE TITLE
Clrmamepro won't recognize Retool DAT as update

### ISSUE THREAD

**Issue by coreyemtp** [unexpectedpanda/retool#212]
**Describe the bug**
When adding newly Retool-ed DATs to clrmamepro, it won't recognize it as an updated DAT to an existing one.

**To reproduce**
Drag and drop Retool DATs to the clrmamepro profiler screen (assume it would be the same adding via the other methods)

**Expected behavior**
Clrmamepro should recognize the newly added DATs as updates to existing DATs (if present)

**Operating system**
- [x] Windows 11 (older versions not supported)
- [ ] Ubuntu
- [ ] Other (please specify)

**Retool edition**
- [x] retool-gui.exe
- [ ] retool.py
- [ ] retool-gui.py

**Retool version**
1.15 (from 1.14)

**Are you using custom global or system filters? If so, list them below**
No

**What other settings are you using?**
Default

**Additional context**
I believe the issue is that you embed the version number of Retool in the DAT's <header>/<name>. So when moving to a new version of Retool, the DAT is no longer recognized as the same. If it simply read (Retool) instead of (Retool %version%), I think it would work fine. 

Update: I tested my theory by going in and doing a find/replace on all instances in all the old Retool DATs of "Retool 1.14," changing it to "Retool 1.15". This was done in clrmamepro's "datfiles," "fastscans," and "settings" subdirectories. The "fastscans" subdirectory was file renaming only, while the other two required editing the file contents (they're txt only). Things work fine now, new DATs are recognized as updates.

**Comment by unexpectedpanda** [comment]
Thanks for this, you're absolutely right. This has already been corrected in v2, but I didn't backport it to v1. I'll bundle the change with the next update.

**Comment by unexpectedpanda** [comment]
Resolved in 1.16. Thanks for the heads up :)
