### ISSUE TITLE
No-Intro Sega - Beena not recognized (update: filtered titles message could be clearer)

### ISSUE THREAD

**Issue by X1pheR** [unexpectedpanda/retool#213]
## Dat
Sega - Beena (20200127-135209).dat

Dat downloaded directly from no-intro. Attached my own copy.

## Issue
It doesn't recognize the games in the dat file. It says there are none;
![image](https://user-images.githubusercontent.com/569396/178517149-beb4eaec-76d6-4494-b1ff-de7ce7135d10.png)

[Sega - Beena (20200127-135209).zip](https://github.com/unexpectedpanda/retool/files/9094070/Sega.-.Beena.20200127-135209.zip)

**Comment by unexpectedpanda** [comment]
I can't replicate this with default settings. Do you have a specific region order, have filtered by language, or excluded files?

For example, if you've only got USA in your region list, you'll see the same message, as the Beena set only includes games from Japan.

**Comment by X1pheR** [comment]
You are absolutely right. Thank you very much. It appeared there are only japanese language games in the set and I have the language at english only. Adding japanese fixed it. Perhaps indeed for message clarity it could be stated that nothing was found with the current region/language settings if any?

**Comment by unexpectedpanda** [comment]
Resolved in 1.16. Thanks for helping out!
