### ISSUE TITLE
[Microsoft - MSX] Parent/Clone

### ISSUE THREAD

**Issue by DiGiCoDe77** [unexpectedpanda/retool#214]
## Dat
Microsoft - MSX (20220712-020023)

## Issue
Nemesis (Japan, Europe) > Gradius (Japan) (WiiU Virtual Console)
https://www.mobygames.com/game/gradius

Nemesis 2 (Japan, Europe) (Alt) > Gradius 2 (Japan, Europe) (En) (WiiU Virtual Console)
https://www.mobygames.com/game/nemesis-2

Nemesis 3 - The Eve of Destruction (Japan, Europe) > Gofer no Yabo - Episode II (Japan) (WiiU Virtual Console)
https://gamefaqs.gamespot.com/msx/917744-nemesis-3

Antarctic Adventure (Europe) > Kekkyoku Nankyoku Dai Bouken (Japan) (WiiU Virtual Console)
https://gamefaqs.gamespot.com/msx/582281-antarctic-adventure

Knightmare II - The Maze of Galious (Japan) > Knightmare - Majou Densetsu (Japan) (WiiU Virtual Console)
https://gamefaqs.gamespot.com/msx/582974-the-maze-of-galious

Penguin Adventure (Japan, Europe) > Yume Tairiku Adventure (Japan) (WiiU Virtual Console)
https://gamefaqs.gamespot.com/msx/582337-penguin-adventure-yume-tairiku-adventure

**Comment by unexpectedpanda** [comment]
Done, thanks :)
