### ISSUE TITLE
[Microsoft - MSX2] Parent/Clone

### ISSUE THREAD

**Issue by DiGiCoDe77** [unexpectedpanda/retool#215]
## Dat
Microsoft - MSX2 (20220712-010411)

## Issue
Vampire Killer (Japan, Europe) > Akumajo Dracula (Japan) (WiiU Virtual Console)
https://gamefaqs.gamespot.com/msx/582105-vampire-killer

Treasure of Usas, The (Japan, Europe) > Treasure of the Usas (Japan) (WiiU Virtual Console)
https://gamefaqs.gamespot.com/msx/934851-usas

**Comment by unexpectedpanda** [comment]
Done, thanks :) I suspect both of these will have their titles altered at some point, so I'll have to keep an eye out.
