### ISSUE TITLE
[NEC - PC Engine - TurboGrafx 16] Parent/Clone

### ISSUE THREAD

**Issue by DiGiCoDe77** [unexpectedpanda/retool#216]
## Dat
NEC - PC Engine - TurboGrafx 16 (20220714-011011)

## Issue
New Adventure Island (USA > Adventure Island of Takahashi Master (Japan) (WiiU Virtual Console)
https://gamefaqs.gamespot.com/tg16/589049-new-adventure-island

Be Ball (Japan) > Chew-Man-Fu (USA, Europe) (WiiU Virtual Console)
https://gamefaqs.gamespot.com/tg16/579587-chew-man-fu

Wallaby!! - Usagi no Kuni no Kangaroo Race (Japan) > Kangaroo Race Wallaby in Rabbit Country!! (Japan) (WiiU Virtual Console)
https://gamefaqs.gamespot.com/tg16/589160-wallaby-usagi-no-kuni-no-kangaroo-race

Jaseiken Necromancer (Japan) > Necromancer (World) (WiiU Virtual Console)
https://gamefaqs.gamespot.com/tg16/589044-jaseiken-necromancer

PC Genjin - Pithecanthropus Computerurus (Japan) > PC Genjin (Japan) (WiiU Virtual Console) 

PC Genjin 2 - Pithecanthropus Computerurus (Japan) > PC Genjin 2 (Japan) (WiiU Virtual Console)

PC Genjin 3 - Pithecanthropus Computerurus (Japan) > PC Genjin 3 (Japan) (WiiU Virtual Console)

Shockman Shubibinman 2 -New Enemy- (Japan) > Shockman (USA, Europe)
https://gamefaqs.gamespot.com/tg16/589102-shockman

PC Geijin (Japan) (WiiU Virtual Console) > Air Zonk (USA, Europe) (WiiU Virtual Console)

Battle Chopper (World) (En,Ja) > Mr. Heli no Daibouken (Japan)
https://gamefaqs.gamespot.com/tg16/589039-mr-heli-no-daibouken

**Comment by unexpectedpanda** [comment]
Most of these are due to a typo on No-Intro's behalf. They should be fixed in the next release.

**Comment by unexpectedpanda** [comment]
Done, thanks :)
