### ISSUE TITLE
Crash loading DAT

### ISSUE THREAD

**Issue by FidoFuz** [unexpectedpanda/retool#218]
Some newer No-Intro DAT files (for example: "Nintendo - Nintendo DS (Decrypted) (20220804-144411).dat") are providing a namespace qualified XML tag.  For example:

< datafile xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://datomatic.no-intro.org/stuff https://datomatic.no-intro.org/stuff/schema_nointro_datfile_v1.xsd" >

Instead of:

< datafile >

This is causing Retool to crash when loading the DAT.

**Comment by unexpectedpanda** [comment]
Huh, so they're shifting to XSD over DTD. Thanks for the heads up, I'll look into it.

**Comment by unexpectedpanda** [comment]
Corrected in 1.17. Thanks again for the heads up :)
