### ISSUE TITLE
Question about alternate "revisions" or "versions" of the same game

### ISSUE THREAD

**Issue by BobbyBoyGaming** [unexpectedpanda/retool#219]
How can I make it so that Retool will always pick the revision with the highest numerical value (latest revision), within a group of otherwise identical roms from the same region, i.e. USA?

And can I also make it pick a "Director's Cut" or "Special Edition" of a game over the original/standard release?

**Comment by unexpectedpanda** [comment]
It should be picking the highest version in a region by default, no need to set any options.

Same with the special editions, so long as you've downloaded the clone lists first and the system is covered.

Is there something you're seeing where this doesn't happen?

**Comment by BobbyBoyGaming** [comment]
Oh ok perfect. No, I was just wondering because I didnt know about your program and I was using the original full-sized redump DATs with Romulus049, and the Romulus program completely trashed my PS1 library, by creating a bunch of extranous folders of clones/alternate-region/revision titles. It even littered my library with a bunch of demo discs that I suppose had some *.bin tracks in common with my personal selection of PS1 titles. 

I just found out about your program and I am going to have to re-run romulus (very slow) and I was just really really hoping I wouldnt further complicate things because I was really frustrated by the whole situation and cant continue to waste time on this type of activity. 

Anyway, thanks for the info, great program. I think its gonna save the day for me.

**Comment by BobbyBoyGaming** [comment]
Is there a program you personally reccomend for checking the roms? I am using romulus. I dont know if I am crazy but the thing appears to find more and more errors on each pass. 
So If I check a bunch of files and thew show up as green (all fine), and then I recheck those same files, some of then give error on a second pass... how the in the hell is that possible. i am about to give up on this. omg i am gonna go crazy... should have not even touched these files..

**Comment by unexpectedpanda** [comment]
Historically I've used CLRMamePro. It's definitely not the most intuitive user experience, but I've got the muscle memory now. [Here's a beginner guide](https://www.reddit.com/r/RetroPie/comments/mtzcy6/create_your_own_1g1r_set_for_redump_and_nointro/) for using it in tandem with Retool.

You might also want to check out RomVault, which is what people seem to be gravitating towards these days. Its design is more focused on keeping multiple sets up to date. It's still not the most user friendly experience, but after you get used to the flow, you can make it work reasonably well.
