### ISSUE TITLE
Option to keep the header information the same as the original dat

### ISSUE THREAD

**Issue by fanzines** [unexpectedpanda/retool#221]
In clrmamepro I like to use the www-dat option to easily know which dat files I need to update and download. One issue I am running into using Retool is that ,where it renames the header information, www-dat treats sees it as a new dat file. As such it is telling me that dat file needs to be updated even though the retool dat is based off the same version as the current No-Intro/Redump dat. I found that if I just copy and paste the header information from the old dat file into the retool one it works as it should. So I was wondering if there was anyway retool could have an option to keep the header information in the retool dat the same as the parent dat.

**Comment by unexpectedpanda** [comment]
I'll have a think about this one. I'm mostly focused on v2 at the moment, and I'm reluctant to expand the code base of v1. I'll add it to the list of potential changes.

**Comment by unexpectedpanda** [comment]
It's been a long wait, but added in v2.01.0.
