### ISSUE TITLE
[NES] Asia/Pirate/Beta clones treated as separate games 

### ISSUE THREAD

**Issue by iGom** [unexpectedpanda/retool#225]
## Dat
Nintendo - Nintendo Entertainment System (Headered) (20221216-121430).dat

## Issue
Retool seems to treat couples of Asia/Pirate/Beta clones as separate games
```
gui settings:
- z
- y
- log
- list
- exclude: Bd
```

from add-remove list

Multicarts:
```
+ 100-in-1 Contra Function 16 (Asia) (En) (Pirate)
+ 110 in 1 (Asia) (En) (Pirate)
+ 168-in-1 (Asia) (En,Ja) (AB CARD-15) (Aftermarket) (Pirate)
+ 18-in-1 (Asia) (En) (Pirate)
+ 1992 Gaishi 190-in-1 Hua Mian Xuan Guan (Asia) (En) (Pirate)
+ 2 in 1 Geminim-Siamond (World) (Aftermarket) (Unl)
+ 2-in-1 - Conan & Rygar (Asia) (En) (RC58) (Pirate)
+ 23-in-1 Super Game (Greece) (En) (K23-001) (Pirate)
+ 24K 4-in-1 Baozheng Zhen Ka Quanji (Asia) (En) (Pirate)
+ 3 in 1 Supergun (Asia) (En) (Unl)
+ 31-in-1 (Asia) (En) (Pirate)
+ 32-in-1 (Asia) (En) (Pirate)
+ 4-in-1 (NC-80) (Asia) (En) (Pirate)
+ 4-in-1 (SN 406) (Asia) (En) (Pirate)
+ 58-in-1 (Asia) (En,Zh) (FL-58) (Pirate)
+ 64-in-1 (Asia) (En) (Pirate)
+ 68-in-1 (Asia) (En) (WQ2006 D) (Pirate)
+ 77-in-1 (Asia) (En) (WQ1806 E) (Aftermarket) (Pirate)
+ 999-in-1 - Duck Hunt + Mario Bros. (Asia) (En) (Aftermarket) (Pirate)
+ 9999999-in-1 (Asia) (En) (Aftermarket) (Pirate)
+ Asder - 20 in 1 (USA) (Unl)
```

1. 8 Eyes (USA) is a parent

```
+ 8 Eyes (World) (Pixel Heart) (Aftermarket) (Unl)
+ 8 Eyes (USA)
	- 8 Eyes (Japan)
	- 8 Eyes (World) (Aftermarket) (Unl)
```

2. [Action 53 Vol. 3 - Revenge of the Twins (World) (v1.5) (Aftermarket) (Unl)](https://datomatic.nointro.org/index.php?page=show_record&s=45&n=4106) is a parent

```
+ Action 53 Vol. 3 - Revenge of the Twins (USA) (Limited Edition) (Aftermarket) (Unl)
+ Action 53 Vol. 3 - Revenge of the Twins (World) (v1.5) (Disk 1) (Aftermarket) (Unl)
+ Action 53 Vol. 3 - Revenge of the Twins (World) (v1.5) (Disk 2) (Aftermarket) (Unl)
+ Action 53 Vol. 3 - Revenge of the Twins (World) (v1.5) (Aftermarket) (Unl)
	- Action 53 Vol. 3 - Revenge of the Twins (World) (v1.3) (Aftermarket) (Unl)
```

3. [Action 53 Vol. 4 - Actually 54 (World) (Aftermarket) (Unl)](https://datomatic.nointro.org/index.php?page=show_record&s=45&n=3509) is a parent

```
+ Action 53 Vol. 4 - Actually 54 (World) (Aftermarket) (Unl)
+ Action 53 Vol. 4 - Actually 54 (World) (Disk 1) (Aftermarket) (Unl)
+ Action 53 Vol. 4 - Actually 54 (World) (Disk 2) (Aftermarket) (Unl)
+ Action 53 Vol. 4 - Actually 54 (World) (Disk 3) (Aftermarket) (Unl)
+ Action 53 Vol. 4 - Actually 54 (World) (Disk 4) (Aftermarket) (Unl)
```

4. [Limited Edition](https://datomatic.nointro.org/index.php?page=show_record&s=45&n=3585) is a clone of [Anguna - Scourge of the Goblin King (World) (Rev 1) (Aftermarket) (Unl)](https://datomatic.nointro.org/index.php?page=show_record&s=45&n=3958)

```
+ Anguna - Scourge of the Goblin King (USA, Europe) (Limited Edition) (Aftermarket) (Unl)
+ Anguna - Scourge of the Goblin King (USA, Europe) (Aftermarket) (Unl)
	- Anguna - Scourge of the Goblin King (USA) (Beta) (Aftermarket) (Unl)
	- Anguna - Scourge of the Goblin King (World) (Rev 1) (Aftermarket) (Unl)
```

5. Clones of [Another World (USA) (Aftermarket) (Unl)](https://datomatic.nointro.org/index.php?page=show_record&s=45&n=4298)

```
+ Another World (World) (Digital Release) (Aftermarket) (Unl)
+ Another World (World) (Glitchcore Version) (Aftermarket) (Unl)
+ Another World (USA) (Aftermarket) (Unl)
	- Another World (World) (Alpha) (Aftermarket) (Unl)
```

6. [Apuntalo, Cheril! (World) (Es) (Aftermarket) (Homebrew)](https://datomatic.nointro.org/index.php?page=show_record&s=45&n=4090) is a clone

```
+ Apuntalo, Cheril! (World) (Es) (Aftermarket) (Homebrew)
+ Cheril the Writer (World) (Aftermarket) (Homebrew)
```

7. Clone of [Arkanoid (USA)](https://datomatic.nointro.org/index.php?page=show_record&s=45&n=0118)

```
+ Arkanoid (Asia) (En) (LC10) (Pirate)
+ Arkanoid (USA)
	- Arkanoid (Japan) (En)
```

8.Assimilate (World) (Nessylum Games) (Aftermarket) (Homebrew) is a parent

```
+ Assimilate (World) (Nessylum Games) (Aftermarket) (Homebrew)
+ Assimilate (USA) (RetroUSB) (Aftermarket) (Homebrew)
	- Assimilate (USA) (RetroUSB) (Aftermarket) (Homebrew) (Alt)
```

9. [Pico Pico Grand Adventure (Japan) (Aftermarket) (Homebrew)](https://datomatic.nointro.org/index.php?page=show_record&s=45&n=3693) is a clone

```
+ Basse Def Adventures (USA, Europe) (Fr) (Aftermarket) (Homebrew)
+ Pico Pico Grand Adventure (Japan) (Aftermarket) (Homebrew)
```	

10. [Batman III (Asia) (En) (Aftermarket) (Pirate)](https://datomatic.nointro.org/index.php?page=show_record&s=45&n=4587) is a clone of [Batman Returns (Europe)](https://datomatic.nointro.org/index.php?page=show_record&s=45&n=0210)

```
+ Batman III (Asia) (En) (Aftermarket) (Pirate)
+ Batman Returns (USA)
	- Batman Returns (Europe)
	- Batman Returns (Europe) (Beta)
```

11. [Honoo no Rangerman (World) (Ja) (Aftermarket) (Unl)](https://datomatic.nointro.org/index.php?page=show_record&s=45&n=4614) is a clone of [Blazing Rangers](https://datomatic.nointro.org/index.php?page=show_record&s=45&n=4612)

```
+ Blazing Rangers (World) (NTSC) (Aftermarket) (Unl)
	- Blazing Rangers (World) (PAL) (Aftermarket) (Unl)
+ Honoo no Rangerman (World) (Ja) (Aftermarket) (Unl)
```

12. [Blockage (World) (Aftermarket) (Homebrew)](https://datomatic.nointro.org/index.php?page=show_record&s=45&n=4073) is a parent

```
+ Blockage (World) (Aftermarket) (Homebrew)
+ Blockage (World) (v0.3.1) (NESDev 2019) (Aftermarket) (Homebrew)
```

13. Clones of [DABG - Double Action Blaster Guys (World) (Aftermarket) (Homebrew)](https://datomatic.nointro.org/index.php?page=show_record&s=45&n=4404)

```
+ DABG - Double Action Blaster Guys (World) (NESDev 2014) (Aftermarket) (Homebrew)
+ DABG - Double Action Blaster Guys (World) (Aftermarket) (Homebrew)
	- DABG - Double Action Blaster Guys (World) (Aftermarket) (Homebrew) (Alt)
+ DABG - Double Action Blaster Guys (World) (Rev A) (Action 53 Version) (Aftermarket) (Homebrew)
	- DABG - Double Action Blaster Guys (World) (Action 53 Version) (Aftermarket) (Homebrew)
```

14. [Depths (World) (Ludum Dare 44 Version) (Aftermarket) (Homebrew)](https://datomatic.nointro.org/index.php?page=show_record&s=45&n=3749) is a parent

```
+ Depths (World) (Ludum Dare 44 Version) (Aftermarket) (Homebrew)
+ Depths (World) (v2.0) (Aftermarket) (Homebrew)
```

15. Clones of [Escape from Atlantis, The (USA) (Proto 2) (Unl)](https://datomatic.nointro.org/index.php?page=show_record&s=45&n=0663)

```
+ Escape From Atlantis (USA) (Piko Interactive) (Aftermarket) (Unl)
+ Escape from Atlantis, The (USA) (Proto 2) (Unl)
	- Escape from Atlantis, The (USA) (Proto 1) (Unl)
```

16. [Euchre (World) (Aftermarket) (Homebrew)](https://datomatic.nointro.org/index.php?page=show_record&s=45&n=3891) is a parent

```
+ Euchre (World) (Aftermarket) (Homebrew)
+ Euchre (World) (NESDev 2018) (Aftermarket) (Homebrew)
```

17. [Excitebike (Asia) (En) (LA21) (Pirate)](https://datomatic.nointro.org/index.php?page=show_record&s=45&n=4599) is a clone

```
+ Excitebike (Asia) (En) (LA21) (Pirate)
+ Excitebike (Japan, USA) (En) (Virtual Console)
	- Excitebike (Europe)
	- Excitebike (Europe) (Virtual Console)
	- Excitebike (Japan, USA) (En)
	- Excitebike (Japan, USA) (En) (GameCube Edition)
	- Excitebike (USA) (e-Reader Edition)
	- Excitebike (World) (Switch Online)
```

18. Clones of [Falling (World) (v1.1) (Aftermarket) (Homebrew)](https://datomatic.nointro.org/index.php?page=show_record&s=45&n=4166)

```
+ Falling (World) (v1.01) (Aftermarket) (Homebrew)
+ Falling (World) (v1.1) (Aftermarket) (Homebrew)
	- Falling (World) (v1.0) (Aftermarket) (Homebrew)
```

19.  [Flappy Bird (World) (Aftermarket) (Homebrew)](https://datomatic.nointro.org/index.php?page=show_record&s=45&n=4097) is a parent

```
+ Flappy Bird (World) (Aftermarket) (Homebrew)
+ Flappy Bird (World) (Easier) (Aftermarket) (Homebrew)
```

20. [Ghoul Grind - Night of the Necromancer (World) (Aftermarket) (Homebrew)](https://datomatic.nointro.org/index.php?page=show_record&s=45&n=3508) is a parent.

```
+ Ghoul Grind - Night of the Necromancer (World) (Aftermarket) (Homebrew)
+ Ghoul Grind - Night of the Necromancer (World) (Dreamcast Version) (Aftermarket) (Homebrew)
```

21. [Gruniozerca 2 - The Great Cavy Rescue! (World) (En,Pl) (Aftermarket) (Homebrew)](https://datomatic.nointro.org/index.php?page=show_record&s=45&n=3471) is a parent

```
+ Gruniozerca 2 - The Great Cavy Rescue! (World) (En,Pl) (Aftermarket) (Homebrew)
+ Gruniozerca 2 (World) (En,Pl) (Rev 1) (NESDev 2017) (Aftermarket) (Homebrew)
	- Gruniozerca 2 (World) (En,Pl) (NESDev 2017) (Aftermarket) (Homebrew)
```

22. [Gruniozerca 3 - The Great Cavy Clean-Up! (World) (En,Pl) (Aftermarket) (Homebrew)](https://datomatic.nointro.org/index.php?page=show_record&s=45&n=3472l) is a parent

```
+ Gruniozerca 3 - The Great Cavy Clean Up! (World) (NESDev 2018) (Aftermarket) (Homebrew)
+ Gruniozerca 3 - The Great Cavy Clean-Up! (World) (En,Pl) (Aftermarket) (Homebrew)
```

23. All of those are clones of [GunTner (World) (ax1147) (Beta) (Build 252) (Aftermarket) (Homebrew)](https://datomatic.nointro.org/index.php?page=show_record&s=45&n=4460)

```
+ GunTner (World) (Beta) (Build 47) (Aftermarket) (Homebrew)
+ GunTner (World) (Beta) (Build 53) (Aftermarket) (Homebrew)
+ GunTner (World) (Beta) (Build 65) (Aftermarket) (Homebrew)
+ GunTner (World) (ax1147) (Beta) (Build 157) (Aftermarket) (Homebrew)
+ GunTner (World) (ax1147) (Beta) (Build 158) (Aftermarket) (Homebrew)
+ GunTner (World) (ax1147) (Beta) (Build 186) (Aftermarket) (Homebrew)
+ GunTner (World) (ax1147) (Beta) (Build 194) (Aftermarket) (Homebrew)
+ GunTner (World) (ax1147) (Beta) (Build 208) (Aftermarket) (Homebrew)
+ GunTner (World) (ax1147) (Beta) (Build 209) (Aftermarket) (Homebrew)
+ GunTner (World) (ax1147) (Beta) (Build 211) (Aftermarket) (Homebrew)
+ GunTner (World) (ax1147) (Beta) (Build 221) (Aftermarket) (Homebrew)
+ GunTner (World) (ax1147) (Beta) (Build 231) (Aftermarket) (Homebrew)
+ GunTner (World) (ax1147) (Beta) (Build 235) (Aftermarket) (Homebrew)
+ GunTner (World) (ax1147) (Beta) (Build 239) (Aftermarket) (Homebrew)
+ GunTner (World) (ax1147) (Beta) (Build 243) (Aftermarket) (Homebrew)
+ GunTner (World) (ax1147) (Beta) (Build 249) (Aftermarket) (Homebrew)
+ GunTner (World) (ax1147) (Beta) (Build 252) (Aftermarket) (Homebrew)
+ GunTner (World) (v2.73) (Beta) (Build 141) (Aftermarket) (Homebrew)
+ GunTner (World) (v2.73) (Beta) (Build 143) (Aftermarket) (Homebrew)
+ GunTner (World) (v2.73) (Beta) (Build 167) (Aftermarket) (Homebrew)
+ GunTner (World) (v2.73) (Beta) (Build 190) (Aftermarket) (Homebrew)
+ GunTner (World) (v2.73) (Beta) (Build 4) (Aftermarket) (Homebrew)
+ GunTner (World) (v2.73) (Beta) (Build 5) (Aftermarket) (Homebrew)
+ GunTner (World) (v2.73) (Beta) (Build 132) (Aftermarket) (Homebrew)
	- GunTner (World) (Beta) (Build 132) (Aftermarket) (Homebrew)
```

24. [Happy Camper (USA) (Proto) (Unl)](https://datomatic.nointro.org/index.php?page=show_record&s=45&n=4045) is a parent

```
+ Happy Camper (USA) (NintendoAge) (Aftermarket) (Unl)
+ Happy Camper (USA) (Proto) (Unl)
```

25. [Incident, The - Standalone Level Creator (USA) (Aftermarket) (Homebrew)](https://datomatic.nointro.org/index.php?page=show_record&s=45&n=3484) is a clone

```
+ Incident, The - Standalone Level Creator (USA) (Aftermarket) (Homebrew)
+ Incident, The (USA) (Remastered) (Aftermarket) (Unl)
	- Incident, The (USA) (Aftermarket) (Unl)
```

26. [Justice Duel (World) (Aftermarket) (Unl)](https://datomatic.nointro.org/index.php?page=show_record&s=45&n=3428) is a parent

```
+ Justice Duel (USA) (RetroGameCon 5 Edition) (Aftermarket) (Unl)
+ Justice Duel (World) (Aftermarket) (Unl)
```

27. [KYFF (World) (Aftermarket) (Homebrew)](https://datomatic.nointro.org/index.php?page=show_record&s=45&n=4408) is a parent

```
+ KYFF (World) (Aftermarket) (Homebrew)
+ KYFF (World) (Rob Bryant's) (Aftermarket) (Homebrew)
```

28. Clones of [Kart Racer '86 (World) (2022-10-31) (Proto) (cfcb276) (Aftermarket) (Homebrew)](https://datomatic.nointro.org/index.php?page=show_record&s=45&n=4552)

```
+ Kart Racer '86 (World) (2022-10-26) (Proto) (879cbea) (Aftermarket) (Homebrew)
+ Kart Racer '86 (World) (2022-10-28) (Proto) (8d96be2) (Aftermarket) (Homebrew)
+ Kart Racer '86 (World) (2022-10-31) (Proto) (aa9d5fd) (Aftermarket) (Homebrew)
+ Kart Racer '86 (World) (2022-10-31) (Proto) (cfcb276) (Aftermarket) (Homebrew)
```

**Comment by iGom** [comment]
sorry, I accidentally hit "submit new issue" before I finished describing the problem..., I"m editing it at the moment...

**Comment by iGom** [comment]
These are not all, I'll update the issue later.

**Comment by unexpectedpanda** [comment]
The NES DAT is just a mess right now, being flooded with aftermarket and homebrew titles which in turn introduce a glut of new tags. It's some Wild West stuff, and a pain to maintain.

There's talk of splitting aftermarket titles out into their own DAT. Hopefully soon.

I'll look into this next time I update the No-Intro clone lists.

**Comment by iGom** [comment]
Yeah, I've seen that topic on the forum and opinions are diveded, as long as they keep original dat with everything like now I support the idea

**Comment by iGom** [comment]
dat and some clones updated

**Comment by iGom** [comment]
From now on, pirate and homebrew will be excluded from standard datfiles by default and xml will follow soon which means I have to do the new whole list.

**Comment by unexpectedpanda** [comment]
I just noticed. Looks like all they've done is turn off the checkboxes for pirate and homebrew on the download page. More frustrating than a clean split as far as Retool is concerned, and managing clone list errors.

The list will still come in handy in its current form, I appreciate your efforts. I was just updating the clone lists for v2, it's still vaguely on target for the end of the month.

**Comment by iGom** [comment]
I see, so I'll keep updating the current list

**Comment by unexpectedpanda** [comment]
Thanks. Looks like No-Intro has some teething problems with the change, as tends to be the case whenever they change something. Hopefully it'll stabilize soon.

**Comment by unexpectedpanda** [comment]
Okay, these have been incorporated into the v2 clone lists. I'm now continuing into titles starting with L-Z. Given the current instability of the NES DAT, I'll hold the update until v2 is ready, it's not worth the double work putting this into the v1 clone lists.

**Comment by iGom** [comment]
> Okay, these have been incorporated into the v2 clone lists. I'm now continuing into titles starting with L-Z. Given the current instability of the NES DAT, I'll hold the update until v2 is ready to be released, it's not worth the double work putting this into the v1 clone lists.

as you wish, I was locally saving my copy with an additional Japanese region for big update. 
btw I don't know it's that gonna be case in the v2, but it seems some parents with no any clones are treated like clones of other games, e.g.
[1942 (Japan, USA) (En)](https://datomatic.nointro.org/index.php?page=show_record&s=45&n=0005) is a parent with no clones

```
+ 1942 (Japan, USA) (En)
	- 1943 - The Battle of Midway (Japan) (Beta)
	- 1943 - The Battle of Midway (USA)
	- 1943 - The Battle of Valhalla (Japan)
```

**Comment by unexpectedpanda** [comment]
Yep, 1942 is an error, raised in #226.

**Comment by unexpectedpanda** [comment]
These changes have been folded into the v2 clone lists.
