### ISSUE TITLE
NES Parents, Metadata, Priority Order

### ISSUE THREAD

**Issue by tomdrakecanada** [unexpectedpanda/retool#226]
## Dat
Nintendo - Nintendo Entertainment System (Headered) (20221215-125422)

## Issue
These might not all be clone issues, and I know NES is changing. But hoping some of these might help you, in case it's also how retool prioritizes some of them. Using suggested English region order, and English language filter. I'm excluding most of the checkboxes, except Educational, Pirate, Preproduction, and Unlicensed.

If there's anything I messed up, please let me know! I figure I could add things like "Namco Museum Archives" to custom exclude, but if it was really the only English option, I'd still want it. I think there are collections out there that might have the only English translation of Japanese games.

### Issue > What retool added to dat. > What I think should have been added _as well_.

1943 - The Battle of Midway is parent to 1942. These should be separate games? > 1943 - The Battle of Midway (USA) > 1942 (Japan, USA) (En)

I think Tengen games were different (Tetris for sure). If that's the case for Pac-Man too, it shouldn't have Namco version as it's parent? > Pac-Man (USA) (Namco) > Pac-Man (USA) (Tengen) (Unl)

### Issue > What retool added to dat. > What I think should have been added _instead_.

Dig Dug II is parent to Dig Dug II - Trouble in Paradise, so it accepts collection over original? > Dig Dug II (USA, Europe) (Namco Museum Archives Vol 2) > Dig Dug II Trouble in Paradise (USA)

Preferring collection over Unl? > Rolling Thunder (World) (Namcot Collection, Namco Museum Archives Vol 2) > Rolling Thunder (USA) (Unl)

USA over World? > Donkey Kong Original Edition (USA, Europe) (3DS Virtual Console) > Donkey Kong (World) (Rev 1)

En over nolang? 1.1 is most recent https://vectrex28.itch.io/wordle-nes > Wordle (World) (v1.02) (Aftermarket) (Homebrew) > Wordle (World) (v1.1) (Aftermarket) (Homebrew)

Metadata file has Homebrew for 1, Unl for 2, is Homebrew preferred? Maybe just the lack of a decimal on 1.0.1? 1.0.2 is most recent https://iodinedynamics.itch.io/whatremains > What Remains (World) (v1.01) (Aftermarket) (Homebrew) > What Remains (World) (v1.0.2) (Aftermarket) (Homebrew)

I think it's just the 1.1 version isn't in metadata? > Haunted Halloween '86 (World) (Remastered Onslaught Edition) (Aftermarket) (Unl) > Haunted Halloween '86 (World) (v1.1) (Remastered Onslaught Edition) (Aftermarket) (Unl)

(World) (Rev 1) isn't in metadata, probably a new name for (USA, Europe) (Rev A)? > Anguna Scourge of the Goblin King (USA, Europe) (Aftermarket) (Homebrew) > Anguna Scourge of the Goblin King (World) (Rev 1) (Aftermarket) (Homebrew)

**Comment by unexpectedpanda** [comment]
Thanks for this, I appreciate the detail. Most of my focus is now on getting v2 out the door, so it might be a little time before I can make the changes.

On the metadata front: unfortunately No-Intro has stopped offering downloads for their NES, SNES, and 3DS DBs (different to DATs) among others, so bit by bit the metadata is going to reduce in accuracy as time goes on. Apparently server load is an issue for those systems, and although they've moved to daily download packs for the DBs, those systems haven't returned. Sadly scraping the site is off the cards too, as they have an overly aggressive banning system in place. I'll keep asking for change, but I don't have high hopes there.

**Comment by unexpectedpanda** [comment]
I refer a lot to v2 here, as it's not worth me tweaking the v1 code base at this point in time.

> 1943 - The Battle of Midway is parent to 1942. These should be separate games? > 1943 - The Battle of Midway (USA) > 1942 (Japan, USA) (En)

Spot on, I'm thinking this might have been a typo. This has been fixed and will be shipped out with v2.

> I think Tengen games were different (Tetris for sure). If that's the case for Pac-Man too, it shouldn't have Namco version as it's parent? > Pac-Man (USA) (Namco) > Pac-Man (USA) (Tengen) (Unl)

[Pac-Man appears to be pretty much identical](https://www.youtube.com/watch?v=QPlOEywiVII&ab_channel=DefunctGames).

> Dig Dug II is parent to Dig Dug II - Trouble in Paradise, so it accepts collection over original? > Dig Dug II (USA, Europe) (Namco Museum Archives Vol 2) > Dig Dug II Trouble in Paradise (USA)

> USA over World? > Donkey Kong Original Edition (USA, Europe) (3DS Virtual Console) > Donkey Kong (World) (Rev 1)

It depends on the options you've set as to whether modern edition rips (Namco Museum titles, Virtual Console titles etc), get chosen over the original system releases. With default settings, _Dig Dug II - Trouble in Paradise (USA)_ gets chosen as the parent if USA is the top region, in both v1 and v2. If you prefer modern edition rips, it selects _Dig Dug II - Trouble in Paradise (USA, Europe) (Virtual Console)_. Donkey Kong parent selection appears to be bugged in v1, as it selects the Virtual Console title by default. This is fixed in v2.

> Preferring collection over Unl? > Rolling Thunder (World) (Namcot Collection, Namco Museum Archives Vol 2) > Rolling Thunder (USA) (Unl)

Unlicensed versions of titles are demoted versus production titles, even if those production titles are in another region. That behavior is reversed for v2, but can be re-enabled with an option.

> En over nolang? 1.1 is most recent https://vectrex28.itch.io/wordle-nes > Wordle (World) (v1.02) (Aftermarket) (Homebrew) > Wordle (World) (v1.1) (Aftermarket) (Homebrew)

v2 now assumes nolang == English.

**Comment by unexpectedpanda** [comment]
v2 is now released, addressing things as detailed in the previous post.
