### ISSUE TITLE
Feature Request: The ability to separate games that were completed but never released from the other Beta/Prototype games

### ISSUE THREAD

**Issue by TomTurbine** [unexpectedpanda/retool#227]
There are quite a few games that were completed but never actually released and these typically are given the labels of Prototype and Beta along with all the other games that were just flat out never finished.

Having an option where those unreleased games could be kept in the dat file while the unfinished games were pruned would be a huge benefit to many.

**Comment by unexpectedpanda** [comment]
I appreciate the angle. However this is something for No-Intro to correct upstream, by replacing the `(Beta)` or `(Prototype)` tags where appropriate with `(Unreleased)` or some equivalent.

**Comment by TomTurbine** [comment]
Thanks, the funny thing is, I personally put in that suggestion their forums using that exact same tag already.
