### ISSUE TITLE
Retool not excluding non-selected regions

### ISSUE THREAD

**Issue by Newyears1978** [unexpectedpanda/retool#228]
**Describe the bug**
New to the program - several files/dats have gone without hitch, but working on a Commodore Amiga PC right now, when I convert it using only US/Europe/World - looks fine but then when I load up that dat files, all regions are present. I am not using any other filters besides those three regions. I re-ran that same PC file through retool and this time it removed 597 more files, however, it still contained a ton of regions.

Maybe I am just misunderstanding how it works, but assumed it would only show the selected regions. 

**To reproduce**
Simple retooling the Amiga P/C Dat.

**Expected behavior**

**Operating system**
 Windows 10 

**Retool edition**
retool-gui.exe
0.12
1.18

**Are you using custom global or system filters? If so, list them below**
Global

Global excludes:
None

Global includes:
None

System excludes:
None

System includes:
None

Here's an image of Romcenter when I loaded the 1G1R Retooled Dat
![image](https://user-images.githubusercontent.com/4557630/211452091-364e4fd6-8117-459a-9b39-ee5de4545e22.png)

Update: Okay I think this may be my own misunderstanding. It may be that Romcenter is seeing those games with names like (En,Fr, De, Es, It) and counting those as "Regions"

So I assume what I should be doing is skipping the region filtering part of Romcenter altogether, is that correct?

**Comment by unexpectedpanda** [comment]
Yep, don't use any 1G1R features in ROM managers. Retool's already done that job for you.

If you check the DAT directly in a text editor, it should only have the regions you've selected.

**Comment by Newyears1978** [comment]
I feel dumb, but at least I figured it out right after haha.

Epic tool, so appreciated! Thanks for the reply as well, all is working now :)
