### ISSUE TITLE
Feature to exlude roms that don't exist

### ISSUE THREAD

**Issue by dd900** [unexpectedpanda/retool#229]
I keep my roms seperated in sub-folders. Licensed, Unlicensed, Homebrew, etc... It would be nice if I could point Retool to one of the directories and have only the roms that are in the folder included in the output list.

**Comment by unexpectedpanda** [comment]
You might have another outcome in mind, but that sounds to me like you're after dir2dat functionality? That's already present in tools like CLRMAMEPro, Sabretools, and more if that helps.

**Comment by dd900** [comment]
I already use ClrMAMEPro to make the directories with their new dat format they use now. I'm going to exagerate a bit to try and get my point across. And no custom filters.

lets say 4 versions of a rom exist
Rom (USA) -> p
Rom (Europe) -> c
Rom (Japan) -> c
Rom (World) -> c

Retool Regions are in this order
USA
Europe
World
Japan

In my rom folder I only have
Rom (World)
Rom (Japan)

Retool would output Rom (USA) as the obvious choice, but since I only have Rom (World) and Rom (Japan) I want Retool to choose Rom (World). Does that help at all? Thanks for your time.

**Comment by unexpectedpanda** [comment]
Ahh, you'd like 1G1R based on the files you already have. Or to look at it another way, to use folder contents as an additional filter on top of the existing processing.

This involves file management, not just outputting a DAT, which is beyond Retool's scope. It's not a use case I plan on supporting.
