### ISSUE TITLE
Excluding "Demos and Samples" doesn't exclude numbered samples

### ISSUE THREAD

**Issue by katarak** [unexpectedpanda/retool#23]
I saw this on the SNES dat.

Rockman X2 (Japan) (Sample 1)
Rockman X2 (Japan) (Sample 2)

Pop 'n Twinbee (Japan) also has 2 samples. 
both samples are included in the dat.

In this case these games are also available in other region. Megaman X2 (don't know region) and Pop 'n Twinbee (USA, Europe)

**Comment by unexpectedpanda** [comment]
Cheers! Numbered samples are handled in 0.87 thanks to this, which won't be too far away now.

Demos/samples are treated as separate entities to preproduction/full versions, which is why the full versions in other regions don't match. This is by design.
