### ISSUE TITLE
Make the GUI window resizable (or smaller)

### ISSUE THREAD

**Issue by dd900** [unexpectedpanda/retool#230]
Thank you for the amazing app by the way.

The resolution on my laptop is 1366x768. When viewing the GUI I cannot see or press the "Go!" button unless I set the Taskbar to hidden or auto-hide.

Windows 10
Retool GUI

**Comment by unexpectedpanda** [comment]
Resizable is unlikely given the layout, but I'll put some thought into it. The next revision is definitely less tall for this very reason, though :)

**Comment by clalcofe** [comment]
I'd like to chime in about the same issue. If you could make it so the Go button is visible on a 1280x720 screen, that'd be wonderful!

**Comment by unexpectedpanda** [comment]
The new design fits in a 1280x720 res on Windows 10. That's as low a resolution as it supports though, 800x600 is a no go.

Still polishing up the final bits. Some features have taken longer than expected to implement.
