### ISSUE TITLE
Parent/Clone relationship miss Super Baseball 2020 (USA) -> 2020 Super Baseball (Japan)

### ISSUE THREAD

**Issue by shinji257** [unexpectedpanda/retool#231]
## Dat
No-Intro Super Nintendo

## Issue
* Super Baseball 2020 (USA) is the parent to 2020 Super Baseball (Japan). | https://datomatic.no-intro.org/index.php?page=show_record&s=49&n=0003

Seems there was a couple of old name changes on the USA one and Retool didn't catch it when it built the parent/clone relationship for filtering.

**Comment by unexpectedpanda** [comment]
Fixed in the v2 clone lists.
