### ISSUE TITLE
Add "Export" as country (used in arcade dats)

### ISSUE THREAD

**Issue by rufotheone-fr** [unexpectedpanda/retool#232]
## Dat
Arcade dats (or consoles like Neo Geo CD)

## Issue
Add "Export" as country

* Examples here: http://redump.org/discs/system/ngcd/region/Eu/

**Comment by unexpectedpanda** [comment]
Ahh, I was treating it as a standard tag, which likely means the region is set as "Unknown". Which ultimately is kind of true...

I'll investigate for v2.

**Comment by unexpectedpanda** [comment]
Fixed in beta 5.
