### ISSUE TITLE
[Feature Request] Can't resize the Program Window

### ISSUE THREAD

**Issue by BobbyBoyGaming** [unexpectedpanda/retool#237]
Can you please allow the program window to be resized?

It makes it a lot easier to use the "Include/Exclude" fields under the "User Filter" tab. In its current state, I currently have a list of entries in the Exclude field, but since I have to use separate lines for each term then it is very difficult to use such a small space. Please consider making the inclusion/exclusion windows a bit spacier by allowing the resize window feature.

So I guess I am requesting two things that the program can be maximized but also that this in turn affects those smaller "user filter" windows so that they are easier to work in.

**Comment by unexpectedpanda** [comment]
This isn't as simple as clicking a resize button. I'll look into it for a future iteration.

**Comment by unexpectedpanda** [comment]
Added into beta 5.
