### ISSUE TITLE
System user filter exclude not working

### ISSUE THREAD

**Issue by BobbyBoyGaming** [unexpectedpanda/retool#238]
## Dat

No-Intro's "Redump Custom":
Nintendo - GameCube - NKit RVZ [zstd-19-128k] (2023-01-09)

Redump.org:
Nintendo - GameCube (2023-03-05 21-29-39)

## Issue

The USA title "Harry Potter and the Sorcerer's stone" is included and therefore
The European variants "Harry potter and the philosopher's stone" should be excluded completely.
As well as the Japanese version of the game "Harry Potter: To Kenja no Ishi" (or whatever, I don't speak Japanese)

<img width="585" alt="image" src="https://user-images.githubusercontent.com/46551829/223955527-e6bad299-752a-4726-9af9-8ce189d83f44.png">

* Missed or incorrect title (Europe) > Original title (USA) | https://www.wikipedia.org
* 
<img width="579" alt="image" src="https://user-images.githubusercontent.com/46551829/223953960-a340d88f-22df-43ef-9bbb-06191520176c.png">

**Comment by unexpectedpanda** [comment]
This works fine for me with both the original Redump GameCube DAT and the No-Intro custom DAT. [The titles are already in the clone list](https://github.com/unexpectedpanda/retool-clonelists-metadata/blob/main/clonelists/Nintendo%20-%20GameCube%20(Redump).json#L702). If it's not working for you, make sure to download the clone lists before processing.

**Comment by BobbyBoyGaming** [comment]
No user filters, in fact, my user filters weren't even working at all when I did try to use them.
I will try updating the clone lists again and see if this helps. Very strange, because I did already produce 1G1R DATs and they did work well for the most part. 

At one point I had this list in the "Exclude" list but none of these key words (Partial matches) did anything, and I also don't see how any of these would have messed up the harry potter games. But I am pretty sure I produced these particular Nkit Gamecube retool dats without any of these filters anyway, because I hadnt started playing with the exclusion stuff until later.

Pokemon
Barbie
Mary-Kate
Yu-Gi-Oh
Naruto
Digimon
Dragon Ball
Puzzle
Pool
Sudoku
Disney's
Disney
Disney-Pixar
Pixar
Dreamworks
Nickelodeon
Ben 10
Dance
Dancing
Beat
Deal or No Deal
Who Wants To Be A Millionaire
Singstar
Jumpstart
Kidz
karaoke
Sesame Street
Pet
Petz
Harvest Moon
Bratz
Rock Band
Guitar Hero
Puyo
Puff Girls
Final Fantasy
Online
Bust-A-Move
Rocksmith
Persona
Hello Kitty
My

**Comment by unexpectedpanda** [comment]
No problems in the excludes as far as I can see. Let me know how you go with the clone lists. If you've got `Nintendo - GameCube (Redump).json` in the `clonelists` subfolder, then there's something else afoot.

**Comment by unexpectedpanda** [comment]
The global exclude user filter is working for me, but looks like the system exclude isn't working. I'll look into it.

**Comment by unexpectedpanda** [comment]
It's a name change in the No-Intro DAT that's causing the issues. There's already an exception in Retool for when it lived on dats.site, so I'll need to add another to cover it.

System user filters work fine with the Redump DAT.

**Comment by unexpectedpanda** [comment]
This should be fixed now in beta 2. Let me know how it goes.

**Comment by BobbyBoyGaming** [comment]
Cool, can't test it now but I will when I get home later

**Comment by BobbyBoyGaming** [comment]
There's still something sketchy about the filters, I dont know how I might be using them incorrectly but they simply do not delete the titles I want them to.

For example (same filter list as shown above, however I removed the last entry "My" it was not specific enough).
I wanted  "My" to remove "My horse" "My pet" and other dumb stuff like that, but it instead removed the "Myst" series, which would indicate that this filter actually works. However, when you look at every other user filter entry, none of them did anything. 

I still have all the Yu-Gi-Oh! games, all the Final Fantasy games. For some reason the Hello Kitty filter did work, but I still have all the Disney games...

It seems like the partial match is only for a single word not "partial match for a whole title [group of words]"?
I don't know whats going on. I would play around with the regular expression stuff but its such a pain, that I am trying to avoid it as much as possible. Because by the time I learn how to use regex properly, I would have just removed each title by hand myself.


[Retool Exceptions Key Words.txt](https://github.com/unexpectedpanda/retool/files/10946102/Retool.Exceptions.Key.Words.txt)

[Sony - PlayStation 2 (2023-03-07 01-04-26) (Retool 2023-03-10 12-57-45) [-aAbBcDdekmMoPpruv] log.txt](https://github.com/unexpectedpanda/retool/files/10946105/Sony.-.PlayStation.2.2023-03-07.01-04-26.Retool.2023-03-10.12-57-45.-aAbBcDdekmMoPpruv.log.txt)

I attched my exclusion list text file as well as a PS2 Redump DAT I tried to apply those filters to (under the system-specific settings tab). 
I tried applying the same settings both as "global" and as "system specific" and I'm getting very similar issues with both when it comes to difficulty removing certain titles.

**Comment by unexpectedpanda** [comment]
I don't think you're using them incorrectly. I'll dig into it.

**Comment by unexpectedpanda** [comment]
All the defined excludes should now be removed in beta 3. Give it a try and let me know.

A few tips on partial matches:

* The longer the string, the more likely you are to get the result you want. For example, `Pet` also removes titles with _Pete_ and _Peter_ in them.
* You've excluded `Harvest Moon`, but that just means the Japanese title _Bokujou Monogatari_ takes over. To remove the related titles as well, you can use `<Harvest Moon>`. The same goes for `Petz`, where _Dogz_ and _Catz_ just end up taking its place. `<Petz>` works around that.

**Comment by BobbyBoyGaming** [comment]
I tested the filters on Beta 4 and they do seem to work almost flawlessly now.
I did notice a game called Tetris World was being removed for no apparent reason, but I deleted those logs and dats. I will keep playing around with it, and if I notice anything big I will post it here, however the filters do seem to work well now.

**Comment by unexpectedpanda** [comment]
With the exclude list you've provided, Tetris World survives for me. I'll close this up for now, but if you find another problem feel free to start a new issue.
