### ISSUE TITLE
[v2] System/DAT override for output directory not working

### ISSUE THREAD

**Issue by retroNUC** [unexpectedpanda/retool#240]
Defined an override output folder for the system/DAT, but it still placed the output file in the global default.

![image](https://user-images.githubusercontent.com/71151161/224456584-389cbe79-b16f-4545-acff-53cf35d2450f.png)

![image](https://user-images.githubusercontent.com/71151161/224456743-ac21e995-9a67-4671-975e-61cd56dc9bf6.png)

Congrats on the v2 release, by the way! If I notice anything else, I'll let you know.

**Comment by unexpectedpanda** [comment]
Cheers! I can see the problem in the screenshot, the (Decrypted) tag has snuck through. I'll take a look as soon as I can.

**Comment by unexpectedpanda** [comment]
This should be fixed in beta 3. Give it a try and let me know.

**Comment by retroNUC** [comment]
Tested on Beta 4. Correct location for dat and name txt, but not for log txt.

**Comment by unexpectedpanda** [comment]
Good catch. So many little things to keep track of with the system settings.

It'll be fixed when I get the next update out.

**Comment by unexpectedpanda** [comment]
Fixed in beta 5.
