### ISSUE TITLE
[v2] Feature request - Ability to deprioritize compilations?

### ISSUE THREAD

**Issue by retroNUC** [unexpectedpanda/retool#241]
Reading through changelogs and new documentation, the new compilation behaviour for v2 seems to be prioritizing compilations for the purposes of being the most 'optimal' in terms of number of files / data size in a 1G1R set.

However, this does go against my personal preference of individual games where possible (the behaviour from v1, I believe), which is much preferred when the set ends up being used in a frontend where it scrapes metadata / screenshots / etc. It seemed to be most people's preference when going through compilation-related bugs from v1 as well, with most logging issues to ask for removal of compilations.

Tracing through the logic, hopefully it would just be an option in the frontend to skip processing rule `REF0072: Looking for this ideal combination: ...`

**Comment by unexpectedpanda** [comment]
Compilations are always tricky work (straight up removal ended up not really working), but yes, this is on my to do list.

I'm aware there are preferences for single titles for hacks and retro achievements too.

**Comment by unexpectedpanda** [comment]
Individual titles are now preferred over compilations as of v2 beta 8.

Take in mind individual titles aren't always selected. If there's a compilation that offers a title with a higher primary region or primary language, or has a higher clone list priority, it is selected instead.
