### ISSUE TITLE
PS1 more Missing Parent/Clone relationships

### ISSUE THREAD

**Issue by tjwoosta** [unexpectedpanda/retool#25]
I audited my 1g1r set in launchbox and found a few more missing parent/clone relationships for PS1

Final Fantasy Origins (USA)     is     Final Fantasy Origins - Final Fantasy (Europe)
Freestyle Boardin' '99 (USA)     is     Zap! Snowboarding Trix '98 (Japan)
Jackie Chan Stuntmaster (USA)     is     Jackie Chan Stuntmaster (Europe) (Recalled)
NASCAR Racing (USA)     is     NASCAR Racing - Season 96 (Japan)
Pipe Dreams 3D (USA)     is     World Greatest Hits Series Vol. 2 - Pipe Dreams 3D (Japan)
Pro Pinball - Big Race USA (USA)     is     World Greatest Hits Series Vol. 1 - Pro Pinball - Big Race USA (Japan)
Street Sk8er 2 (USA)	   is      Street Boarders 2 (Japan)
Street Racer (USA)     is     Street Racer Extra (Japan)
TNN Motorsports HardCore TR (USA)     is     C3 Racing - Car Constructors Championship (Europe) (En,Fr,De,Es,It) (Rev 1)
Tyco R-C - Assault with a Battery (USA)     is     World Greatest Hits Series Vol. 5 - Tyco R-C - Assault with a Battery (Japan)

**Comment by tjwoosta** [comment]
And a couple more after some manual database matching.
WWF SmackDown! 2 - Know Your Role (USA)    is     Exciting Pro Wres 2 (Japan)
Speedball 2100 (USA)    is     World Greatest Hits Series Vol. 3 - Speedball 2100 (Japan)
Tom Clancy's Rainbow Six (USA)    is     World Greatest Hits Series Vol. 4 - Tom Clancy's Rainbow Six (Japan)

**Comment by unexpectedpanda** [comment]
> Final Fantasy Origins (USA) is Final Fantasy Origins - Final Fantasy (Europe)

Not quite. _Final Fantasy Origins (USA)_ contains both FFI & II. _Final Fantasy Origins - Final Fantasy (Europe)_ is just the first game. As such, the first is a superset of the second. To get just FFO USA, use the supersets option.

In saying that, I need to have a rethink on what is a compilation vs what is a supserset, and what's included and what's not. See #20 for more details.

> Freestyle Boardin' '99 (USA) is Zap! Snowboarding Trix '98 (Japan)
> Jackie Chan Stuntmaster (USA) is Jackie Chan Stuntmaster (Europe) (Recalled)
> NASCAR Racing (USA) is NASCAR Racing - Season 96 (Japan)
> Street Racer (USA) is Street Racer Extra (Japan)
> Pro Pinball - Big Race USA (USA) is World Greatest Hits Series Vol. 1 - Pro Pinball - Big Race USA (Japan)
> Pipe Dreams 3D (USA) is World Greatest Hits Series Vol. 2 - Pipe Dreams 3D (Japan)
> Speedball 2100 (USA) is World Greatest Hits Series Vol. 3 - Speedball 2100 (Japan)
> Tom Clancy's Rainbow Six (USA) is World Greatest Hits Series Vol. 4 - Tom Clancy's Rainbow Six (Japan)
> Tyco R-C - Assault with a Battery (USA) is World Greatest Hits Series Vol. 5 - Tyco R-C - Assault with a Battery (Japan)

Nice, all added :)

> Street Sk8er 2 (USA) is Street Boarders 2 (Japan)

Looks like this applies to the prequel too, so two matches for the price of one :)

> TNN Motorsports HardCore TR (USA) is C3 Racing - Car Constructors Championship (Europe) (En,Fr,De,Es,It) (Rev 1)

All three of these related titles (Max Power Racing is the other) are slightly different (some graphics, cars etc), but yep, they are pretty much the same game, so added.

Retool 0.87 is going through the testing phase atm and is the priority, but the clone lists with these updates will go out at the same time.

**Comment by unexpectedpanda** [comment]
Okay, changed my mind. _Final Fantasy Origins (USA)_ isn't a superset but a collection. It should be the parent now when an English-speaking region is ranked higher than Japan.
