### ISSUE TITLE
Bug: Language prioritization is ignored

### ISSUE THREAD

**Issue by prklx2** [unexpectedpanda/retool#251]
With the latest 2.00.0 version of Retool it seems that the languages are ignored (completely?).
The easiest way to confirm this bug is with bigger sets that have a lot of regional variants like PS1 and PS2.

For example, using PS1 redump dat: I have Finland as the top region and Finnish as the top language and still the exported list has
`Disney-Pixar Monsters, Inc. - Scare Island (Europe)`
instead of the Finnish variant:
`Disney-Pixar Monsterit Oy - Saeikkysaari (Finland)`

Also seems to happen with Scandinavian releases and other non-English European releases.

`Harry Potter and the Philosopher's Stone (Europe) (En,Fr,De)`
instead of Scandinavian variant
`Harry Potter and the Philosopher's Stone (Scandinavia) (Sv,No,Fi)`

`Need for Speed - Road Challenge (Europe) (En,Es,It)`
instead of the Swedish release
`Need for Speed - Road Challenge (Europe) (En,Sv)`
Swedish language is higher on my list than Spanish and Italian. I had all the languages included in this test.

This worked fine in previous releases and the higher region/language was always prefered when selecting the titles.

**Comment by unexpectedpanda** [comment]
> For example, using PS1 redump dat: I have Finland as the top region and Finnish as the top language and still the exported list has
>Disney-Pixar Monsters, Inc. - Scare Island (Europe)
>instead of the Finnish variant:
>Disney-Pixar Monsterit Oy - Saeikkysaari (Finland)

For me, the Finnish title is selected when using either a custom global or system language list.

>Also seems to happen with Scandinavian releases and other non-English European releases.
>
>Harry Potter and the Philosopher's Stone (Europe) (En,Fr,De)
>instead of Scandinavian variant
>Harry Potter and the Philosopher's Stone (Scandinavia) (Sv,No,Fi)

For me, the Scandinavian title is selected over the European one when using either a custom global or system language list.
>
>Need for Speed - Road Challenge (Europe) (En,Es,It)
>instead of the Swedish release
>Need for Speed - Road Challenge (Europe) (En,Sv)

I'm getting the Swedish version with the language order:

- Finnish
- English
- Swedish
- Spanish
- Italian

And then just adding any language afterward.

Are you using global or system languages here? Could you provide your `user-config.yaml` and, if applicable, `config/systems/Sony - Playstation (Redump).yaml`? I feel like I'm missing something. If anything I suspect v2.00.0 Beta 8 would be the issue or perhaps something going wrong with metadata, subsequent updates didn't touch the language code.

**Comment by unexpectedpanda** [comment]
Looks like you had the system language override on, but it's identical to the global override. Beta 6 did have an issue with system languages not working. Good to hear a clean start fixed it, although I don't know how it could hold onto that issue when overwriting with 2.00.0 :/ _Maybe_ if you're using the Python version and somehow one of the changed files wasn't overwritten, but otherwise, I'm stumped.

I'll close this up for now, but it's definitely something for me to keep an eye on, thanks for the heads up.
