### ISSUE TITLE
Feature request: Option to reduce compilation duplicates even more

### ISSUE THREAD

**Issue by tpmoney** [unexpectedpanda/retool#252]
In some systems games were released in both individual forms and multi pack games. For example the GBA had a number of "2 in 1" packs, or the NES Super Mario + Duck Hunt cartridge. Right now the 1G1R filtering prefers to drop the individual games for their X in Y collection and while it's possible to build up a set of partial matches / regexes to drop them, it isn't quite as simple as just matching against "2 in 1" because some games / cartridges were only released as a combo pack. It would be handy to have a option to say that you prefer the individual games over their collections when all the parts of a collection were released as individual games.

**Comment by unexpectedpanda** [comment]
This is already the case, unless the individual game doesn't support your language, features a higher region, or is set higher in the clone list. You might be running an old version, the change was made in beta 8.

**Comment by tpmoney** [comment]
That would be it, I was running beta 7. Re-ran against the list and my hand filtering and found this difference:

```
TITLES WITH CLONES
==================
...
+ Classic NES Series - Dr. Mario (USA, Europe)
  - 2 Games in 1 - Dr. Mario + Puzzle League (Europe) (En,Fr,De,Es,It)
  - Dr. Mario & Panel de Pon (Japan)
  - Famicom Mini 15 - Dr. Mario (Japan)

...

TITLES WITHOUT CLONES
==================

+ 2 Games in One! - Dr. Mario + Puzzle League (USA)
```

From a trace it looks like this is because `Puzzle League` wasn't ever released outside of the combo pack. Might be worth having an option that removes collections if and only if all the games in the collection are available as individual games.

Appreciate it and all the work you put into this tool.

**Comment by unexpectedpanda** [comment]
I might be misunderstanding, but that's exactly how it works now. Compilations get kept if they contain a title not available individually.

The basic approach is they are split into virtual versions of their constituent titles before any comparison is done. If that virtual title is the only one in the group, then the associated compilation ends up being kept, even though one of its other titles might already be represented as an individual title.

It does occasionally make what looks like a confusing clone assignment, but that's the nature of the beast. The final output should still be correct.

**Comment by tpmoney** [comment]
Yeah I didn't explain the option suggestion well enough. In the case of the example I was suggesting an option that says 

>Because `Puzzle League` was never released standalone, then prefer the compilation and don't include `Classic NES Series - Dr. Mario`

If `Puzzle League` had been available as a standalone, prefer the individual games. The default settings make sense, and I can certainly see where coding that logic would be a lot of complexity for a not very common concern that for now could be addressed with user filters.

**Comment by unexpectedpanda** [comment]
Got it, you're looking to reduce duplicates further where possible. That was originally in scope as an option, but compilations are complex so I opted for a single path after early experiments didn't work out.

I'll leave this as a feature request for now, maybe one day.

**Comment by unexpectedpanda** [comment]
The compilation version of Super Mario World has a [few tweaks](https://www.mariowiki.com/Super_Mario_All-Stars_%2B_Super_Mario_World) compared to the standalone, making it a superset. It's not an untouched collection of the two titles.

**Comment by unexpectedpanda** [comment]
I think I've tracked five or six different ways people would like compilations processed. I definitely understand that people want to organize things in a way that fits their specific scenario.

To set realistic expectations, all things compilations are very low priority for me. Getting it to where it is now took considerable effort, and I'm loathe to add more complexity to that part of Retool.

That's not saying never; just that many other things are likely to be completed before I come back to this.

**Comment by unexpectedpanda** [comment]
Compilation handling options have been added in v2.03.0.
