### ISSUE TITLE
Issue #78 is back in version 2.0 (Tech Demo in Genesis - Megadrive dat)

### ISSUE THREAD

**Issue by Goratrix** [unexpectedpanda/retool#254]
Looks like https://github.com/unexpectedpanda/retool/issues/78 is still (or again?) present in 2.0. I just ran the Megadrive dat file, with 'Select all' exclusions (and no other options changed from default) and these three demos remained in the output dat.

**Comment by unexpectedpanda** [comment]
v2 was a complete rewrite, which included new regex. Looks like this particular variant slipped the net for the demo regex.

Fixed in v2.00.1.
