### ISSUE TITLE
Unlicensed Games Being Excluded Even When Unchecked

### ISSUE THREAD

**Issue by espiox** [unexpectedpanda/retool#257]
**Describe the bug**
I have Retool configured to include Unlicensed games in Global Settings (I have no per-system overrides turned on), but for at least some systems they're being excluded anyway.

**To reproduce**
Run Retool against the latest Game Boy and/or Game Boy Color DATs with Unlicensed unchecked in Exclusions tab.

**Expected behavior**
Unlicensed games included in DAT.

**Operating system**
Windows 11

**Retool edition**
retool-gui.exe

**Retool version**
2.00.1

**Are you using custom global or system filters? If so, list them below**

Global excludes:
Add-ons
Applications
Audio
BIOS
Coverdiscs
Demos etc
Manuals
Promotional
Video

Global includes:
Bad dumps
Bonus discs
Educational
MIA
Multimedia
Pirate
Preproduction
Unlicensed

System excludes:
[none]

System includes:
[none]

**What other settings are you using?**
Prefer licensed versions over unlicensed, aftermarket or homebrew titles

**Comment by unexpectedpanda** [comment]
Unchecking an exclude is not the same as forcing those title types to be included. The checkbox solely determines whether or not a title type is excluded.

As such, the unlicensed titles in this case are still subject to 1G1R selection (meaning things like lower versions can be removed), and can potentially be replaced where licensed equivalents exist (and it looks like you've selected that option).

Do you have examples of the specific titles that were excluded?

**Comment by unexpectedpanda** [comment]
I'm going to guess closing the issue means you figured it out and things are operating as expected.

Let me know if you hit roadblocks otherwise.

**Comment by espiox** [comment]
Yeah, it was something silly elsewhere in the process that was causing the problem! Appreciate your help though.
