### ISSUE TITLE
Missing Parent/Clone relationships on Sony PlayStation

### ISSUE THREAD

**Issue by DiGiCoDe77** [unexpectedpanda/retool#26]
First of all, thanks for your wonderful tool!

## Dat
Sony - PlayStation - Datfile

## Issue
**F1 World Grand Prix - Saison 2000 (France)** is a clone of **F1 World Grand Prix (Europe)**
https://psxdatacenter.com/games/P/F/SLES-03346.html

**Junior Sports Fussball (Germany)** is a clone of **Junior Sports Football (Europe)**
https://psxdatacenter.com/games/P/J/SLES-03579.html

**Roger Lemerre - La Selection des Champions (France)** is a clone of **LMA Manager 2001 (Europe)**
https://psxdatacenter.com/games/P/L/SLES-02975.html

**Telefoot Manager (France)** is a clone of **Premier Manager Ninety Nine (Europe)**
https://psxdatacenter.com/games/P/P/SLES-01544.html

**Rayman Junior - Level 1 (Europe) (En,Fr,De,Es,It)** is a clone of **Rayman Brain Games (USA)**
https://psxdatacenter.com/games/U/R/SLUS-01265.html

**Comment by unexpectedpanda** [comment]
Cheers, these will be in the next update :)
