### ISSUE TITLE
No-Intro NES dat generating an error message

### ISSUE THREAD

**Issue by specialt1212** [unexpectedpanda/retool#263]
**Describe the bug**
Retool 2.00.4
-------------
* Reading DAT file: "G:\Tools & System Backups\_Retool (1G1R)\_dats\_FROM_DOM_Nintendo -
  Nintendo Entertainment System (Headered) (Private) (20230520-071425).dat"
* Validating DAT file... done.

|  DAT DETAILS
|  Description: Nintendo - Nintendo Entertainment System (Headered) (Private)
|  Author/s: aci68, Arctic Circle System, baldjared, BigFred, bikerspade, BitLooter, Blank, C.
   V. Reynolds, chillerecke, DeadSkullzJr, DeriLoko3, EggmanPEI, einstein95, fuzzball, Gefflon,
   Hiccup, jimmsu, Just001Kim, kazumi213, Lesserkuma, Madeline, Money_114, NESBrew12, niemand,
   nnssxx, norkmetnoil577, NovaAurora, omonim2007, Powerpuff, PPLToast, rarenight, relax,
   RetroUprising, Rifu, sCZther, SonGoku, Special T, Tauwasser, ToeKnee, togemet2, UnlockerPT,
   Vigi, xuom2
|  URL: https://www.no-intro.org
|  Version: 20230520-071425
|  Numbered dat: No

* Processing DAT file... done
* Applying clone list categories... done.
* Applying clone list overrides... done.
* Analyzing clone list variants... done.
* Applying category and user excludes... done.
* Removing titles without specified regions... done.
* Selecting 1G1R titles [#####!              ] (!) 1/4 [25%] in 5.0s

Retool has had an unexpected error. Please raise an issue at
https://github.com/unexpectedpanda/retool/issues, attaching
the DAT file that caused the problem and the following trace:

multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "multiprocessing\pool.py", line 125, in worker
  File "multiprocessing\pool.py", line 48, in mapstar
  File "modules\chooseparent.py", line 1960, in choose_parent_process
  File "modules\chooseparent.py", line 545, in choose_date
  File "modules\titletools.py", line 986, in get_date
ValueError: invalid literal for int() with base 10: ''
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "retoolgui.py", line 175, in run
  File "retool.py", line 212, in main
  File "modules\chooseparent.py", line 1649, in choose_parent
  File "multiprocessing\pool.py", line 367, in map
  File "multiprocessing\pool.py", line 774, in get
ValueError: invalid literal for int() with base 10: ''

The error occurred on this file:
G:\Tools & System Backups\_Retool (1G1R)\_dats\_FROM_DOM_Nintendo - Nintendo Entertainment System (Headered) (Private) (20230520-071425).dat

======================================================

**To reproduce**
It happens ever time I try to process this dat

[_FROM_DOM_Nintendo - Nintendo Entertainment System (Headered) (Private) (20230520-071425).zip](https://github.com/unexpectedpanda/retool/files/11523250/_FROM_DOM_Nintendo.-.Nintendo.Entertainment.System.Headered.Private.20230520-071425.zip)

**Expected behavior**
A new dat should be created but retool generates the error listed above

**Operating system**
- Windows 10 Pro

**Retool edition**
- retool-gui.exe

**Retool version**
2.00.4

**Are you using custom global or system filters? If so, list them below**
Global excludes:
Everything on the exclusions tab except bad dumps and unlicensed (see attachment)

_*you can ignore the dat loaded in this image it was just the one I had loaded when I took the printscreen. The only dat giving me an error is the one I linked above_
![Preferences - 04](https://github.com/unexpectedpanda/retool/assets/134172949/34e13d3e-4d9c-44d0-bd1e-b03baa8ad545)

**What other settings are you using?**
everything else default

**Comment by unexpectedpanda** [comment]
Just No-Intro introducing yet another inconsistent date format.

It looks like an attempt at RFC 3339 without the time zone. I'll look into it.

**Comment by unexpectedpanda** [comment]
After doing some digging -- this one is my fault. I didn't process this particular date format properly. Fixed in 2.00.5.
