### ISSUE TITLE
Titles being as both parent and clone

### ISSUE THREAD

**Issue by 0xC0D3D34D** [unexpectedpanda/retool#265]
**Describe the bug**
Retool 2 is keeping clones in the output dat as both are being set as parent of each other.

eg
Finding Nemo - The Continuing Adventures (Europe) (En,Es,It,Sv,Da)
Finding Nemo - The Continuing Adventures (USA, Europe)

All seem to be happening with (Europe) + (USA, Europe) variations.
I think there are 19 occurrences in this dat. Is it an issue with handling variants with multiple regions?
When traced only the first one shows for Europe, surely both should match for European region.

**To reproduce**
Set Europe as highest priority region, tick all excludes. Run latest No-intro GBA dat

**Expected behavior**
Keep the Europe version of the game that matches language (Eng as no language set), this was the behavior in v1

**Operating system**
- [ ] Windows 10 (older versions not supported)
- [X] Ubuntu
- [ ] Other (please specify)

**Retool edition**
- [ ] retool-gui.exe
- [ ] retool.py
- [X] retool-gui.py

**Retool version**
2.00.0-2.00.5

**Are you using custom global or system filters? If so, list them below**

No filters only all exclusions ticked

**What other settings are you using?**

Europe region moved to the top

**Comment by unexpectedpanda** [comment]
At the individual region filtering stage, the following happens:

* USA multi-region titles are grouped with USA titles.
* European single titles are grouped with European titles.

As such, both titles go through to the stage where all the regions are bundled together and compared, but there aren't enough checks there to filter things further down to just one winner, which confuses things.

In the next version, Retool adds two fallbacks: first a check is done based on user language order preference. If that fails, it tries to give priority to the title with the most regions.

**Comment by unexpectedpanda** [comment]
Fixed in v2.01.0.
