### ISSUE TITLE
Think I found a missing Megadrive/Genesis clone

### ISSUE THREAD

**Issue by Samington33** [unexpectedpanda/retool#266]
Hello,

I think I might have found a clone which Retool missed in the latest No-Intro Genesis/Megadrive dat.

After running Retool, I had both of the following titles:
Bonanza Bros. (Japan, Europe) (En) (Rev A);
Bonanza Bros. (USA, Europe, Korea) (En) (Rev B)

I’m guessing these are the same game, and just got missed by the clone lists?

I did run the --update command before processing the dat.

All the best, and thanks for this great tool. Real life saver!

**Comment by unexpectedpanda** [comment]
This is probably related to #265. I'm implementing a new feature at the moment, I'll look into it when I can.

**Comment by unexpectedpanda** [comment]
Confirmed -- the fix is in the next release (not out yet).
