### ISSUE TITLE
I think I found a few XBOX clones

### ISSUE THREAD

**Issue by SiriusVI87** [unexpectedpanda/retool#267]
I believe I found a few clones:

"Roger Lemerre - La Selection des Champions 2003 (France)" seems to a clone of "LMA Manager 2003 (Europe)"

Same goes for LMA Manager 2004 and LMA Manager 2005.

"Shikigami no Shiro Evolution" seems to be an updated version of "Shikigami no Shiro". But I cannot confirm that with certainty. I can't find any info of the game "Shikigami no Shiro" without "Evolution" for the XBOX, but redump lists them both. When starting the games, I found that "Shikigami no Shiro Evolution" has an "Evo Mode" which "Shikigami no Shiro" does not have.

"X-Men 2 - Wolverine's Revenge (Europe)" seems to a clone of "X2 - Wolverine's Revenge (USA)"

"Double-S.T.E.A.L (Japan)" seems to be a clone of "Wreckless - The Yakuza Missions (USA)"

"Pro Beach Soccer (Europe) (En,Fr,De,Es,It,Pt)" seems to be a clone of "Ultimate Beach Soccer (USA)"

"Crash (Europe) (En,Fr,De,Es,It)" seems to be a clone of "Totaled! (USA)."

**Comment by unexpectedpanda** [comment]
Fixed, thanks!
