### ISSUE TITLE
SNES Missing Clone Relationships

### ISSUE THREAD

**Issue by possiblyneal** [unexpectedpanda/retool#269]
## Dat
Nintendo - Super Nintendo Entertainment System (20230704-100620)

## Issue
* Bubsy II (World) (Bubsy Two-Fur) (Unl) > Bubsy II (USA) | https://bubsy.fandom.com/wiki/Bubsy_Two-Fur
* Bubsy in - Claws Encounters of the Furred Kind (World) (Bubsy Two-Fur) (Unl) > Bubsy in - Claws Encounters of the Furred Kind (USA) | https://bubsy.fandom.com/wiki/Bubsy_Two-Fur
* Trials of Mana (World) (Beta) (Collection of Mana, 2019-04-02) > Trials of Mana (World) (Rev 1) (Collection of Mana)

Thanks for your hard work on all of this. Its a huge convenience and time saver :)

**Comment by possiblyneal** [comment]
I've also found a possible incorrect clone:

* Super Tetris 2 + Bombliss - Genteiban | there was a different set of levels added https://tetris.wiki/Super_Tetris_2_%2B_Bombliss

**Comment by unexpectedpanda** [comment]
Retool now catches the _Bubsy Two-Fur_ titles. I've reported the Trials of Mana title to No-Intro (they shouldn't be combining the date with the _Collection of Mana_ tag).

> Super Tetris 2 + Bombliss - Genteiban | there was a different set of levels added

This is one of those times I need to make a judgement call as to whether something should be considered a clone or not. For background, _Bombliss_ is essentially _Tetris_, where one or more squares of a block are replaced with a bomb. When you eliminate a line containing a bomb, it explodes.

For the _Bombliss_ portion, _Super Bombliss_, _Super Tetris 2 + Bombliss_, and _Super Tetris 2 + Bombliss - Genteiban_ are essentially the same game with the same mechanics. The starting state for the stages in each game are different (unlike typical _Tetris_, there are already blocks on screen that you have to deal with, and the arrangement changes between these variations).

I don't have the capacity to play through each of these games to find out if the stages are completely different between all three, a shuffling of order, or if one is a true superset of the other. Given this, I'm going to split them apart from now and they can stand alone.
