### ISSUE TITLE
Missing Parent/Clone relationships on Nintendo GameCube

### ISSUE THREAD

**Issue by DiGiCoDe77** [unexpectedpanda/retool#27]
## Dat
Nintendo - GameCube - Datfile

## Issue
**Disney Sports - Football (Europe) (En,Fr,De,Es,It)** is a clone of **Disney Sports - Soccer (USA)**
https://gamefaqs.gamespot.com/gamecube/561317-disney-sports-soccer

**Tak & Le Pouvoir de Juju (France)** is a clone of **Tak and the Power of Juju (Europe)** and not **Nickelodeon Tak - The Great Juju Challenge (Europe) (En,De)** as it is on your clone list.
https://www.gametdb.com/Wii/GJUF78

**Comment by unexpectedpanda** [comment]
_Disney Sports - Football (Europe)_ was auto-associated with _Disney Sports - Football (USA)_. An override has now been put in.

Looks like _Tak und die Macht des Juju_ was also misassigned. Both of these have been corrected.

You'll see them in the next clone list updates.
