### ISSUE TITLE
NES Missing Clone Relationships

### ISSUE THREAD

**Issue by possiblyneal** [unexpectedpanda/retool#270]
## Dat
Nintendo - Nintendo Entertainment System (Headered) (20230708-030456) (Retool 2023-07-08 13-24-38) (1,059) [-Bdp]

## Issue
Where possible, include URLs to a reputable source as proof, as it helps speed up verification.

* Missed or incorrect title (Europe) > Original title (USA) | https://www.wikipedia.org
* BMX Simulator (Asia) (En) (B-S2) (Unl) > BMX Simulator (World) (Unl)
* Booky Man (Brazil) (En) (Mega Soft) (Unl) & Booky Man (Spain) (En) (NTDEC) (Unl) > Brush Roller (Asia) (En) (Hwang Shinwei) (Unl) | Brush Roller seems to be the closest to the original - Should probably be classified as a pirate. https://en.wikipedia.org/wiki/Make_Trax
*  Chinese Checkers (Asia) (En) (60 pin cart) (Unl) > Chinese Checkers (Asia) (En) (72 pin cart) (Unl)
*  Cosmos Cop (Asia) (En) (Mega Soft) (Unl) > Cosmos Cop (Europe, Asia) (En) (Caltron) (Unl)
*  Destroyer (Asia) (En) (Mega Soft) (Unl) > Destructor, El (Spain) (En) (NTDEC) (Unl) | https://retro.gg/game/el-destructor/868
*  Final Combat (Asia) (En) (60 pin cart) (Unl) > Final Combat (Asia) (En) (72 pin cart) (Unl)

**Comment by possiblyneal** [comment]
Here are additional: 
* Time Diver - Avenger (Asia) (En) (T-A1) (Unl) > Time Diver - Eon Man (USA) (Proto) | https://en.wikipedia.org/wiki/Time_Diver:_Eon_Man
* Weilai Xiaozi - Joy Van Kid (Asia) (En) (Unl) > Metal Fighter (Asia) (En) (Sachen) (72 pin cart) (Unl) > Metal Fighter (USA) (Unl) | https://tcrf.net/Metal_Fighter_(NES)
* Crazy Land (USA) (Proto) > Trolls in Crazyland, The (Europe) | https://hiddenpalace.org/Crazy_Land_(Prototype)
* Virus (USA) (Proto) (1990-03-xx) (PC10) [b] > Dr. Mario (Japan, USA) (En) (Rev 1) | https://tcrf.net/Proto:Dr._Mario_(NES)/Virus_1989_%26_1990
* U-Force Power Games (USA) (Proto 2) (NintendoAge) [b] > U-Force Power Games (USA) (Proto 1)
* Sidewinder (Asia) (En) (72 pin cart) (Unl) > Mission Cobra (USA) (Unl) | https://en.wikipedia.org/wiki/Mission_Cobra
* Silent Assault (Asia) (En) (72 pin cart) (Unl) > Silent Assault (USA) (Unl)
* Master Chu and the Drunkard Hu (Asia) (En) (72 pin cart) (Unl) > Master Chu and the Drunkard Hu (USA) (Unl)

Compilations:
Funblaster Pak (Australia) (Unl) | https://bootleggames.fandom.com/wiki/Home_Entertainment_Suppliers & https://bootleggames.fandom.com/wiki/Twin_Eagle
- Little Red Hood (Australia) (Unl)
- Pipemania (Australia) (Unl)
- Metal Fighter (USA) (Unl)
- Double Strike - Aerial Attack Force (USA) (v1.1) (Unl)

Mindblower Pak (Australia) (Unl) | https://bootleggames.fandom.com/wiki/Home_Entertainment_Suppliers
- Magical Mathematics (Asia) (En) (NTSC) (Unl)
- Jackpot (Australia) (Unl)
- Arctic Adventure - Penguin & Seal (Australia) (Unl)
- Galactic Crusader (USA) (Unl)

Total Funpak (Australia) (Unl) | https://bootleggames.fandom.com/wiki/Home_Entertainment_Suppliers
- Pac-Man (USA) (Tengen)
- Sidewinder (Asia) (En) (72 pin cart) (Unl)
- Othello (Australia) (HES) (Unl)
- Duck Maze (Australia) (Unl)

Super Cartridge Ver 7 - 4 in 1 (Asia) (En) (Unl) | https://bootleggames.fandom.com/wiki/Super_Cartridge_(Sachen)
- Sidewinder (Asia) (En) (72 pin cart) (Unl)
- Happy Pairs (Asia) (En) (72 pin cart) (Unl)
- Silver Eagle (Asia) (En) (72 pin cart) (Unl)
- Tasac (Asia) (En) (Unl)

Super Cartridge Ver 9 - 3 in 1 (Asia) (En) (Unl) | https://bootleggames.fandom.com/wiki/Super_Cartridge_(Sachen)
- Challenge of the Dragon (Asia) (En) (Sachen) (Unl)
- Rockball (Asia) (En) (Unl)
- Popo Team (Asia) (En) (Unl)

**Comment by unexpectedpanda** [comment]
This is due to me not having time to update the clone lists for a while, and No-Intro flooding their sets with unlicensed and pirate titles. I really wish they would separate the bootlegs out into their own thing, they're a nightmare to manage.

Thanks for the leads, I'll look into these when I can.

**Comment by possiblyneal** [comment]
Its surprising how much 30 - 40 year old software is still being found. By default the no-intro dat-o-matic doesn't include pirate/bootlegs for the NES dats, I wouldn't put much effort into those. Unlicensed is selected by default, but there are many great unlicensed titles for the NES, it would be hard to consider a collection complete without them. And no expectations on timeline, I'm just happy you have put this software out here for all to enjoy. 

Also, out of curiosity do you forward this stuff to no-intro so they can amend their p/c list?

**Comment by unexpectedpanda** [comment]
This is finally done. Woo, what a mess they've turned this DAT into.

> Also, out of curiosity do you forward this stuff to no-intro so they can amend their p/c list?

Not usually. They're not quite a 1:1 mapping in the way they work, and it's more overhead when updating for me to report it.
