### ISSUE TITLE
TG16 Missing Clone

### ISSUE THREAD

**Issue by possiblyneal** [unexpectedpanda/retool#272]
## Dat
NEC - PC Engine - TurboGrafx-16 (20230708-115245) (Retool 2023-07-10 20-25-04) (104) [-Bdp]

## Issue
Where possible, include URLs to a reputable source as proof, as it helps speed up verification.

* Final Soldier - Special Version (Japan) (En) > Final Soldier (Japan) (En) | Note that the special version has less game content. The regular version includes everything the special version has plus more. https://shmups.system11.org/viewtopic.php?f=1&t=10341

**Comment by unexpectedpanda** [comment]
Thanks, fixed.
