### ISSUE TITLE
Sega CD Incorrect Exclusion Text File Output

### ISSUE THREAD

**Issue by possiblyneal** [unexpectedpanda/retool#274]
**Describe the bug**
Retool is incorrectly processing txt file output of exclusions checked in the exclusions tab.

Two examples are:

- Marko (USA) (Unl) - the no-intro listed category is "game" but retool excludes it as "audio"
- Battle Frenzy (USA) (Unl) - the no-intro listed category is "game" but retool excludes it as "application"

Both should have been in the unlicensed section of the txt output. There are likely more but I'm not super familiar with the system.

**To reproduce**
Use Retool to process a sega cd dat with my settings below.

**Expected behavior**
exclusions processed based on the category in the no-intro dat

**Operating system**
- [ x] Windows 10 (older versions not supported)
- [ ] Ubuntu
- [ ] Other (please specify)

**Retool edition**
- [ x] retool-gui.exe
- [ ] retool.py
- [ ] retool-gui.py

**Retool version**
2.00.5

For the GUI edition, click **Help**, then **About**.

**Are you using custom global or system filters? If so, list them below**

Global excludes:
All exclusions checked

Global includes:

System excludes:

System includes:

**What other settings are you using?**
Default other than outputing a list of titles that have been kept and removed

**Additional context**

**Comment by unexpectedpanda** [comment]
I think you mean the Redump DAT in this instance, not No-Intro. Let me know if otherwise, because that changes things.

I've run multiple tests across 2 different versions of the DAT in question, and can't replicate this. Those titles are always in the unlicensed removes section for me.

**Comment by possiblyneal** [comment]
Oops, yes Redump. 

I tested it again, redownloading the DAT from the Redump website and I get the same result. I've attached the log file with the error in it. 
[Sega - Mega CD & Sega CD (2023-06-28 06-38-42) (Retool 2023-07-16 23-58-42) [-AaBcdekMmpuv] log.txt](https://github.com/unexpectedpanda/retool/files/12065976/Sega.-.Mega.CD.Sega.CD.2023-06-28.06-38-42.Retool.2023-07-16.23-58-42.-AaBcdekMmpuv.log.txt)

Here is the link where I get my DAT: http://redump.org/datfile/mcd/

**Comment by unexpectedpanda** [comment]
Well, that's certainly messed up.

Despite excluding preproduction, according to your provided log those titles weren't removed, just assigned as clones where appropriate.

Unlicensed titles have turned up in audio and application removes, as you've noted, but also demos and multimedia.

Since I still can't replicate this, we're going to have to go a little general.

1. Update to Retool 2.01.1, see if that fixes your issue. Watch out on the exclusions tab -- **Games** is now an option there.
2. If not, supply me with two, possibly three files so I can dig a little deeper:
    - `config/user-config.yaml`
    - If it exists, `config/systems/Sega - Mega CD & Sega CD (Redump).yaml`
    - The output DAT file.

Failing this we might have to do a trace.

**Comment by possiblyneal** [comment]
It now outputs correctly for me! Thank you!

**Comment by unexpectedpanda** [comment]
Ah so the new version fixed it? Now I'm going to have to find out what changed for categories...

Good to hear things are working for you :)

**Comment by possiblyneal** [comment]
Yes, all that was changed was the version update. Thanks again.
