### ISSUE TITLE
Feature Suggestions: Prioritize roms from early versions of games over newer revisions

### ISSUE THREAD

**Issue by GDX-X** [unexpectedpanda/retool#278]
Hey,

I have feature suggestions

The ability to prioritize roms from early versions of games over newer revisions or vice versa

Original
Grand Theft Auto - Vice City (Europe) (En,Fr,De,Es,It) (v1.50) 

Revision
Grand Theft Auto - Vice City (Europe) (En,Fr,De,Es,It) (v2.03)

Or

Original 
Jak and Daxter - The Precursor Legacy (USA) (En,Fr,De,Es,It)

Revision
Jak and Daxter - The Precursor Legacy (USA) (En,Fr,De,Es,It) (Rev 1)

**Comment by unexpectedpanda** [comment]
This one has been requested before. Most people usually ask because they're concerned about what they see as censorship in later versions of some titles.

So I can get a full understanding, do you have a different reason?

**Comment by GDX-X** [comment]
Yes for censorship in some games too and other little things like glitch fixed in recent version

**Comment by unexpectedpanda** [comment]
Added in v2.3.6.
