### ISSUE TITLE
Mega CD: Marko's Magic Football - Wrong prioritization

### ISSUE THREAD

**Issue by Keiyuu** [unexpectedpanda/retool#279]
**Describe the bug**
DAT: Sega - Mega CD & Sega CD - Datfile (542) (2023-07-22 03-27-17)

* Marko's Magic Football (Europe) (En,Fr,De,Es) | http://redump.org/disc/51733/
* Marko (USA) (Unl) | http://redump.org/disc/73145/

Retool prioritizes the Europe version despite me having USA as the first region in the list.
If I understood Retool's behavior correctly, it should prioritize the USA version if it's the top region and "Prefer licensed versions over unlicensed, aftermarket, or homebrew titles" is **not** checked.

**Operating system**
- [x] Windows 10 (older versions not supported)
- [ ] Ubuntu
- [ ] Other (please specify)

**Retool edition**
- [x] retool-gui.exe
- [ ] retool.py
- [ ] retool-gui.py

**Retool version**
v2.01.3

**Are you using custom global or system filters? If so, list them below**
Global exclusions: Audio, Demos, Preproduction, Video

**What other settings are you using?**
Regions: USA, World, Canada, etc. (Europe is on the 13th spot)
Languages: English, Japanese

**Comment by unexpectedpanda** [comment]
`Marko's Magic Football (Europe) (En,Fr,De,Es)` is set as a superset of `Marko (USA) (Unl)` in the clone list, which takes priority over any Retool options.

Truthfully I have no idea why. I'll move it back to the regular title status and things will work as expected.
