### ISSUE TITLE
Crash when filtering No-Intros Nintendo - Family Computer Disk System dat

### ISSUE THREAD

**Issue by prklx2** [unexpectedpanda/retool#28]
**Describe the bug**
**To reproduce**
When trying to filter the latest No-Intro datfile for Nintendo FDS the software crashes.
Exact dat version: Nintendo - Family Computer Disk System (#371 ~ 2021-01-11 13:28:54 ~ P/C: #371) 

**Expected behavior**
Not crashing.

**Operating system**
- [X] Windows 10 (older versions not supported)
- [ ] Ubuntu
- [ ] Other (please specify)

**Retool edition**
- [X] retool-gui.exe
- [ ] retool.py
- [ ] retool-gui.py

**Retool version**
Retool GUI: 0.05
Retool CLI: 0.86

**Are you using custom global or system filters? If so, list them below**

Global excludes:
  Applications
  Audio
  BIOS
  Compilations
  Coverdiscs
  Demos and samples
  Educational
  Multimedia
  Video
  
Every "Mode" unticked in "Modes".

**What other settings are you using?**
All regions enabled, only moved Finland, Scandinavia, Europe and UK to top before US.

**Comment by unexpectedpanda** [comment]
I this is what I think it is, your issue should be fixed by updating to 0.87. From the change log:

* Can now handle the new (DV #, #) versioning in No-Intro's FDS dat without crashing.

Let me know how you go. If it doesn't resolve the issue, we can dig a little deeper.

**Comment by prklx2** [comment]
Yup. My bad - didn't even notice there was a new version available.
This fixed the issue.
