### ISSUE TITLE
Issues filtering Nintendo - Nintendo 3DS (Encrypted)

### ISSUE THREAD

**Issue by muggsyd** [unexpectedpanda/retool#280]
**Describe the bug**
When using the following switches on the Nintendo - Nintendo 3DS (Encrypted) DAT, I go from over 2000 entries, to just 25. This used to work. It's been broken for a few releases and I am unsure the last version it worked on. This does not appear to affect the other No-Intro DATs I am running retool against.

**To reproduce**
run retool.py with following switches -l --exclude aAbBcdDemMopPrv

**Expected behavior**
I would expect filtering based on above switches

**Operating system**
- [ ] Windows 10 (older versions not supported)
- [ ] Ubuntu
- [*] Debian via docker

**Retool edition**
- [ ] retool-gui.exe
- [* ] retool.py
- [ ] retool-gui.py

**Retool version**
2.0.1.4

**Are you using custom global or system filters? If so, list them below**

Global excludes:

Global includes:

System excludes:

System includes:

**What other settings are you using?**

user-config.yaml includes. All other region/language are commented out
# ==============
# LANGUAGE ORDER
# ==============
- English

# ============
# REGION ORDER
# ============

- USA
- World
- Canada
- UK
- Australia
- New Zealand
#- Singapore
#- Ireland
- Europe
- Japan
- Asia

**Comment by unexpectedpanda** [comment]
With `Nintendo - Nintendo 3DS (Encrypted) (20230406-211023).dat`, I get 554 titles with your settings, in both Retool GUI and CLI on Windows. The same is true whether I use global or system settings for the filtering.

A quick spin on Ubuntu via WSL using CLI and global settings gives the same result.

> user-config.yaml includes.

What includes?

I think the easiest way to diagnose this is to provide the following files:

* `config/user-config.yaml`
* `config/systems/Nintendo - Nintendo 3DS (No-Intro).yaml`, if it exists
* The TXT file generated when you run Retool with the `--log` command.

**Comment by muggsyd** [comment]
Here are the files. When I remove the "-l" is seems to filter better. I didn't know where the logs files were kept (I'm running in docker) so I have copied the output into txt files. I have also include the json and yaml file you requested

[retool.zip](https://github.com/unexpectedpanda/retool/files/12182670/retool.zip)

**Comment by unexpectedpanda** [comment]
I wrote up a whole piece of the diagnostic I did and thinking I'd hit a dead end, but I see you've provided the answer, possibly by accident.

In your file bundle is your 3DS metadata file, which I didn't ask for, but is funnily enough the problem.

It's old and in the wrong format. You need to update your clone lists, which also grabs new metadata (`--update` from the command line).

Here's what that file should look like:

https://github.com/unexpectedpanda/retool-clonelists-metadata/blob/main/metadata/Nintendo%20-%20Nintendo%203DS%20(No-Intro).json

**Comment by muggsyd** [comment]
That's strange. The 1st thing my script does it run a retool.py --update
All those meta files were updated the last time I ran the script. I renamed
the old meta file and re-ran and it appeared to work the 1st time. When I
tried it again it once again failed. However the new and the old metafile
appear to be identical
[image: image.png]
I also wiped out all my clonelist and metadata, so it all redownloaded

retool  |
retool  | * Done. Downloaded 346 files.
retool  |
retool  |
retool  | Retool 2.01.4
retool  | -------------
retool  | Processing folder...
retool  | * Reading DAT file: "/retool/dats/No-Intro/Nintendo - Nintendo
3DS (Encrypted)
retool  |   (20230724-091936).dat"
retool  | * Validating DAT file... done.
retool  |
retool  | |  DAT DETAILS
retool  | |  Description: Nintendo - Nintendo 3DS (Encrypted)
retool  | |  Author/s: aci68, ajax16384, ajshell1, Arctic Circle System,
Aringon, b2071988, Bent,
retool  |    buckwheat, C. V. Reynolds, Connie, coraz, Datman,
DeadSkullzJr, Densetsu, einstein95, Fonix,
retool  |    Gefflon, Hiccup, InternalLoss, Jack, jimmsu, Just001Kim,
Larsenv, MeguCocoa, MisterSheeple,
retool  |    Money_114, NESBrew12, NovaAurora, PPLToast, psykopat, relax,
Rifu, scorp256, SonGoku,
retool  |    Tauwasser, TBemme, togemet2, u53r123, Xenirina, xprism, xuom2,
ZeroSkill, zg, Zora
retool  | |  URL: https://www.no-intro.org
retool  | |  Version: 20230724-091936
retool  | |  Numbered dat: No
retool  |
* Processing DAT file... done.
retool  | * Analyzing clone list variants... done.
retool  | * Applying category and user excludes... done.
retool  | * Removing titles without specified languages... done.
retool  | * Removing titles without specified regions... done.
* Selecting 1G1R titles... done.
retool  | * Creating DAT... done.
retool  |
retool  | Stats:
retool  | o  Original title count: 2,092
retool  | -  Clones removed: 4
retool  | -  Add-on titles removed: 0
retool  | -  Applications removed: 4
retool  | -  Audio titles removed: 0
retool  | -  Bad dumps removed: 0
retool  | -  BIOSes and other chips removed: 2
retool  | -  Bonus discs removed: 0
retool  | -  Coverdiscs removed: 0
retool  | -  Demos removed: 68
retool  | -  Educational titles removed: 0
retool  | -  Manuals removed: 0
retool  | -  Multimedia titles removed: 0
retool  | -  Pirate titles removed: 0
retool  | -  Preproduction titles removed: 9
retool  | -  Promotional titles removed: 0
retool  | -  Video titles removed: 0
retool  | -  Titles removed by language filters: 1,980
retool  |
retool  | -  Total titles removed: 2,067
retool  | -------------------------------
retool  | =  Final title count: 25
retool  |
retool  | * Finished adding 25 titles to
"/retool/dats/1G1R/No-Intro/Nintendo - Nintendo 3DS
retool  |   (Encrypted) (20230724-091936) (Retool 2023-07-28 01-32-30) (25)
(-l) [-aAbBcDdemMopPrv].dat"
retool  |   in 2.54s.

I'm rebuilding my environment. It's possible an issue with my data as you
pointed out

**Comment by muggsyd** [comment]
It actually looks like wiping my **internal-config.json** and my **user-config.yaml** and having them re-downloaded fixed it for me. This also replicated your results

retool  | Stats:
retool  | o  Original title count: 2,092
retool  | -  Clones removed: 559
retool  | -  Add-on titles removed: 0
retool  | -  Applications removed: 4
retool  | -  Audio titles removed: 0
retool  | -  Bad dumps removed: 0
retool  | -  BIOSes and other chips removed: 2
retool  | -  Bonus discs removed: 0
retool  | -  Coverdiscs removed: 0
retool  | -  Demos removed: 68
retool  | -  Educational titles removed: 0
retool  | -  Manuals removed: 0
retool  | -  Multimedia titles removed: 0
retool  | -  Pirate titles removed: 0
retool  | -  Preproduction titles removed: 9
retool  | -  Promotional titles removed: 0
retool  | -  Video titles removed: 0
retool  | -  Titles removed by language filters: 895
retool  |
retool  | -  Total titles removed: 1,537
retool  | -------------------------------
retool  | =  Final title count: 555

The only other change once they had been downloaded was uncommenting  **English** is **user-config.yaml**

**Comment by unexpectedpanda** [comment]
No worries :) Yep that definitely looks like `internal-config.json` was pointing to the wrong place.

I think I might be able to work around that for future users... that's at least two people that grabbed the first beta who have had the issue.

Out of interest, how are you dealing with storage in your container? I'm assuming the output file ends up in a folder shared with the host system?

**Comment by muggsyd** [comment]
Yes, I am seeing actual clone list updates (I assumed they were pretty
static) etc now that those config files were cleaned up

Here is my docker-compose.yml file for my volumes which are all local
storage on my docker (except the last volume)
      - /docker/retool/config:/retool/config
      - /docker/retool/files/datafile.dtd:/retool/datafile.dtd
      - /docker/retool/data/clonelists:/retool/clonelists
      - /docker/retool/data/metadata:/retool/metadata
      - /docker/retool/scripts:/scripts
      - DatRoot:/retool/dats/ *(this goes off to my NAS)*

I see the log file is placed in the DAT output location. Anyway to have a
switch to output it to a log folder? like /retool/logs/

**Comment by unexpectedpanda** [comment]
Cheers! Eventually I'll get something semi-working on the Docker front.

You can't currently route log output elsewhere, but I'll add it as a feature request.
