### ISSUE TITLE
Category Filter Enhancement Request

### ISSUE THREAD

**Issue by waden34** [unexpectedpanda/retool#282]
Would it be possible to have categories be stored in metadata files like the languages are?
A lot of titles for computer systems don't have a category tag in the name, so they are not removed.

This tool has made it possible to finally get my emulation box up and running, so I greatly appreciate you!

**Comment by unexpectedpanda** [comment]
Very possible -- so possible in fact that you can already [assign categories to titles in clone lists](https://unexpectedpanda.github.io/retool/contribute-clone-lists-categories/) :)

I rely on community contributions for these though -- it's too big a job for just me. If you find something that you think should be categorized differently, definitely raise it and I'll take a look.

**Comment by waden34** [comment]
Oh very cool, I didn't see that as part of the clone lists. I'll dive into the clonelist repo and create a pull request for the systems I'm working on.

Thank you!
