### ISSUE TITLE
No titles in the input DAT match your preferences. No DAT file has been created.

### ISSUE THREAD

**Issue by bropesda** [unexpectedpanda/retool#284]
**Describe the bug**
I get this message when trying to process a DAT. I have tried many different types (Redump, No-Intro..)

**No titles in the input DAT match your preferences. No DAT file has been created.**

**To reproduce**
Try to process a DAT file

**Expected behavior**
It should create the 1G1R DAT file correctly

**Operating system**
- Windows 10 22H2

**Retool edition**
- retool-gui.exe

**Retool version**
2.01.5

For the GUI edition, click **Help**, then **About**.

**Are you using custom global or system filters? If so, list them below**

No

**What other settings are you using?**
Regions: USA > Europe > UK > World (Have tried various region ordering)
Languages: English (Have also tried without a language)
Exclusions: Selected All

**Additional context**

Retool 2.01.5
-------------
* Reading DAT file: "W:\ROMVault_V3.6.1\DatRoot\REDUMP\Philips - CD-i - Datfile (1964)
  (2023-07-21 16-35-44)\Philips - CD-i - Datfile (1964) (2023-07-21 16-35-44).dat"
* Validating DAT file... file is a Logiqx DAT file.

|  DAT DETAILS
|  Description: Philips - CD-i - Discs (1964) (2023-07-21 16-35-44)
|  Author/s: redump.org
|  URL: http://redump.org/
|  Version: 2023-07-21 16-35-44

* Processing DAT file... done.
* Applying clone list MIA tags... done.
* Analyzing clone list variants... done.
* Applying category and user excludes... done.
* Removing titles without specified languages... done.
* Removing titles without specified regions... done.
* Selecting 1G1R titles... done.

* No titles in the input DAT match your preferences. No DAT file has been created.

**Comment by bropesda** [comment]
I did! I usually select all exclusions but didn't realise there was a new Game option. This can be closed.

**Comment by unexpectedpanda** [comment]
I figured it might trip a few people up who'd built some habits :) It was added as people were using the exclude tab as a way to split DATs by category.

Glad we got it fixed!
