### ISSUE TITLE
Test Cartridges not excluded from SNES dat when only 'Games' is selected

### ISSUE THREAD

**Issue by Goratrix** [unexpectedpanda/retool#285]
When processing Nintendo - Super Nintendo Entertainment System (20230814-130018) dat file with Retool 2.01.5, excluding everything except 'Games' and no other settings changed from default, the following non-game roms remain in the dat:

Burn-in - Test Cartridge (USA) (Rev D)
NTF 2.5 Test Cartridge (USA) (Rev A)

**Comment by unexpectedpanda** [comment]
Thanks for this. Both are recent updates.

* _NTF 2.5 Test Cartridge (USA) (Rev A)_ is a rename of _World Class Service Super Nintendo Tester (USA)_
* _Burn-in - Test Cartridge (USA) (Rev D)_ is a rename of _SNES Burn-in Test Cartridge (USA) (Rev D)_.

If you update your clone lists, you'll get the changes.
