### ISSUE TITLE
+ You Don't Know Jack (Germany)  - You Don't Know Jack (USA) (Disc 1)  but it keeps USA Disc 2

### ISSUE THREAD

**Issue by MaXGitteR** [unexpectedpanda/retool#294]
## Dat
Sony - PlayStation - Datfile (10753) (2023-12-20 17-29-54).dat
DAT-o-MATIC

## Issue
ReTool removes "(USA) (Disc 1)" but keeps "(USA) (Disc 2)"
I think it should also remove "(USA) (Disc 2)" or it should also keep "(USA) (Disc 1)", but only removing 1 and keeping 2 is wrong.
I think it thinks Germany Version is USA Disc 1 and USA Disk 2 is a standalone game? 

* Missed or incorrect title (Europe) > Original title (USA) | https://www.wikipedia.org
"+ You Don't Know Jack (Germany)" 
"- You Don't Know Jack (USA) (Disc 1)"
"+You Don't Know Jack (USA) (Disc 2)"

**Comment by MaXGitteR** [comment]
Dat and Log Files

[Sony - PlayStation - Datfile (10753) (2023-12-20 17-29-54).dat.txt](https://github.com/unexpectedpanda/retool/files/13767174/Sony.-.PlayStation.-.Datfile.10753.2023-12-20.17-29-54.dat.txt)
[Sony - PlayStation (2023-12-20 17-29-54) (Retool 2023-12-25 20-56-17) (1,752) [-AabBcdDekmMoPpruv] names.txt](https://github.com/unexpectedpanda/retool/files/13767175/Sony.-.PlayStation.2023-12-20.17-29-54.Retool.2023-12-25.20-56-17.1.752.-AabBcdDekmMoPpruv.names.txt)
[Sony - PlayStation (2023-12-20 17-29-54) (Retool 2023-12-25 20-56-17) (Removed titles) (9,001) [-AabBcdDekmMoPpruv] names.txt](https://github.com/unexpectedpanda/retool/files/13767176/Sony.-.PlayStation.2023-12-20.17-29-54.Retool.2023-12-25.20-56-17.Removed.titles.9.001.-AabBcdDekmMoPpruv.names.txt)
[Sony - PlayStation (2023-12-20 17-29-54) (Retool 2023-12-25 20-56-17) [-AabBcdDekmMoPpruv] log.txt](https://github.com/unexpectedpanda/retool/files/13767177/Sony.-.PlayStation.2023-12-20.17-29-54.Retool.2023-12-25.20-56-17.-AabBcdDekmMoPpruv.log.txt)

**Comment by unexpectedpanda** [comment]
As long as the USA version of the game is definitely split over two discs , and the second disc isn't some kind of standalone bonus, then this is fixed easily enough in the clone lists. Are you able to confirm?

As an aside, keeping disc sets together isn't a supported feature yet. One day, but it requires a lot of work.

**Comment by MaXGitteR** [comment]
The US version seems to have different question categories per disc. On the German version everything seems to be on one disc.

**Comment by unexpectedpanda** [comment]
Okay, great, I'll make the change in the next clone list update.

**Comment by unexpectedpanda** [comment]
Fixed. Make sure to update to v2.02.0 before you update your clone lists, as they have a new format now.
