### ISSUE TITLE
[Bug] Clone being left in 1G1R output for No Intro "Atari - Lynx" DAT

### ISSUE THREAD

**Issue by Daeymon** [unexpectedpanda/retool#296]
Using the DAT file "Atari - Lynx (LYX) (20231231-205835)"

Both of these are making it into the 1G1R output despite one being a clone of the other within the DAT:
"Find a Way to My Heart (World) (Aftermarket) (Unl)"
"Find a Way to My Heart (World) (Atari Lynx 30th Birthday) (Aftermarket) (Unl)"

Edit:
On second look, its doing this with all the "(Atari Lynx 30th Birthday)" clones.

**Comment by unexpectedpanda** [comment]
Thanks for the heads up!

Parent/clone relationships in DAT files are ignored in favor of Retool's own processing (far too many issues with parent/clone to rely on it). 

Generally I update Retool's clone lists about once a month, which means occasionally fresh titles in DAT files slip the net. The 30th birthday entries were only recently added at the end of December.

So not a bug, just the nature of how things work. Given No-Intro and Redump are very unlikely to ever support proper 1G1R, it's the best we've got. That and reports like this that let me sneak in a specific change before my usual regular updates :)

I'll make an update later today so Retool recognizes the 30th birthday titles.

**Comment by unexpectedpanda** [comment]
Resolved. Looks like No-Intro came in with a 1-2 whammy and also renamed the Lynx DATs to include a format, which bypassed the clone list. You'll need Retool v2.01.9 and updated clone lists for full clone detection to resume.
