### ISSUE TITLE
Post Filters

### ISSUE THREAD

**Issue by Jaylinx** [unexpectedpanda/retool#298]
Hello, I'm using the daily pack of No-Intro DATS with Aftermarket roms ticked in options

I want to make 1G1R only with Aftermarket roms in order to have one DAT with "normal" roms and one DAT with aftermarket roms for each systems.

So in Post Filters, I just write Aftermarket and scan my DATS. It works for a lot of systems like NES, GB, GBC, GBA, Lynx, GG, N64 and Jaguar. But for systems like Genesis, Master System, Super Nintendo and Virtual Boy it doesn't work, it gives me this error whatever the word I put in Post Filters

Traceback (most recent call last):
  File "retoolgui.py", line 225, in run
  File "retool.py", line 228, in main
  File "modules\titletools.py", line 662, in post_filters
TypeError: 'in <string>' requires string as left operand, not dict

**Comment by unexpectedpanda** [comment]
I can't replicate this. It's possible that another setting is required to trigger it, or that those DATs in the daily pack were invalid in some way at the time you downloaded it.

Did you have other settings enabled as well? Could you provide one of the problem DAT files for me to test?

**Comment by unexpectedpanda** [comment]
Also, it might be useful to see your `config/user-config.yaml` file, just so I can get a sense as to your setup.

**Comment by Jaylinx** [comment]
I made a clean install and it worked as planned. Sorry for the inconvenience

**Comment by unexpectedpanda** [comment]
No troubles. Let me know if you run into an issue again :)
