### ISSUE TITLE
Some command line exclusions are ignored

### ISSUE THREAD

**Issue by AlvaroBurnett** [unexpectedpanda/retool#301]
Using the following command line:

`python.exe retool.py my_dat_dir --output my_1g1r_dat_dir --config my_user_config.yaml -l --exclude a A b B c d D e k m M p P r u v
`

Does not filter out bios, betas, demos, promos, samples, unl (seems that 'B', 'P', and 'u' are ignored).

**Comment by unexpectedpanda** [comment]
I think this is a syntax thing. Try the exclusions without the spaces between them:

```
python.exe retool.py my_dat_dir --output my_1g1r_dat_dir --config my_user_config.yaml -l --exclude aAbBcdDekmMpPruv
```

**Comment by unexpectedpanda** [comment]
Excellent :)
