### ISSUE TITLE
PIP Package

### ISSUE THREAD

**Issue by maxexcloo** [unexpectedpanda/retool#303]
**Describe the bug**
Wondering if there's any chance of publishing a package on pip so that I can simply `pip install retool` to download the tool :)

**Expected behavior**
Would download the latest version and add it to the PATH, also adding dependencies.

**Comment by unexpectedpanda** [comment]
This requires dramatic restructuring, plus to generate multi-platform binaries (so you can just run `retool` from the terminal) requires me to own an Apple silicon Mac.

It's not feasible in the short term, sorry.

**Comment by maxexcloo** [comment]
Happy to take a look at this as it seems this can be done using GitHub Actions - https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

**Comment by unexpectedpanda** [comment]
I'm currently working on integrating [Hatch](https://github.com/pypa/hatch) as a linting, testing, and building framework on my local, with the idea of eventually getting it into GitHub Actions for easier contribution. Ultimately I imagine that would be part of a package workflow as well.

From a package perspective I'm not sure how much restructuring of Retool itself has to be done. Ultimately I'd want to manage the tokens/project for PyPI, so there'd have to be collaboration there.

If you want to get a start on building some Actions, happy to look at PRs, with the caveat that it might take me a little time to understand what's happening in said PRs.

As an aside, I notice you've also built a Docker container for Retool -- my work on #255 stalled as it required learning a new ecosystem, and I was struggling a bit with making [muggsyd](https://github.com/muggsyd/docker-retool)'s user permissions work (for some reason the commands didn't exist) and not being able to test against the originally requested ARM64 hardware for peace of mind.

Looking at the fuss people have to go through to install Retool in a Docker container, perhaps package + Docker install are complementary tasks?

**Comment by maxexcloo** [comment]
I’d say a Docker image with VNC and just a plain Docker image cli CLI could be different things - personally I used the GUI to configure but past that I didn’t use it. My image is pretty clean so I’m happy to open a PR and tweak it a bit more :)

**Comment by maxexcloo** [comment]
To add another guide I found that might help: https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
