### ISSUE TITLE
Feature Request: Create a list of games that are labeled Beta/Prototype but are actually finished and just unreleased.

### ISSUE THREAD

**Issue by TomTurbine** [unexpectedpanda/retool#313]
Thinking in terms of like Thrill Kill for the PSX or Mickey's Playtown Adventures for the Super Nintendo.

The Datting groups have them labeled as "Beta" but they are complete and playable from beginning to end, they just don't have a tag for "Unreleased" to deal with those games.

Have an option to exclude the preproduction games while keeping the unreleased ones.

Would be cool to have that feature. That being said, I don't believe this will likely be included due to the homework it would take trying to figure out which is which but figure its worth the suggestion.

**Comment by unexpectedpanda** [comment]
I get the sentiment, but yeah, it's a lot of work to add to an already research-heavy project.

Maybe one day.

**Comment by unexpectedpanda** [comment]
I'm going to close this one up as too much work. Others are welcome to tackle it.
