### ISSUE TITLE
Game Boy Advanced 2 missed games to filter out.

### ISSUE THREAD

**Issue by TomTurbine** [unexpectedpanda/retool#314]
## Dat
No-Intro Game Boy Advance

## Issue
Yu-Gi-Oh! Double Pack (USA)    is a compilation of
Yu-Gi-Oh! - Reshef of Destruction (USA)  &  Yu-Gi-Oh! - The Sacred Cards (USA)

Yu-Gi-Oh! Double Pack 2 (USA) (En,Fr,De,Es,It) is a compilation of
Yu-Gi-Oh! - Destiny Board Traveler (USA)  &  Yu-Gi-Oh! - Dungeon Dice Monsters (USA) (En,Es)

But are not filtered out.

**Comment by TomTurbine** [comment]
Also for Game Boy Advance, it keeps
Strawberry Shortcake - Summertime Adventure (USA)  &  Strawberry Shortcake - Summertime Adventure - Special Edition (USA)

Even though the only difference between them as far as I know is the special edition includes a TV episode.

**Comment by TomTurbine** [comment]
For 3DS, it wants to filter out "Fire Emblem Fates - Special Edition (USA)" which is the one fates you WANT to keep.
It is a compilation of
Fire Emblem Fates - Birthright
Fire Emblem Fates - Conquest
Fire Emblem Fates - Revelation

And Fire Emblem Fates - Revelation is a eShop exclusive with no actual cartridge release outside of this compilation cartridge.

**Comment by TomTurbine** [comment]
And with Wii CDN content, it prioritizes the base version of a game and wants to remove the updated versions of them.

**Comment by unexpectedpanda** [comment]
> For 3DS, it wants to filter out "Fire Emblem Fates - Special Edition (USA)" which is the one fates you WANT to keep.

The default is to prefer single releases over compilations, unless the compilations are verified to contain newer versions of the games.

Eventually there'll be a feature that lets people choose how to handle compilations.

> Wii CDN content

I've barely spent any time on CDN DAT files, as they're huge and don't always have useful naming structures.

The rest I'll look into when time presents.

**Comment by TomTurbine** [comment]
> > For 3DS, it wants to filter out "Fire Emblem Fates - Special Edition (USA)" which is the one fates you WANT to keep.
> 
> The default is to prefer single releases over compilations, unless the compilations are verified to contain newer versions of the games.
> 
> Eventually there'll be a feature that lets people choose how to handle compilations.
> 
> > Wii CDN content
> 
> I've barely spent any time on CDN DAT files, as they're huge and don't always have useful naming structures.
> 
> The rest I'll look into when time presents.

For the Fire Emblem Fates - Special Edition, it isn't that it has a newer version, its that it has a game that is ONLY released on that cartridge out of the entire dat file.

Where you either get it from that cartridge or you have to have the eShop set to get access to it.

**Comment by unexpectedpanda** [comment]
> For the Fire Emblem Fates - Special Edition, it isn't that it has a newer version, its that it has a game that is ONLY released on that cartridge out of the entire dat file.

Ah, thanks for the clarification. This has been fixed. Due to the way compilations work, you'll get the individual titles for Birthright and Conquest, whereas Revelation is represented by the compilation.

The other 3DS and GBA misses have also been corrected, thanks. Update your clone lists for the changes to take effect.

> And with Wii CDN content, it prioritizes the base version of a game and wants to remove the updated versions of them.

Can you provide some example title names so I know where to look?

**Comment by TomTurbine** [comment]
I know this completely off topic, but I had an idea for another dat related program that I think many would like and you have definitely shown the ability to create. It would effectively be your own portable version of No-Intros Dat-O-Matic.

Have it load a dat into memory and read every single tag in the names and display them as a spreadsheet along with the number of entries that match it and with 4 options.

1) Include
2) Neutral (Chosen by default)
3) Exclude
4) Delete

If anything is deleted, they are removed from the list and the whole thing is re-scanned and the spreadsheet reloaded with the new entries.

Then when they hit process, it first includes everything that has the tags that you included then a second pass which then prunes anything you have selected exclude on before writing it to a new dat file.

I think many would enjoy that for making their own custom ReDump Dats or even the No-Intro ones if they just use the daily dumps from them as the starting point.

**Comment by unexpectedpanda** [comment]
> For the Wii CDN sets.
>
> Cave Story (USA) (v258) (WiiWare)
> Cave Story (USA) (WiiWare)
>
> Even though the v258 version is an update, it would remove that and keep the original that wasn't updated. For the Wii CDN wads, the one with the numbers at the end should be the one you want to keep.

Ah right, this is the (WAD) set not the (CDN) set.

I don't see what you're seeing, Retool selects v258 for me. You might have set different options that are getting in the way?

**Comment by TomTurbine** [comment]
> Ah right, this is the (WAD) set, not the (CDN) set.
> 
> I don't see what you're seeing, Retool selects v258 for me. You might have set different options that are getting in the way?

All I had done was set the defaults for the regions and the languages and told it to exclude preproduction stuff.

It had excluded the v258 wad but kept the other one.

**Comment by unexpectedpanda** [comment]
I've downloaded the latest files from Dat-O-Matic.

I can't replicate this on Retool v2.02.2 using `Unofficial - Nintendo - Wii (Digital) (Deprecated) (WAD) (20231216-065527).dat`. `Cave Story (USA) (v258) (WiiWare)` is correctly chosen as the 1G1R title.

There's another DAT file, `Nintendo - Wii (Digital) (CDN) (20231116-082057).dat`, however only `Cave Story (USA) (WiiWare)` is present in the original DAT file, v258 isn't. Naturally Retool selects the base title, as v258 doesn't exist.

We've only got few options left here. You could try uploading your `config/user-config.yaml` and the input DAT file you used, and I can use them and see if something strange tips up.

Failing that, wiping out the Retool folder and starting again is the only hail Mary I have 🤷

**Comment by TomTurbine** [comment]
It's fine. If it works for you, that's fine by me, as I said, I decided to just keep the sets and pull what I want.
Just use the Dat-O-Matic for their filters and for ReDump I use ClrMamePro and use these 2 filters.

Include this
%d=*(USA)*;*,USA)*;*(USA,*;*(World)*;*,USA,*

Excluse this
%d=*(Beta*;*(Proto*;*(Demo*;*(Trade Demo)*;*Sampler Disc*;*Preview Disc*;*Demo Disc*;*Kiosk*;*Demo CD*;*Sampler Disk*;*Sampler Pack*

But decided to exclude the 1g1r setup for now.
