### ISSUE TITLE
System Exclude Override not working as intended

### ISSUE THREAD

**Issue by Daeymon** [unexpectedpanda/retool#317]
On the "Nintendo - Nintendo 3DS (Decrypted)" dat I'm having an issue where a game which should be excluded is being included in the final output dat with a comment on it with a remove reason (even though it hasn't been removed). My guess is the "+" symbol is causing problems; characters like that always do. Also all the non-plus versions of the game were correctly stripped out.

![image](https://github.com/unexpectedpanda/retool/assets/29780145/629a98ad-c6e1-4b9a-90b0-c27a6ec01f11)
![image](https://github.com/unexpectedpanda/retool/assets/29780145/3bc66d25-1198-4802-b3f1-3705b658a08d)

**Comment by Daeymon** [comment]
Also happening with this rom. Again, has non-alpha numeric characters in the name. So hopefully another example will help.

![image](https://github.com/unexpectedpanda/retool/assets/29780145/50b00a28-6c2c-47af-96eb-e3dbcd46b9cf)
![image](https://github.com/unexpectedpanda/retool/assets/29780145/2b94d291-8331-4ec0-ad7f-1d0fa14288be)

**Comment by unexpectedpanda** [comment]
This is a case of over-optimization on my behalf. Retool is looking for the titles in their default group, however the related clone list has already moved them to a different group for comparison.

The fix is cued up for the next release.

**Comment by unexpectedpanda** [comment]
Fixed in v2.03.0.
