### ISSUE TITLE
Binaries Slowing Down Git Clone

### ISSUE THREAD

**Issue by MateusAmin** [unexpectedpanda/retool#32]
Mind removing the binaries under /dist (and placing it under .gitignore) or enabling LFS? Make for a rather long git clone.

https://docs.github.com/en/github/authenticating-to-github/removing-sensitive-data-from-a-repository

Thanks for reading! This project is really helpful and appreciated.

EDIT: Misunderstood project goals.

**Comment by unexpectedpanda** [comment]
Thanks for the feedback :)

I hadn't considered the impact of binaries on cloning, especially with history. I'll look into the alternatives and blast out the history of `/dist` when things look solid.

There was originally a question here about whether Retool uses checksum or name matching, so I'll address that. Yep, the 1G1R matching is entirely name-based. This works well for auto-matching, but it means clone lists are fragile -- they survive redumps (checksum changes), but not name changes. Checksum matching in clone lists as a secondary method could help clone lists to live longer if they aren't updated in step with dat releases. I like the idea, it just involves a lot of work (and there are probably issues I haven't thought of yet), so it's not on my radar for now.

It looks like you might have been looking for functionality other than what Retool offers though -- if that's the case, [Sabretools](https://github.com/SabreTools/SabreTools) might fit your bill.

**Comment by unexpectedpanda** [comment]
The dist folder is now gone from history, with binaries now hosted in another repo. Thanks again for the heads up!
