### ISSUE TITLE
Merge Split Systems (No-Intro)

### ISSUE THREAD

**Issue by maxexcloo** [unexpectedpanda/retool#322]
With some systems in No-Intro the full set of ROMs is split, for example Apple II:

```
Apple - II (A2R)
Apple - II (WOZ)
Apple - II (Waveform)
```

It would be nice to be able to merge these split systems into one DAT.

**Comment by unexpectedpanda** [comment]
I have no plans to support merging in Retool. Check out [Sabretools](https://github.com/SabreTools/SabreTools) to scratch that particular itch.
