### ISSUE TITLE
Sega - Mega Drive - Genesis - Sonic The Hedgehog (Japan, Europe, Korea) (En) is chosen over (USA, Europe)

### ISSUE THREAD

**Issue by veritas5** [unexpectedpanda/retool#327]
**DAT**
Sega - Mega Drive - Genesis (20240421-003558).dat

**Issue**
Sonic The Hedgehog (Japan, Europe, Korea) (En).zip 
Sonic The Hedgehog (USA, Europe) (Sonic Classic Collection).zip 
Sonic The Hedgehog (USA, Europe).zip 
Sonic The Hedgehog (Unknown) (Beta).zip 
Sonic The Hedgehog (World) (Sonic Mega Collection).zip

(Japan, Europe, Korea) (En) is chosen over (USA, Europe) even though USA is at the top of my region order when I filter by English only in the languages setting.

![Screenshot 2024-04-21 181207](https://github.com/unexpectedpanda/retool/assets/167718790/da6709bf-0ec6-4aaf-8c1b-c7be037bd731)
![Screenshot 2024-04-21 181216](https://github.com/unexpectedpanda/retool/assets/167718790/e60d442c-f503-4839-8072-0b40ca2ce039)

**Comment by unexpectedpanda** [comment]
This is working as intended. Sonic Japan is in English and is a newer revision that has additional parallax scrolling in the background, so is treated as a [superset](https://unexpectedpanda.github.io/retool/terminology/#supersets).

**Comment by unexpectedpanda** [comment]
No need to be sorry, there are lots of questions about this one. It's on me to make it clearer.
