### ISSUE TITLE
select.pyd file flaged as a trojan and removed by Windows Defender

### ISSUE THREAD

**Issue by GamaBurst** [unexpectedpanda/retool#330]
**Describe the bug**
Retool automatically close at launch, caused by Windows defender that automatically flag and remove the file : _internal\select.pyd
Windows defender treat this file as a Trojan.

![Capture](https://github.com/unexpectedpanda/retool/assets/98297910/8db1fde2-cbdc-45aa-8113-cb4e214c7ea9)

**To reproduce**
Just unzip the latest version and launch it.

**Operating system**
- [x] Windows 10 (older versions not supported)
- [ ] Ubuntu
- [ ] Other (please specify)

**Retool edition**
- [x] retool-gui.exe
- [ ] retool.py
- [ ] retool-gui.py

**Retool version**
retool-2.03.4-win-x86-64 and some other previous versions.

**Comment by unexpectedpanda** [comment]
There's nothing I can do about false positives other than recompile and hope whatever is triggering the antivirus decides it's no longer a threat. The best thing you can do is make an exception in Defender.
