### ISSUE TITLE
[Feature Request]: Another way to deciding what to keep and discard.

### ISSUE THREAD

**Issue by TomTurbine** [unexpectedpanda/retool#332]
Much appreciated on the other thing but was looking at the different options for "Compilation Handling" and was thinking of another one many collectors might want.

Where it keeps the clones and the compilations and only gets rid of the older revisions of games.

Examples:

On the original Nintendo, it would keep:
Mario Brothers
Mario Brothers + Duck Hunt
Mario Brothers + Duck Hunt + Track Meet
Punch Out
Mike Tyson's Punch Out

But when it came to the different revisions of each of them or all the Mega Man games revisions from all those different sources, it would only keep one of each of them.

Or on the Wii, it would keep;

Just Dance (Rev 1)
Just Dance (Target Exclusive Edition) (Rev 1)
Just Dance (Best Buy Edition) (Rev 1)

but would discard
Just Dance
Just Dance (Target Exclusive Edition)
Just Dance (Best Buy Edition)

That way you could keep each variation of the games without keeping each revision of those variations. And on the Nintendo DS Beyblade series I mentioned in the other ticket, it would keep each version of it.

**Comment by unexpectedpanda** [comment]
Cheers, I appreciate where you're coming from. However this capability isn't something I'm interested in pursuing.
