### ISSUE TITLE
Post filters are broken since v2.3.5

### ISSUE THREAD

**Issue by Keiyuu** [unexpectedpanda/retool#338]
First of all, apologies for opening this issue after your announcement. I only encountered it just now because I was on version 2.03.4 and only updated today.

Whenever I want to use Post filters, Retool fails to process the DAT and stops with the follow error:

> Traceback (most recent call last):
  File "retoolgui.py", line 278, in run
  File "retool.py", line 278, in main
  File "modules\title_selection\overrides_post_filters.py", line 202, in post_filters
TypeError: user_override_post_filter_match() got an unexpected keyword argument 'post_filter'

This is happening with any DAT, both in global and in system settings. I already tried fresh installs with default settings.
I have confirmed this error started at version v2.3.5 and every version since then is affected.

**Operating system**
- [x] Windows 10 (older versions not supported)
- [ ] Ubuntu
- [ ] Other (please specify)

**Retool edition**
- [x] retool-gui.exe
- [ ] retool.py
- [ ] retool-gui.py

**Retool version**
v2.3.5, v2.3.6, v2.3.7

**Comment by unexpectedpanda** [comment]
Fixed.
