### ISSUE TITLE
Compilations handling not working?

### ISSUE THREAD

**Issue by SiriusVI87** [unexpectedpanda/retool#339]
**Describe the bug**
I have set the compilation handling option to "keep individual titles and compilations", but after processing my SNES dat file, compilations seem to be preferred over individual titles. The individual titles are missing (e.g.: Super Mario All-Stars + Super Mario World (USA) is kept, but not the individual Super Mario World.)

**Comment by unexpectedpanda** [comment]
The logic is correct, but the clone list had to be updated to change _Super Mario All-Stars + Super Mario World_ from a superset to a compilation. That's done now, update your clone lists and it'll work as expected.

**Comment by SiriusVI87** [comment]
Great, thank you! On that note, I believe an option for supersets, similar to the "compilation handling" would be great. Users could chosse to just keep the superset or keep the superset and previous versions also.

To my mind it makes sense that if a cartridge of a game exists, it counts as a distinct title. So I'd like to keep Super Mario All-Stars + Super Mario World, Super Mario All-Stars, and Super Mario World, no matter the first one is considered a comilation or a superset of the latter two titles.

**Comment by unexpectedpanda** [comment]
> To my mind it makes sense that if a cartridge of a game exists, it counts as a distinct title. So I'd like to keep Super Mario All-Stars + Super Mario World, Super Mario All-Stars, and Super Mario World, no matter the first one is considered a comilation or a superset of the latter two titles.

That's exactly what the clone list change enables, but I'm guessing you mean if the compilation was still set as a superset.

It looks like you might have missed the post &mdash; no new features are coming in the foreseeable future, as [Retool is no longer maintained](https://github.com/unexpectedpanda/retool/issues/337).
