### ISSUE TITLE
missing </datafile> at end of file

### ISSUE THREAD

**Issue by feurry** [unexpectedpanda/retool#34]
Running the latest windows retool-gui.exe with Sega - Mega Drive - Genesis dat (downloaded today) after downloading the updated clonelists.

set regions to USA,World,Canada,Europe

language English

Exclusions:
Applications
Bad Dumps
Coverdiscs
Demos and samples
Pirate
Preproduction
Promotional
Unlicensed
Video

Crashes right at the end, but appears to finish, other than not ending the dat file properly.

</datafile> was missing, but once I manually added that, the file ran fine in clrmamepro and romcenter. It had 785 entries.

I installed the latest from Git and ran retool-gui.py which also produced 785 entries and created the dat properly.

Running Windows 10

**Comment by unexpectedpanda** [comment]
I'm also not able to replicate this. Same thing, if you run `retool-gui.exe` from command prompt, does it output anything when the program crashes?

Bit weird that the `py` file completed successfully, makes me wonder if there's something hardware related going on, or some other program clashing with Retool in some fashion.

**Comment by feurry** [comment]
Well that's strange. This seems to be working fine now. I ran it form command line and from explorer and it worked.

**Comment by unexpectedpanda** [comment]
It's a really odd place for it to crash, considering all it's doing is writing to a file and it had been doing that for the previous lines just fine. I had wondered if maybe there wasn't enough space on the drive.

I'll close this for now, but if you're able to replicate it, happy to reopen and look a bit deeper.
