### ISSUE TITLE
PS2 Madden NFL 08 en Espanol (USA) is considered an English Language game; It's not

### ISSUE THREAD

**Issue by pirsir76** [unexpectedpanda/retool#341]
Hi, this is my 2nd bug report.
I possess lists that I have painstakingly made by hand.
I'm happy to compare my lists with the ones that Retool outputs and help to locate possible bugs.

**Describe the bug**

Retool considers PS2 "Madden NFL 08 en Espanol (USA)" as an English Language game; It's not an English Language game.
"SingStar Latino (USA)" is the only other Spanish Language USA region PS2 game and Retool correctly excludes that when "Languages: English" is selected.

**To reproduce**
Steps to reproduce the behavior.

In Retool using Redump's PS2 dat file.
Sort by:
Region: USA 
Languages: English
Exclusions: All except games

**Expected behavior**

"Madden NFL 08 en Espanol (USA)" should not be on the output list, rather the English equivalent  "Madden NFL 08 (USA)"
should appear in it's place.

**Operating system**
- [x ] Windows 10 (older versions not supported)
- [ ] Ubuntu
- [ ] Other (please specify)

**Retool edition**
- [x ] retool-gui.exe
- [ ] retool.py
- [ ] retool-gui.py

**Retool version**
For the command line edition of Retool, the version is shown when you run it with no other arguments.

For the GUI edition, click **Help**, then **About**.

Version 2.3.8

**Are you using custom global or system filters? If so, list them below**

Global excludes:

Global includes:

System excludes:

System includes:

**What other settings are you using?**

**Additional context**

No custom global or system filters are used. No other settings are used.

**Comment by unexpectedpanda** [comment]
This is a problem to be fixed by Redump, not Retool. You can [report it at the Redump forum](http://forum.redump.org/forum/15/fixes-additions/).

**Comment by pirsir76** [comment]
I have reported the incorrect language tag to Redump.

**Comment by pirsir76** [comment]
Just to let you know; Redump confirmed the missing language tag and fixed it. The game is not correctly labelled as being in Spanish.
