### ISSUE TITLE
PS2 Educational Games not appearing on output list

### ISSUE THREAD

**Issue by pirsir76** [unexpectedpanda/retool#342]
**Describe the bug**

Sorry, the title is wrong, it should be simply: "PS2 games not appearing on list"
Specifically these games:
- Konami Kids Playground - Alphabet Circus (USA)
- Konami Kids Playground - Dinosaurs - Shapes & Colors (USA)
- Konami Kids Playground - Frogger - Hop, Skip & Jumpin' Fun (USA)
- Konami Kids Playground - Toy Pals Fun with Numbers (USA)
It appears like Retool is trying to mislabel the type of these games. They are not considered as "Educational" on Redump, they are just considered as regular "games".

**To reproduce**
Steps to reproduce the behavior.

Use Redump PS2 .dat file.
Region: USA
Exclusions: Everything except games

**Expected behavior**

Retool should produce a list without excluding the following games:
- Konami Kids Playground - Alphabet Circus (USA)
- Konami Kids Playground - Dinosaurs - Shapes & Colors (USA)
- Konami Kids Playground - Frogger - Hop, Skip & Jumpin' Fun (USA)
- Konami Kids Playground - Toy Pals Fun with Numbers (USA)

**Operating system**
- [x ] Windows 10 (older versions not supported)
- [ ] Ubuntu
- [ ] Other (please specify)

**Retool edition**
- [x ] retool-gui.exe
- [ ] retool.py
- [ ] retool-gui.py

**Retool version**
For the command line edition of Retool, the version is shown when you run it with no other arguments.

For the GUI edition, click **Help**, then **About**.

Version 2.3.8

**Are you using custom global or system filters? If so, list them below**

Global excludes:

Global includes:

System excludes:

System includes:

**What other settings are you using?**

**Additional context**

No custom global or system filters.
No other settings.

**Comment by unexpectedpanda** [comment]
Retool manages its own categories that don't always match Redump's definition. I'm comfortable with these being classed as educational.

**Comment by unexpectedpanda** [comment]
There's no issue at all, and it's working exactly as intended. Multiple categories are assigned to those titles through the clone list, so you've excluded the educational titles by also excluding games and demos,

```json
{
	"group": "Konami Kids Playground (Demo)",
	"categories": ["Demo", "Educational", "Games"],
	"titles": [
		{"searchTerm": "Konami Kids Playground (Demo)"}
	]
},
{
	"group": "Konami Kids Playground - Alphabet Circus",
	"categories": ["Educational", "Games"],
	"titles": [
		{"searchTerm": "Konami Kids Playground - Alphabet Circus"}
	]
},
{
	"group": "Konami Kids Playground - Dinosaurs - Shapes & Colors",
	"categories": ["Educational", "Games"],
	"titles": [
		{"searchTerm": "Konami Kids Playground - Dinosaurs - Shapes & Colors"}
	]
},
{
	"group": "Konami Kids Playground - Frogger - Hop, Skip & Jumpin' Fun",
	"categories": ["Educational", "Games"],
	"titles": [
		{"searchTerm": "Konami Kids Playground - Frogger - Hop, Skip & Jumpin' Fun"}
	]
},
{
	"group": "Konami Kids Playground - Toy Pals Fun with Numbers",
	"categories": ["Educational", "Games"],
	"titles": [
		{"searchTerm": "Konami Kids Playground - Toy Pals Fun with Numbers"}
	]
},
```

**Comment by pirsir76** [comment]
I see.
Is there a way I can filter games by just one category?
Like, if I want to see all the games that have "Demo" in their category (regardless of what other categories the game has been placed in) is there a way to do that?

**Comment by unexpectedpanda** [comment]
Not with Retool there isn't.
