### ISSUE TITLE
Jak and Daxter Complete Trilogy (USA) type is incorrect

### ISSUE THREAD

**Issue by pirsir76** [unexpectedpanda/retool#343]
**Describe the bug**

Hi, my last bug to report with the PS2 platform for the USA games. :)

Redump considers PS2 Jak and Daxter Complete Trilogy (USA) as "Multimedia"
But, Retool considers it a "Video".
I double checked this; it's definitely a Multimedia title.

**To reproduce**
Steps to reproduce the behavior.

Load the Redump PS2 .dat file.
Region: USA
Exclusions: All except for video.
You will notice it flags Jak and Daxter Complete Trilogy (USA) as a video.
You can double check this title on Redump here: http://redump.org/disc/68218/
It's definitely the Multimedia type.

**Expected behavior**

With "Exclusions: all except Multimedia" Jak and Daxter Complete Trilogy (USA) appears along with the other Multimedia titles. It should not appear as a video.

**Operating system**
- [ x] Windows 10 (older versions not supported)
- [ ] Ubuntu
- [ ] Other (please specify)

**Retool edition**
- [x ] retool-gui.exe
- [ ] retool.py
- [ ] retool-gui.py

**Retool version**
For the command line edition of Retool, the version is shown when you run it with no other arguments.

For the GUI edition, click **Help**, then **About**.

Version 2.3.8

**Are you using custom global or system filters? If so, list them below**

Global excludes:

Global includes:

System excludes:

System includes:

**What other settings are you using?**

**Additional context**

No custom global or system filters and no other settings.

**Comment by unexpectedpanda** [comment]
This title is a mixture of demos, videos, and music, so the original multimedia category is correct. I've updated the clone list to take this into account.
