### ISSUE TITLE
rtool-gui.exe crashes on region sort

### ISSUE THREAD

**Issue by feurry** [unexpectedpanda/retool#35]
if you try to sort the regions list by pressing the up or down arrow, and do not have any regions selected, the program crashes.

Windows 10
retool-gui.exe 0.06

**Comment by unexpectedpanda** [comment]
I'm not able to replicate this. If you run retool-gui.exe from command prompt, does it output anything when the program crashes?

**Comment by feurry** [comment]
Traceback (most recent call last):
  File "retool-gui.py", line 943, in <module>
  File "retool-gui.py", line 684, in main
IndexError: list index out of range
[9212] Failed to execute script retool-gui

You have to hit the up or down sort buttons before you select any regions.

**Comment by unexpectedpanda** [comment]
Aha, perfect. I'll get this fixed in the next release :)

**Comment by unexpectedpanda** [comment]
Fixed in 0.88.
