### ISSUE TITLE
Missing Playstation clone

### ISSUE THREAD

**Issue by AlvaroBurnett** [unexpectedpanda/retool#36]
BallBlazer Champions (Europe) > BallBlazer Champions (USA)

**Comment by unexpectedpanda** [comment]
Cheers! Yep, for some reason Redump changed the case on the US title (BallBlazer > Ballblazer). It'll be covered in the next update.

I'm figuring I should change things to ignore case in the future too. The prevalence of Windows users makes it unlikely there'll be problems.
