### ISSUE TITLE
Include specific games from an otherwise excluded region

### ISSUE THREAD

**Issue by Freeben666** [unexpectedpanda/retool#38]
Hi,

In order to save space, I use your great tool to make 1G1R sets, only including a few regions. For example, I don't include Asian regions (Japan, Taiwan, Asia, ...). But there are a handful of games from these regions I'd like to include.

For example, I like the "Ouendan" games from Japan, which are playable even when you don't read japanese. So I tried to include them with custom filters. The thing is, apparently, once the region is filtered out, you can't include games with the custom filters (I tried with global and system filters).

My solution so far is to include the "Japan" region in my region selections, and add "(Japan)" in my global exclude filter, with "Ouendan" in the include filter. This works but is not perfect. For example, this doesn't filter out games with region (Japan, Asia).

Is there a better way to achieve what I'm trying to do?

Best regards

**Comment by unexpectedpanda** [comment]
Ah yep, only included regions are considered. Includes/excludes are a recent feature, and I hadn't considered this use case. I'll have to put some time into it for a future release. There's a chance language filters are affected too.

In the meantime, you can work around it as you've discovered, but you'll need to use some fancy regex to capture all the Japanese games and to avoid false positives:

1. Add Japan to your region order.
2. Add this to your global exclude:
   ```
   /.*?\((.*?,){0,} {0,}Japan(,.*?){0,}\)
   ```
3. Add this to your global include:
   ```
   Ouendan
   ```

**Comment by Freeben666** [comment]
Thanks for the quick answer :)

I'll be using the RegEx for now 👍

**Comment by unexpectedpanda** [comment]
Fixed as of 0.89.
