### ISSUE TITLE
Games with Sega CD 32X and Mega-CD 32X -tags

### ISSUE THREAD

**Issue by prklx2** [unexpectedpanda/retool#40]
Sega CD 32X -tag is prioritized even when setting Europe higher priority:

When using the latest Redump Sega CD & Mega CD datfile with region priorities so that European release is preferred before US, it seems that filtering doesn't quite work as it should be with CD 32X -games

As an example, game Corpse Killer:
The resulting dat will have "Corpse Killer (USA) (Sega CD 32X)" 
even though there's an European release available in the same dat, "Corpse Killer (Europe) (Mega-CD 32X)"

Here's my settings:

![Capture1](https://user-images.githubusercontent.com/78171889/110821740-09be3680-8299-11eb-8a7f-9d8c2f00be0c.PNG)
![Capture2](https://user-images.githubusercontent.com/78171889/110821742-0a56cd00-8299-11eb-9d73-22763a5d1a04.PNG)
![Capture3](https://user-images.githubusercontent.com/78171889/110821746-0aef6380-8299-11eb-9796-431efe5cb6f1.PNG)
![Capture4](https://user-images.githubusercontent.com/78171889/110821747-0aef6380-8299-11eb-90e1-2244dc2fbbfd.PNG)

**Comment by unexpectedpanda** [comment]
Supersets (and 0 priority titles) are reasonably complicated, in that they look at your region order, determine a language order from it, then compare that language order against Retool's internal region order (providing those regions are in your list). This makes sure you get supersets from other regions if they're not available in your own region but you speak the language, and prioritizes things like NTSC for higher frame rates.

In saying that, I'm reworking compilations and supersets at the moment and this directly ties in &mdash; so I'll look into how this can be improved.

Just for my own interest, are you planning to play on original/hacked hardware? There are frame rate benefits to emulating US versions if not.

**Comment by prklx2** [comment]
Okay, so the superset-filter is the issue. I might need to make more tests
with this. What you're describing sounds like there might be other similar
problems with it's logic on other systems.

About the framerates - I don't really care for them. I just want my lists
appear with European titles for nostalgic and authenticity purposes. I
never played NTSC versions in my youth and PAL versions are the ones I
remember.

Also, there even are some games that are actually better on PAL systems
like Dragon's Lair on NES. That games NTSC version is notoriously bad :D

Thanks for your continued support. This software is really great and I'll
keep using this in the future because it fits all my requirements, all the
small issues aside.

**Comment by unexpectedpanda** [comment]
Cheers for the feedback, nostalgia is, weirdly, not something I'd taken into account.

The superset logic is indeed independent of system. But in 0.89 it and compilations will be going away in favor of regular clone assignment, so there's opportunity to close this particular loophole.

**Comment by unexpectedpanda** [comment]
Fixed as of 0.89. If Europe is above USA, then Mega CD 32X gets selected. If USA is above Europe, Sega CD 32X gets selected.

A `0` priority otherwise continues to work as it previously did.
