### ISSUE TITLE
Missing Parent/Clone relationships on Sony PlayStation Portable

### ISSUE THREAD

**Issue by DiGiCoDe77** [unexpectedpanda/retool#42]
## Dat
Sony - PlayStation Portable - Datfile (2193) (2021-03-26 19-58-07) [Redump]

## Issue
Crimson Gem Saga (USA)
Astonishia Story 2 (Korea)
https://renascene.com/psp/info/umd/1823

Smart Bomb (USA)
Baku-No (Asia)
https://renascene.com/psp/info/umd/6

WTF - Work Time Fun (USA)
Beit Hell 2000 (Japan)
https://renascene.com/psp/info/umd/694

Harvest Moon - Boy & Girl (USA)
Bokujou Monogatari - Harvest Moon - Boy & Girl (Japan) 
https://renascene.com/psp/info/umd/1114

Buzz! Quiz World (Europe) (En,Pl)
Buzz! Concurso Universal (Europe) (Es,Pt)
https://www.cdiscount.com/Product/Zoom/0711719152750/0.html
https://xtremmedia.com/gestor/files/images/A004339_0_2.jpeg

Buzz! Das grosse Laenderquiz (Europe) (De,It)
Buzz! Polskie Lamiglowki ~ Buzz! Mozak Hrvatske (Europe) (Pl,Hr)
https://en.wikipedia.org/wiki/Buzz!:_Brain_of_the_World

Pursuit Force (Europe) (En,Fr,De,Es,It)
Chase Cop - Pursuit Force (Korea)
https://renascene.com/psp/info/umd/324

DJ Max Portable - Black Square (Japan)
DJ Max Emotional Sense P - Black Square (Korea) (En,Ja,Ko)
https://renascene.com/psp/info/umd/1686

Dragoneer's Aria (Europe)
Dragoneer's Aria - Ryu ga Nemuru Made (Asia) (En,Ja)
https://renascene.com/psp/info/umd/1137

Formula One 06 (Europe) (En,Fr,De,Es,It,Pt,Fi)
F1 06 Portable (Asia)
https://renascene.com/psp/info/umd/845

Off Road (Europe) (En,Fr,De,Es,It)
Ford Racing - Off Road (USA)
https://renascene.com/psp/info/umd/1545

SBK-07 - Superbike World Championship (Europe) (En,Fr,De,Es,It)
Hannspree Ten Kate Honda SBK - Superbike World Championship (USA)
https://renascene.com/psp/info/umd/1436

Key of Heaven (Europe) (En,Fr,De,Es,It)
Kingdom of Paradise (USA)
Tenchi no Mon (Asia) (v1.00)
Tenchi no Mon (Asia) (v1.01)
Tenchi no Mon (Japan)
Tenchi no Mon (Korea)
https://renascene.com/psp/info/umd/197

LittleBigPlanet (Europe) (En,Fr,De,Es,It,Nl,Pt,Sv,No,Da,Fi,Pl,Ru)
Little Big Planet (Asia) (En,Zh,Ko)
https://renascene.com/psp/info/umd/2030

LocoRoco (Europe) (En,Fr,De,Es,It,Nl,Pt,Sv,No,Da,Fi,Ru)
LocoRoco (Japan) (Toku Toku Pack)
https://renascene.com/psp/info/umd/1023

Lumines - Puzzle Fusion (Europe) (En,Fr,De,Es,It)
Lumines (Japan)
https://renascene.com/psp/info/umd/120

Disgaea - Afternoon of Darkness (Europe)
Makai Senki Disgaea Portable - Tsuushin Taisen Hajimemashita. (Japan)
https://renascene.com/psp/info/umd/1297

FIFA World Cup Germany 2006 (Europe)
Mondiali FIFA 2006 (Italy)
https://renascene.com/psp/info/umd/548

Mawaskes Puzzle (Europe) (En,Fr,De,Es,It,Nl)
Puzzle Guzzle (USA)
https://renascene.com/psp/info/umd/1894

White Knight Chronicles - Origins (Europe) (En,Fr,De,Es,It)
Shirokishi Monogatari Episode Portable - Dogma Wars (Japan)
https://renascene.com/psp/info/umd/2633

Silent Hill Origins (Europe) (En,Fr,De,Es,It)
Silent Hill Zero (Japan)
https://renascene.com/psp/info/umd/1259

Super Pocket Tennis (Europe)
Simple 2500 Series Portable!! Vol. 2 - The Tennis (Japan, Asia)
https://renascene.com/psp/info/umd/1048

Simpson, Les - Le Jeu (France)
Simpsons Game, The (Europe)
https://renascene.com/psp/info/umd/1249

Pro Evolution Soccer 5 (Europe) (En,Fr,De,Es,It)
World Tour Soccer - Winning Eleven 9 (USA)
https://renascene.com/psp/info/umd/289

**Comment by unexpectedpanda** [comment]
Cheers! I'll be able to jump on it after I finish the supersets/compilation rework.

In theory the code is done now, just need to go through some of the brain bending logic to set the clones appropriately across multiple regions.

**Comment by unexpectedpanda** [comment]
The PlayStation Portable (Redump) clone list has been updated.
