### ISSUE TITLE
Video-filter doesn't remove GBA Video -titles

### ISSUE THREAD

**Issue by prklx2** [unexpectedpanda/retool#43]
Video-filter doesn't seem to remove GBA Video -titles.

Used (-aABcCdemMv) on latest No-Intro and resulted with this;
[Nintendo - Game Boy Advance (20210326-211504) (Retool 2021-04-02 16-16-33) (1,161) (-aABcCdemMv).txt](https://github.com/unexpectedpanda/retool/files/6250261/Nintendo.-.Game.Boy.Advance.20210326-211504.Retool.2021-04-02.16-16-33.1.161.-aABcCdemMv.txt)

Basically every title that starts with "Game Boy Advance Video".
Dunno if there are any others.

VersIon: GUI v0.88.

**Comment by unexpectedpanda** [comment]
Thanks -- the video exclusion only filters out titles with a category of video at the moment. I'll add that string in the next release.

**Comment by unexpectedpanda** [comment]
Fixed as of 0.89.
