### ISSUE TITLE
ColecoVision - 3 Roms that are not games [Applications]

### ISSUE THREAD

**Issue by jim16127** [unexpectedpanda/retool#45]
- ColecoVision Monitor Test (USA, Europe)
- Final Test Cartridge (USA)
- Super Controller Tester (USA)

**Comment by unexpectedpanda** [comment]
Unfortunately there's no way for Retool to programmatically identify these as applications, as No-Intro doesn't supply enough information in their dat.

At this point in time Retool doesn't support manual assignment of applications either. I'm not sure I want to open that can of worms, but I'll keep this issue around just in case I change my mind one day.

**Comment by unexpectedpanda** [comment]
Corrected in 0.92 when it's released.
