### ISSUE TITLE
Microsoft MSX - 2 Roms - Not what these should be classified as but they are not games [Applications]

### ISSUE THREAD

**Issue by jim16127** [unexpectedpanda/retool#46]
Not what these should be classified as but they are NOT games, potentially the "Applications" category?

- Basic Lessons 1 (Japan)
- Basic Lessons 2 (Japan)

**Comment by unexpectedpanda** [comment]
As per #45, there's no way to programmatically detect these as applications. No-Intro would have to add more information to their dat or db in order to do so.

**Comment by unexpectedpanda** [comment]
Corrected in 0.92 when it's released.
