### ISSUE TITLE
NEC - PC Engine - TurboGrafx 16 - 1 Rom is not a game [Applications]

### ISSUE THREAD

**Issue by jim16127** [unexpectedpanda/retool#47]
- Ten no Koe Bank (Japan)

The Ten no Koe Bank is a device released by Hudson Soft to allow CD-ROM² games to save data.
https://necretro.org/Ten_no_Koe_Bank

**Comment by unexpectedpanda** [comment]
Cheers. Again, this is a No-Intro problem, as they don't include categories. Retool can't programmatically detect what type of title this is.

**Comment by jim16127** [comment]
I know...I'm thoroughly combing the results...This just seems like the best place to document my findings.  ; ) Your software is AWESOME!!! The Parent/Clone list you maintain is second to NONE. Thanks again, you've saved me and many other COUNTLESS hours! You're awesome! I'll probably have a few more reports for a handful of other systems.

**Comment by unexpectedpanda** [comment]
Understood :)

**Comment by unexpectedpanda** [comment]
Corrected in 0.92 when it's released.
