### ISSUE TITLE
NEC - PC Engine - TurboGrafx 16 - 1 game (4 roms) has an unusual Parent/Clone relationship???

### ISSUE THREAD

**Issue by jim16127** [unexpectedpanda/retool#48]
R-Type (USA)
R-Type I (Japan)
R-Type II (Japan)
R-Type II (Japan) (v1.1)

https://www.mobygames.com/game/turbo-grafx/r-type

The Japanese PC Engine-version of R-Type was released as two separate games, R-Type I and R-Type II, with the former containing the first four stages and the latter the remaining four. This was presumably done because the whole game would not fit on one HuCard. The second of these cards has nothing do to with the real sequel R-Type II which was never released for the PC Engine/TurboGrafx in any way. For the US TurboGrafx release they managed to fit the whole game on one HuCard so there it was simply called R-Type.

The game was later re-released (again only in Japan) as a PC Engine CD game called R-Type Complete CD which contained all of the stages, a new intro movie and improved music.

**Comment by unexpectedpanda** [comment]
Ah interesting. This one can be addressed reasonably easily with the current architecture :) It'll be fixed in the next update.

**Comment by unexpectedpanda** [comment]
The TurboGrafx 16 clone list has been updated.
