### ISSUE TITLE
Distribution roms

### ISSUE THREAD

**Issue by prklx2** [unexpectedpanda/retool#49]
Distribution roms should be filtered that can be found in No-Intro's Nintendo DS and GBA -datfiles.
Basically everything that has "distribution" in the title. My filtered DS set contained 21 of these and GBA had 4.

[Nintendo - Nintendo DS (Decrypted) (20210410-081407) (Retool 2021-04-11 14-51-46) (2,262) (-aABcCdemMv).txt](https://github.com/unexpectedpanda/retool/files/6294625/Nintendo.-.Nintendo.DS.Decrypted.20210410-081407.Retool.2021-04-11.14-51-46.2.262.-aABcCdemMv.txt)
[Nintendo - Game Boy Advance (20210410-081751) (Retool 2021-04-11 14-51-28) (1,161) (-aABcCdemMv).txt](https://github.com/unexpectedpanda/retool/files/6294627/Nintendo.-.Game.Boy.Advance.20210410-081751.Retool.2021-04-11.14-51-28.1.161.-aABcCdemMv.txt)

These aren't really necessary for anyone except perfectionist Pokemon players.

Retool doesn't seem to have a proper automatic exclusion-setting for these. 
If this kind of setting would be added in the future I suggest Add-ons, Expansions or something like that. There might be other roms in other databases that'd meet this same criteria.

**Comment by unexpectedpanda** [comment]
Filtering on "distribution" could potentially cause issues down the track, as it's just a string without parentheses.

Perhaps excluding the anything with "kiosk" in a tag might be an acceptable compromise? That way it picks up everything except _Nintendo Zone Wireless Distribution Box DS Card (World) (Rev 1)_ in those dats, and knocks out a whole lot more in other dats.

Curious what "Kiosk" means though -- I had assumed it to be retail displays with limited versions of games.

**Comment by prklx2** [comment]
That might be the best option - filter everything that has (Kiosk) or (Wi-Fi Kiosk) -tags in addition to the "distribution" in the title.

I have no idea what's the official explanation for the Kiosk -tag. I've always assumed it's used for those demo units in retails and/or events (demos in E3 etc.). There might be more info in No-Intro's naming convention documentation if that's available publicly somewhere...

**Comment by unexpectedpanda** [comment]
> There might be more info in No-Intro's naming convention documentation if that's available publicly somewhere...

It's [13 years old](https://datomatic.no-intro.org/stuff/The%20Official%20No-Intro%20Convention%20(20071030).pdf), non-exhaustive (for example, unlike Redump, there's no standardized date system), and many sets have established divergent standards since then. There's sadly not a publicly-facing index of all the tags used.

Looks like [we weren't too far off though](https://gbatemp.net/threads/x-and-z-coded-nds-roms.547810/#post-8785365):

> Kiosk games are ones used in demo units at stores etc. Sometimes they can have noticeable differences to the retail release, but usually they are near indistinguishable from the final versions AFAIK.

Rather than the addition of distribution, I think I'll add the option to remove kiosk titles.

**Comment by prklx2** [comment]
Yes, that's actually a better idea. Just add a new filter that removes the Kiosk-titles overall.
Made a quick search on my files and it seems a great way to go and nothing of importance will be lost.

Only rom that appeared as unique game title was "_Dr. Mario (USA) (Kiosk, GameCube)_" in No-Intro's GBA Multiboot dat. 
Maybe make the filter include only (Kiosk) and (Wi-Fi Kiosk) -tags so even that single corner case is covered.

**Comment by unexpectedpanda** [comment]
I'm happy for people to individually recover that Dr. Mario title if they want it.

There's a few more strings I'll need to capture to be complete (Redump doesn't use the same format), but it'll be in 0.90.
