### ISSUE TITLE
inconsistency in the PS2 json

### ISSUE THREAD

**Issue by pcca-matrix** [unexpectedpanda/retool#5]
First , Congratulations on your excellent work! 

seems there is an inconsistency in the PS2 json DB.

Arc: Twilight of the Spirits (EU), 
Arc the Lad: Seirei no Koukon (JP), 
Ark the Lad: Jeongryeongui Hwanghon (KO), 
Arc the Lad: Seirei no Tasogare, 
Arc the Lad: Jing Ling Zhi Huang Hun (AS)

it should be grouped together.

**Comment by unexpectedpanda** [comment]
Howdy, thanks for the heads up! I've grouped the _Seirei no Tasogare_ titles with _Twilight of the Spirits_, which were previously separate.

Looks like in the latest Redump dat that _Seirei no Koukon_ isn't there. If I was to guess, I'd say _Koukon_ is a mis-romanizing of _Tasogare_. The furigana above the last two kanji on the [cover](https://www.videogamex.com/image/cache/catalog/PS2/Japan/arctheladseireinotasogare_jp-1000x665w.jpg) (which is the same for both titles it seems) is definitely tasogare (たそがれ).

[Jeongryeongui Hwanghon](http://redump.org/disc/18058/) and [Jing Ling Zhi Huang](http://redump.org/disc/34360/) Hun are already grouped with Twilight of the Spirits :)
