### ISSUE TITLE
"Trailers" should be added to the Video-filter

### ISSUE THREAD

**Issue by prklx2** [unexpectedpanda/retool#50]
"Trailers" should be added to the Video-filter.

Found two roms in No-Intro's Nintendo DS datfile after filtering:
_Legend of Zelda, The - Twilight Princess - Preview Trailer (USA) (Promo)
Legend of Zelda, The - Twilight Princess - Movie Trailer Vol. 1 (USA) (Kiosk) (E3 2005) [b].7z_

[Nintendo - Nintendo DS (Decrypted) (20210410-081407) (Retool 2021-04-11 14-51-46) (2,262) (-aABcCdemMv).txt](https://github.com/unexpectedpanda/retool/files/6294674/Nintendo.-.Nintendo.DS.Decrypted.20210410-081407.Retool.2021-04-11.14-51-46.2.262.-aABcCdemMv.txt)

**Comment by unexpectedpanda** [comment]
This one could be a bit stickier. "Trailer" is a word with multiple meanings. I'll see what I can do, but no promises on this one.

You could approach this from some other angles:

* **Legend of Zelda, The - Twilight Princess - Preview Trailer (USA) (Promo)** &mdash; can be removed by excluding promotional titles.
* **Legend of Zelda, The - Twilight Princess - Movie Trailer Vol. 1 (USA) (Kiosk) (E3 2005) [b]** &mdash; can be removed by excluding bad dumps.

**Comment by prklx2** [comment]
Possibility to just add "Preview Trailer" and "Movie Trailer" to the filters?

Made a comprehensive search on my files and these two roms seem to be the only ones that even have Trailer in the name. 
Of course Trailer is so common word that this might appear in newer game titles, so that's why it might be a good idea to expand the filter with these additional words, Preview and Movie.

I don't really feel like filtering out bad dumps, because they might be the only available rom version on a particular game - this is particularly true when speaking about Nintendo DS. Pretty much the same thing with Promos - there might be some files that I want to keep and on the top of my head Pokemon Mini -console has some titles that are exclusively "Promos".

**Comment by unexpectedpanda** [comment]
I've picked up quite a few trailer strings across No-Intro and Redump, so when 0.90 is released, a lot more videos will be picked up. Thanks :)
