### ISSUE TITLE
"Trials" should be added to Demo-filter

### ISSUE THREAD

**Issue by prklx2** [unexpectedpanda/retool#51]
"Trials" should be added to Demo and samples-filter.

In No-Intro's GBA Multiboot -datfile there's four trial versions of games:
_Made in Wario - Trial Version (Japan)
WarioWare, Inc. - Trial ver. 1 (World)
WarioWare, Inc. - Trial ver. 4 (World)
WarioWare, Inc. - Trial version (USA)_

[Nintendo - Game Boy Advance (Multiboot) (20210321-122109) (Retool 2021-04-12 10-31-58) (34) (-aABcCdemMv).txt](https://github.com/unexpectedpanda/retool/files/6294746/Nintendo.-.Game.Boy.Advance.Multiboot.20210321-122109.Retool.2021-04-12.10-31-58.34.-aABcCdemMv.txt)

**Comment by unexpectedpanda** [comment]
In theory the following shouldn't be too much of an issue to capture:

* Trial version
* Trial ver. #

I'll do a search of the dats and make sure nothing untoward turns up, and if not, it'll be in the next version.

**Comment by unexpectedpanda** [comment]
This will make it into 0.90 -- cheers!
