### ISSUE TITLE
Nintendo - Family Computer Disk System - 10 Roms are not games. [Applications]

### ISSUE THREAD

**Issue by jim16127** [unexpectedpanda/retool#52]
+ Tonkachi Editor (Japan) (Unl)
https://www.satakore.com/nintendo-famicom-disk-system-video-game-store,,24,,370,,Tonkachi-Editor-JP-Unlicensed.html
Tonkachi Editor (Unlicensed) is a Tool game, developed and published by I2 (Aitsu).

+ Souseiki Fammy - ROM-QD for 256K+64K (Japan) (Unl)
https://www.satakore.com/nintendo-famicom-disk-system-video-game-store,,24,,404,,Souseiki-Fammy-JP-Unlicensed.html
Souseiki Fammy (Unlicensed) is a Copier, developed and published by I2 (Aitsu).

+ Quick Hunter (Japan) (Unl)
+ Quick Hunter - Parameter Disk Vol.1 (Japan) (Unl)

**Not entirely sure what these Quick Hunter roms are. Google search just generates the rom download. So i booted them both in an emulator. Parameter Disk just black screen & Quick Hunter sits at a screen that "looks like" a title screen but unsure. Fairly sure these 2 roms are NOT games.

+ Kosodate Gokko (Japan) (Unl)
https://www.famicomworld.com/forum/index.php?topic=12853.0
Kosodate Gokko is a Disk Copier.

+ Graphic Editor Hokusai - Ver 1.2 (Japan) (Unl)

+ FMC Disk Card Checker Ver 1.3 (Japan) (Rev 2) (Developer Card)

+ Disk Keeper (Japan) (Unl)

+ Disk Hacker - Version 1.3 (Japan) (Unl)

+ Disk Hacker II - Copy Plus 3 (Japan) (Unl)

**Comment by unexpectedpanda** [comment]
[Looks like _Quick Hunter_ is a disk copier](https://www.famicomworld.com/forum/index.php?topic=14843.0), along with a [bunch of other stuff](https://www.famicomdisksystem.com/disk-copy/).

These will be corrected in 0.92.
