### ISSUE TITLE
Nintendo - Game Boy - 4 Roms which are superseded by existing roms

### ISSUE THREAD

**Issue by jim16127** [unexpectedpanda/retool#53]
I'm not sure how you address these. All of the games included in these "4 in 1" roms are existent using the default sort order that you provide, thus they should be removed.

- Mani 4 in 1 - Genki Bakuhatsu Gambaruger + Zettai Muteki Raijin-Oh + Zoids Densetsu + Miracle Adventure of Esparks - Ushinawareta Seiseki Perivron (China)

	+ Genki Bakuhatsu Gambaruger (Japan)
	+ Zettai Muteki Raijin-Oh (Japan)
	+ Zoids Densetsu (Japan)
	+ Miracle Adventure of Esparks - Ushinawareta Seiseki Perivron (Japan)

- Mani 4 in 1 - R-Type II + Saigo no Nindou + Ganso!! Yancha Maru + Shisenshou - Match-Mania (China)

	+ R-Type II (Europe)
		+ R-Type II (Japan)
	+ Saigo no Nindou (Japan)
	+ Ganso!! Yancha Maru (Japan)
	+ Shisenshou - Match-Mania (Japan)

- Mani 4 in 1 - Takahashi Meijin no Bouken-jima II + GB Genjin + Bomber Boy + Milon no Meikyuu Kumikyoku (China)

	+ Milon's Secret Castle (USA, Europe)
		+ Milon no Meikyuu Kumikyoku (Japan)
	+ Atomic Punk (USA)
		+ Bomber Boy (Japan)
	+ Bonk's Adventure (USA)
		+ GB Genjin (Japan)
	+ Adventure Island II - Aliens in Paradise (USA, Europe)
		+ Takahashi Meijin no Bouken-jima III (Japan)

- Mani 4 in 1 - Tetris + Alleyway + Yakuman + Tennis (China)

	+ Tetris (World) (Rev 1)
		+ Tetris (Japan) (En)
	+ Alleyway (World)
	+ Yakuman (Japan) (Rev 1)
		+ Yakuman (Japan)
	+ Tennis (World)

**Comment by unexpectedpanda** [comment]
Cheers, it'll go out in the next clone list update.

**Comment by unexpectedpanda** [comment]
Accidental close. The short version is, compilations are tricky, especially cross-region (see #20). I'll consider it when I put the time aside to tackle the other compilation fun in GBA.

**Comment by unexpectedpanda** [comment]
Thanks folks. It's been a long time coming, but thanks to the changes in v2 beta 8, this is now fixed.
