### ISSUE TITLE
Nintendo - Game Boy - 8 Roms which are not games [Applications]

### ISSUE THREAD

**Issue by jim16127** [unexpectedpanda/retool#54]
- Game Boy Camera Gold (USA) (SGB Enhanced)
- Game Boy Controller Kensa Cartridge (Japan)
- Game Boy Datenlogger 1 (Germany) (Unl)
- Game Genie (USA) (v2.1) (Unl)
- GameShark (USA) (Unl)
- Minolta Camera Test Cart 2420 (USA)
- Pro Action Replay (Europe) (Unl)
- SMARTCOM (Europe) (Unl)

**Comment by unexpectedpanda** [comment]
Fixed when 0.92 is released.
