### ISSUE TITLE
Nintendo - Game Boy Color - dealing with European title localization

### ISSUE THREAD

**Issue by jim16127** [unexpectedpanda/retool#56]
+ Barca Total 2000 (Europe) (En,Fr,De,Es,It,Nl,Ca)
	- David O'Leary's Total Soccer 2000 (Europe) (En,Fr,De,Es,It,Nl)

Shouldn't it be...

+ David O'Leary's Total Soccer 2000 (Europe) (En,Fr,De,Es,It,Nl)
	- Barca Total 2000 (Europe) (En,Fr,De,Es,It,Nl,Ca)

**Comment by unexpectedpanda** [comment]
Could you give more context why you think things should be ordered that way?

**Comment by jim16127** [comment]
"Barca Total 2000" is the spanish title.

https://www.mobygames.com/game/david-olearys-total-soccer-2000

**Comment by unexpectedpanda** [comment]
Yeah language order is always meant to be the same for No-Intro, it's one of their standards. Default written + audio language first might be a preferable system. I think in GBA they've been messing with a new system looking at how the languages are formatted there, but it's still not ideal for this particular scenario.

Back to the topic at hand. One way Retool selects a parent from titles in the same region with the same priority is to look at how many languages they support, while also taking into account the user's region order and the implied language preference from that region order. In this case, to Retool, the Spanish version looks superior as it supports all the same languages plus one more.

I don't know that this can be corrected unless No-Intro changes the region tag or the language ordering. I could make O'Leary higher priority in the clone list, but then that would disadvantage Spanish users. Other solutions involve a lot more manual work for me (non-starter), integrating some sort of scraping system (slow), or even crowdsourcing the content... but each of these are large in work size, come with their own challenges, and are effectively starting a secondary No-Intro DB. Makes more sense to fix the problem at the source... but it's unlikely a priority for No-Intro, and would involve a lot of manual work for them too to shift standards.

In this case I reckon you might need to use custom system filters to get around it. Not ideal, but it's a rock-and-hard-place situation.

**Comment by jim16127** [comment]
I understand everything you stated. I don't mind custom filtering any and all instances I find. Although, I still think it is more uniform utilizing the english title release for "Europe" releases, if applicable, in the Parent/Clone lists. Since most if not all Europe games are in english with english artwork, manuals, in-game text, etc.

**Comment by unexpectedpanda** [comment]
Noted. Agree that it's more uniform, but I don't see it as more appropriate. I'm loathe to adjust the clone list priorities in this manner as well.

I recognise it's an issue though. I'll put some more thought into what a viable solution might be.

**Comment by unexpectedpanda** [comment]
This is finally addressed as of v2 beta 9. If the user ranks Europe above Spain, David O'Leary's wins. The other way around, Barca Total 2000 wins.
