### ISSUE TITLE
Nintendo - Game Boy Color - 1 Rom is missing from a Parent/Clone collection

### ISSUE THREAD

**Issue by jim16127** [unexpectedpanda/retool#57]
+ Tom and Jerry - Mousehunt (Europe) (En,Fr,De,Es,It) (Rev 1)
	- Tom and Jerry - Mousehunt (Europe) (En,Fr,De,Es,It)

This rom is missing from that Parent/Clone collection...
+ Tom and Jerry - Mouse Hunt (USA) (En,Fr,Es)

**Comment by unexpectedpanda** [comment]
Cheers, it'll go out in the next clone list update.
