### ISSUE TITLE
Nintendo - Nintendo Entertainment System - 6 Roms 2 games is missing Parent/Clone relationship

### ISSUE THREAD

**Issue by jim16127** [unexpectedpanda/retool#58]
+ Mahjang Companion (Japan) (Hacker) (SA-016 PCB) (Unl)
	- Mahjang Companion (Asia) (Ja) (Sachen) (Unl)
	- Mahjang Companion (Japan) (Hacker) (SA-002 3011 PCB) (Unl)		<---Do NOT make this one the parent! It does NOT run!

+ Nomolos - Storming the CATsle (World) (V1.01) (Aftermarket) (Unl)
	- Nomolos - Storming the CATsle (World) (V1.00) (Aftermarket) (Unl)
	- Nomolos - Storming the CATsle (World) (V1.00D) (Aftermarket) (Unl)		<---This is a DEMO!
	- Nomolos - Storming the CATsle (World) (V1.00D) (Aftermarket) (Alt) (Unl)	<---This is a DEMO!

**Comment by unexpectedpanda** [comment]
Fixed when the next clone list update is released.
