### ISSUE TITLE
Nintendo - Nintendo Entertainment System - PunchOut!! vs Mike Tyson's PunchOut!!

### ISSUE THREAD

**Issue by jim16127** [unexpectedpanda/retool#59]
Are these truly the 'same' game?? We're these intentionally matched together? Having played them both. They ARE different.
....Just a suggestion ;)

**Comment by unexpectedpanda** [comment]
To my understanding, the only difference is the rebranding and replacing Tyson with Mr Dream. Since this is a superficial change, they are treated as the same title.

**Comment by jim16127** [comment]
Understood!
