### ISSUE TITLE
Nintendo - Game Boy Advance -  2 Parent/Clone relationships need merged [Polly Pocket! - Super Splash Island]

### ISSUE THREAD

**Issue by jim16127** [unexpectedpanda/retool#60]
+ Polly Pocket! - Super Splash Island (USA) (DSI)
	- Polly Pocket! - Super Splash Island (Europe) (En,Fr,De,Es,It) (DSI)
	- Polly Pocket! - Super Splash Island (Europe) (En,Fr,De,Es,It) (Vivendi)
 	- Polly Pocket! - Super Splash Island (USA) (Vivendi)

**Comment by unexpectedpanda** [comment]
This will be in the next clone list update.
