### ISSUE TITLE
Nintendo - Game Boy Advance - 12 Roms are not games [Applications]

### ISSUE THREAD

**Issue by jim16127** [unexpectedpanda/retool#61]
+ Action Replay MAX (Europe) (Unl)
+ Aging Cartridge (World)
+ CodeBreaker (USA) (Unl)
+ e-Reader (USA)
+ GameShark GBA (USA) (Unl)
+ GBA AV Adapter (China) (Unl)
+ GBA Movie Player 2 CF (Spain) (Unl)
+ GBA Personal Organizer (USA) (Unl)
+ GBA TV Tuner PAL (China) (v2.0) (Unl)
+ iQue Reader (China)
+ iQue Video & Audio (China)
+ Nintendo MP3 Player (Europe) (En,Fr,De,Es,It)

**Comment by unexpectedpanda** [comment]
Fixed when 0.92 is released.
