### ISSUE TITLE
Nintendo - Super Nintendo Entertainment System - 8 Roms are not games [Applications]

### ISSUE THREAD

**Issue by jim16127** [unexpectedpanda/retool#65]
+ Game Genie (USA) (v2.0) (Unl)
+ Game Saver (Europe) (v1.7) (Unl)
+ Pro Action Replay MK3 (Europe) (Unl)
+ SNES Burn-in Test Cartridge (USA) (Rev D)
+ Super 8 (USA) (Unl)
+ Super Game Boy (Japan, USA) (Rev 1)
+ World Class Service Super Nintendo Tester (USA)
+ XBAND (USA)

*** I only scoured through Non Japan Roms***

**Comment by unexpectedpanda** [comment]
Fixed when 0.92 is released.
