### ISSUE TITLE
Nintendo - Nintendo Entertainment System - 1 Game - "Pop'n TwinBee" - Incorrect Parent Clone order

### ISSUE THREAD

**Issue by jim16127** [unexpectedpanda/retool#66]
Currently this is how it's organized...
+ Pop'n TwinBee (Europe)
	- Pop'n TwinBee (Japan)
	- Pop'n TwinBee (USA, Europe) (Switch Online)

It should be like this...

+ Pop'n TwinBee (USA, Europe) (Switch Online)
	- Pop'n TwinBee (Europe)
	- Pop'n TwinBee (Japan)

*Utilizing your region preset in retool, "Pop'n TwinBee (USA, Europe) (Switch Online)" should be the kept rom. It is USA region & NTSC format. Whereas, "Pop'n TwinBee (Europe)" is EU region & PAL format.

**Comment by unexpectedpanda** [comment]
This is working as intended. It's demoted because it's from Switch Online, a modern ROM rip.

To reverse this, set **Titles ripped from modern platform rereleases replace standard editions** in the **Modes** tab.
