### ISSUE TITLE
Game slips through

### ISSUE THREAD

**Issue by AlvaroBurnett** [unexpectedpanda/retool#7]
The NES game "Fan Kong Jing Ying (Asia) (Unl)" is all in Chinese but it passes the English filter.

**Comment by unexpectedpanda** [comment]
At first I thought this might need to be handballed back to No-Intro, but there's a potential workaround here.

No-Intro doesn't always include available languages in their titles. In addition to this, IIRC their standard states if there's only one language available for the title, don't list it. While this helps to keep filenames succinct, it becomes a problem for users when you have large regions with lots of languages to choose from like "Asia". On the face of it, there's nothing the user can do to determine the language of a title other than boot it up. For Retool, it can glean nothing about available languages from the dat unless they're explicitly listed.

What is interesting, though, is that No-Intro offers a "database" version of their dats, which seems to include more info for each title. In this case, it _does_ tell us the available languages:

```
Fan Kong Jing Ying (Asia) (Unl)
  Number: 0729
  Clone: P
  Name: Fan Kong Jing Ying
  Region: Asia
  Languages: Zh
```

Retool's metadata folder already includes info scraped from Redump's website that's regularly updated in an attempt to get around this exact language problem. I'll look into whether I can automate that for No-Intro as well.

**Comment by AlvaroBurnett** [comment]
Excellent! Thank you very much for the detailed explanation.
