### ISSUE TITLE
Philips CD-i, small clonelist fixes

### ISSUE THREAD

**Issue by prklx2** [unexpectedpanda/retool#70]
## Dat
Philips - CD-i - Datfile (845) (2021-04-20 18-10-30)

## Issue
Small clonelist fixes for Philips CD-i:

"_Zombie Dinos van de Planeet Zeltoid_" 
	is a Dutch clone of "_Zombie Dinos from Planet Zeltoid_"

"_Labyrinth von Kreta_" 
	is a German clone of "_Labyrinth of Crete_"
 
The English title is currently missing from Redump, but probably will be dumped in the future since it exists: https://www.mobygames.com/game/cd-i/labyrinth-of-crete_

**Comment by prklx2** [comment]
Found one more.

"_Mad Dog 2 - Le Tresor Perdu_"
is a French clone of "_Mad Dog II - The Lost Gold_"

**Comment by unexpectedpanda** [comment]
CD-i is definitely on a huge update spree at the moment. These will be in the next update.
