### ISSUE TITLE
retool.py clears screen on startup

### ISSUE THREAD

**Issue by AlvaroBurnett** [unexpectedpanda/retool#71]
**Describe the bug**
retool.py clears the screen on startup, which is very inconvenient when invoked from a batch file.

**To reproduce**
Invoke retool.py from the command line or from a batch file.

**Expected behavior**
Do not clear the screen.

**Operating system**
- [x] Windows 10 (older versions not supported)
- [ ] Ubuntu
- [ ] Other (please specify)

**Retool edition**
- [ ] retool-gui.exe
- [x] retool.py
- [ ] retool-gui.py

**Retool version**
version 0.91

For the GUI edition, click **Help**, then **About**.

**Are you using custom global or system filters? If so, list them below**

Global excludes:

Global includes:

System excludes:

System includes:

**What other settings are you using?**

**Additional context**

**Comment by unexpectedpanda** [comment]
Good call. This will be in 0.92.

**Comment by unexpectedpanda** [comment]
Built into 0.92. Might be a little while before release.
