### ISSUE TITLE
Sega - Mega Drive - Genesis - Is this the expected behavior for Parent/Clones??

### ISSUE THREAD

**Issue by jim16127** [unexpectedpanda/retool#74]
This rom...
+ Ariel the Little Mermaid (USA, Europe) (1992-10-10) (Sega Channel)

Supersedes this rom...
+ Ariel the Little Mermaid (USA, Europe)

Is that the expected behavior? There are a handful of other games that this happens with as well. I'm combing through Genesis right now. Just want to know if I should report all the instances of this? (I'll edit this post if so)

**Comment by unexpectedpanda** [comment]
Sure is, Sega Channel is promoted above other titles.

**Comment by jim16127** [comment]
Okay...but what about Genesis Mini & Mega Drive Mini? Wouldn't those fall into a similar category as Virtual Console?

+ (Genesis Mini)
+ (Mega Drive Mini)

**Comment by jim16127** [comment]
This is the only Sega Channel rom i see that is an incorrect Parent/Clone. Did it end up like that because it's titled differently? 

+ F-22 Interceptor - Advanced Tactical Fighter (USA) (F-205)
	- F-22 Interceptor (USA) (1991-09-17) (Sega Channel)
	- F-22 Interceptor - Advanced Tactical Fighter (Japan)
	- F-22 Interceptor - Advanced Tactical Fighter (USA, Europe) (F-202)


Either way, following the current scheme should result in this...

+ F-22 Interceptor (USA) (1991-09-17) (Sega Channel)
	- F-22 Interceptor - Advanced Tactical Fighter (Japan)
	- F-22 Interceptor - Advanced Tactical Fighter (USA) (F-205)
	- F-22 Interceptor - Advanced Tactical Fighter (USA, Europe) (F-202)

**Comment by unexpectedpanda** [comment]
Yes, Genesis and Mega Drive Mini should be demoted as well. They were recently added to No-Intro, and Retool was updated to take them into account. If you're running 0.91 and the latest clone lists, there should only be a few of those (IIRC) hanging around as unique titles.

I'm going to have to research the F22 relationship, I don't know offhand what's going on there, and haven't been working on Retool for a little while.

**Comment by unexpectedpanda** [comment]
The F22 relationship was an error in the clone list, and will be corrected in the next update.
