### ISSUE TITLE
Sega - Mega Drive - Genesis - Another (TAG) that can be added?

### ISSUE THREAD

**Issue by jim16127** [unexpectedpanda/retool#75]
This is the Parent/Clone list of this (Prerelease) game...

+ Arkagis Revolution (World) (En,Fr,Es) (Prerelease) (2020-03-04) (Unl)
	- Arkagis Revolution (World) (En,Es) (Prerelease) (2019-07-29) (Unl)
	- Arkagis Revolution (World) (En,Es) (Prerelease) (2019-09-02) (Unl)
	- Arkagis Revolution (World) (En,Es) (Prerelease) (2019-09-16) (Unl)
	- Arkagis Revolution (World) (En,Fr,Es) (Prerelease) (2019-02-21) (Unl)
	- Arkagis Revolution (World) (En,Fr,Es) (Prerelease) (2019-11-28) (Unl)

This is the full game...

+ Arkagis Revolution (World) (En,Fr,Es) (Rev 1) (Aftermarket) (Unl)

The (Prerelease) tag can be added to the filters??

**Comment by unexpectedpanda** [comment]
Will look into it. The Aftermarket tag might cause issues, so I'll need to be careful.

**Comment by unexpectedpanda** [comment]
`(Prerelease)` will be recognized as a preproduction title when 0.92 is released.
