### ISSUE TITLE
Sega - Mega Drive - Genesis - 15 Compilation Roms can be removed

### ISSUE THREAD

**Issue by jim16127** [unexpectedpanda/retool#76]
+ 6-Pak (USA)

	- Bare Knuckle - Ikari no Tekken ~ Streets of Rage (World)
	- Columns (USA, Europe)
	- Golden Axe (World)
	- Revenge of Shinobi, The (USA, Europe)
	- Sonic The Hedgehog (USA, Europe)
	- Super Hang-On (Japan, USA) (En,Ja)

+ 10 Super Jogos (Brazil)

	- Bare Knuckle - Ikari no Tekken ~ Streets of Rage (World)
	- California Games (USA, Europe)
	- Columns (USA, Europe)
	- Flicky (USA, Europe)
	- Golden Axe (World)
	- Revenge of Shinobi, The (USA, Europe)
	- Sonic The Hedgehog (USA, Europe)
	- Super Hang-On (Japan, USA) (En,Ja).zip
	- Super Monaco GP (Japan, USA) (En,Ja)
	- World Cup Soccer ~ World Championship Soccer (Japan, USA)

+ Arcade Legends Sega Mega Drive ~ Arcade Legends Sega Genesis ~ Mega Drive Play TV (World)

	- Altered Beast (USA, Europe)
	- Dr. Robotnik's Mean Bean Machine (USA)
	- Flicky (USA, Europe)
	- Golden Axe (World) (Rev A)
	- Kid Chameleon (USA, Europe)
	- Sonic The Hedgehog (USA, Europe)

+ Arcade Legends Street Fighter II' - Special Champion Edition ~ Mega Drive Play TV 3 (World)

	- Daimakaimura ~ Ghouls'n Ghosts (Japan, USA)
	- Street Fighter II' - Special Champion Edition (USA)

+ Disney Collection, The - QuackShot Starring Donald Duck + Castle of Illusion Starring Mickey Mouse (Europe)
	- Castle of Illusion Starring Mickey Mouse (USA, Europe)
	- QuackShot Starring Donald Duck ~ QuackShot - I Love Donald Duck - Guruzia Ou no Hihou (World)

+ Mega 6 Vol. 3 (Europe)
	- Bare Knuckle - Ikari no Tekken ~ Streets of Rage (World)
	- Columns (USA, Europe)
	- Revenge of Shinobi, The (USA, Europe)
	- Sonic The Hedgehog (USA, Europe)
	- Super Monaco GP (World) (En,Ja) (Rev A)
	- World Cup Soccer ~ World Championship Soccer (Japan, USA)

+ Mega Games 2 (Europe)
	- Bare Knuckle - Ikari no Tekken ~ Streets of Rage (World)
	- Golden Axe (World)
	- Revenge of Shinobi, The (USA, Europe)

+ Mega Games 3 (Europe, Asia)
	- Alien Storm (World)
	- Super Monaco GP (World) (En,Ja) (Rev A)
	- Super Thunder Blade (World)

+ Mega Games 6 (Europe)
	- Columns (USA, Europe)
	- Super Hang-On (Europe) (En,Ja) (Rev A)
	- World Cup Italia '90 (Europe)

+ Mega Games 6 Vol. 2 (Europe)
	- Columns (USA, Europe)
	- Super Hang-On (Europe) (En,Ja) (Rev A)
	- World Cup Italia '90 (Europe)

+ Mega Games I (Europe)
	- Columns (USA, Europe)
	- Super Hang-On (Europe) (En,Ja) (Rev A)
	- World Cup Italia '90 (Europe)

+ Sega Sports 1 (Europe)
	- Super Monaco GP (World) (En,Ja)
	- Ultimate Soccer (Europe) (En,Fr,De,Es,It)
	- Wimbledon (Europe)

+ Sega Top Five (Brazil)
	- Flicky (USA, Europe)
	- Shadow Dancer - The Secret of Shinobi (World)
	- Super Monaco GP (World) (En,Ja) (Rev A)
	- Super Thunder Blade (World)
	- World Cup Soccer ~ World Championship Soccer (Japan, USA)

+ Sport Games (Brazil)	***Boots straight to "Super Volleyball". According to https://segaretro.org/Sport_Games these games are included...
	- Super Real Basketball (Europe)
	- Super Volleyball (USA)
	- World Championship Soccer II (USA)

+ Game no Kanzume Otokuyou (Japan) (Sega Channel) https://segaretro.org/Game_no_Kanzume_Otokuyou

	- 16t (Japan) (Game no Kanzume Otokuyou)
	- Aworg (Japan) (SegaNet)
	- Flicky (USA, Europe)
	- Hyper Marbles (Japan) (Game no Kanzume Otokuyou)
	- Ikasuze! Koi no Doki Doki Penguin Land MD (Japan) (Game no Kanzume Otokuyou)
	- Medal City (Japan) (SegaNet)
	- Paddle Fighter (Japan) (Game no Kanzume Otokuyou)
	- Putter Golf (Japan) (Game no Kanzume Otokuyou)
	- Pyramid Magic (Japan) (Game no Kanzume Otokuyou)
	- Robot Battler (Japan) (SegaNet)
	- Shi no Meikyuu - Labyrinth of Death (Japan) (Game no Kanzume Otokuyou)
	- Teddy Boy Blues (Japan) (SegaNet)

**Comment by jim16127** [comment]
Updated ^

**Comment by jim16127** [comment]
Sports Games boots straight to Super Volleyball. There's no game selection or any indication of one aside from the size of the rom. I personally booted every compilation rom listed in this issue and verified the games listed above manually. I tested Sports Games on 3 emulators all with the same results.

**Comment by unexpectedpanda** [comment]
Cheers for the work on this. Cross region compilations are complicated, so it might be some time before I get to this issue.

**Comment by unexpectedpanda** [comment]
Thanks folks, finally handled.
