### ISSUE TITLE
Sega - Mega Drive - Genesis - "Budokan - The Martial Spirit"

### ISSUE THREAD

**Issue by jim16127** [unexpectedpanda/retool#77]
Currently this is the Parent/Clone order...

+ Budokan - The Martial Spirit (Europe)
	- Budokan - The Martial Spirit (USA) (Unl)

Shouldn't it be?...

 + Budokan - The Martial Spirit (USA) (Unl)
	- Budokan - The Martial Spirit (Europe)

**Comment by unexpectedpanda** [comment]
Working as intended &mdash; unlicensed gets demoted below commercial production releases.

**Comment by jim16127** [comment]
Okie Doke
