### ISSUE TITLE
Sega - Mega Drive - Genesis - 3 Roms are Demos

### ISSUE THREAD

**Issue by jim16127** [unexpectedpanda/retool#78]
+ Elite (Unknown) (Tech Demo, Game)
+ Elite (Unknown) (Tech Demo, Soaker)
+ Elite (Unknown) (Tech Demo, Viewer)

Couldn't these be filtered utilizing their (TAG) to assign them to the DEMO category?

**Comment by unexpectedpanda** [comment]
Fixed when 0.92 is released.
