### ISSUE TITLE
Sega - Mega Drive - Genesis - 2 Parent/Clone Fixes

### ISSUE THREAD

**Issue by jim16127** [unexpectedpanda/retool#79]
Both of these roms are classified as "Standalones". They are the same.

+ Lion King, The (World)
	- Lion King, The (World) (Aftermarket)

These roms are prioritized incorrectly in the Parent/Clone list...

+ Misplaced (Russia) (Aftermarket)
	- Misplaced (World) (Aftermarket) (Unl)

Should be like this...

+ Misplaced (World) (Aftermarket) (Unl)
	- Misplaced (Russia) (Aftermarket)

**Comment by unexpectedpanda** [comment]
I've seen the (World) and (World) (Aftermarket) once before -- it's a known bug, but this raises its visibility, thanks.

For Misplaced, I think the extra (Unl) tag is what's causing the demotion there. No-Intro isn't clear on what Aftermarket means, it just turned up recently next to a bunch of unlicensed titles, which makes me wonder if the Russian one will have a (Unl) tag soon. Will keep an eye out.

**Comment by jim16127** [comment]
If it's Aftermarket then it MUST be unlicensed. They are all created many years after the consoles lifespan and support. Sega is no longer licensing products for their defunct consoles. I suspect you may be correct, that No-Intro will be adding (unl) to aftermarket roms.

**Comment by unexpectedpanda** [comment]
Makes sense &mdash; I'll check if I can treat Aftermarket as a synonym for (Unl).

**Comment by unexpectedpanda** [comment]
Fixed when 0.92 is released.
