### ISSUE TITLE
Nintendo - Nintendo Entertainment System - Multiple Compilation Parent/Clones

### ISSUE THREAD

**Issue by jim16127** [unexpectedpanda/retool#85]
+ Rumble Station - 15 in 1 (USA) (Unl)
	- Baby Boomer (USA) (Unl)
	- Captain Comic - The Adventure (USA) (Unl)
	- Challenge of the Dragon (USA) (Color Dreams) (Unl)
	- Crystal Mines (USA) (Unl)
	- Galactic Crusader (USA) (Unl)
	- King Neptune's Adventure (USA) (Unl)
	- Master Chu and the Drunkard Hu (USA) (Unl)
	- Menace Beach (USA) (Unl)
	- Moon Ranger (USA) (Unl)
	- Operation Secret Storm (USA) (Unl)
	- P'Radikus Conflict (USA) (Unl)
	- Pesterminator - The Western Exterminator (USA) (Unl)
	- Raid 2020 (USA) (Unl)
	- Robodemons (USA) (Unl)
	- Secret Scout in the Temple of Demise (USA) (Unl)

+ Sesame Street - ABC & 123 (USA)
	- Sesame Street - 123 (USA)
	- Sesame Street - ABC (USA)

+ Super Spike V'Ball + Nintendo World Cup (USA)
	- Nintendo World Cup (USA)
	- Super Spike V'Ball (USA)

_____________________________________________________________________________________________________________________________

+ Asder - 20 in 1 (USA) (Unl)
https://bootleggames.fandom.com/wiki/Asder_20-in-1
	- Caltron - 6 in 1 (USA) (Unl) <---All 6 games on this MultiCart are included on the Asder MultiCart listed above.

+ Maxi 15 (USA) (Unl)  <---Only unique game is "Stakk'M"
https://www.mobygames.com/game/maxi-15-

**Comment by iGom** [comment]
[Multicart of Final Fantasy I and II](https://datomatic.nointro.org/index.php?page=show_record&s=45&n=0758) threated as separate game.

```
+ Final Fantasy I, II (Japan)
+ Final Fantasy (USA) (Virtual Console)
	- Final Fantasy (Japan)
	- Final Fantasy (Japan) (Rev 1)
	- Final Fantasy (Japan) (Rev 1) (3DS Virtual Console)
	- Final Fantasy (Japan) (Rev 1) (Wii and Wii U Virtual Console)
	- Final Fantasy (USA)
+ Final Fantasy II (Japan) (Wii and Wii U Virtual Console)
	- Final Fantasy II (Japan)
	- Final Fantasy II (Japan) (3DS Virtual Console)
```

**Comment by unexpectedpanda** [comment]
Thanks both. Fixed in v2. The NES DAT is now quite slow to process to figure out these compilations 😅
