### ISSUE TITLE
Coleco - ColecoVision

### ISSUE THREAD

**Issue by DiGiCoDe77** [unexpectedpanda/retool#86]
## Dat
Coleco - ColecoVision (20200926-011306)

## Issue
Super Action Football (Europe) and Super Action Football (USA) are not clones.
The first one is a soccer game: https://www.musee-des-jeux-video.com/fr/game/Super-Action-Soccer/15/2/127
The second one is an "american football" game: https://www.musee-des-jeux-video.com/fr/game/Super-Action-Football/15/2/126

**Comment by unexpectedpanda** [comment]
Thanks! This will be corrected in the next clone list update.
