### ISSUE TITLE
Non-English titles selected when English is the only language filter

### ISSUE THREAD

**Issue by HVR88** [unexpectedpanda/retool#87]
**Describe the bug**
I'm seeing a lot of Portuguese (Brazil) and Korean titles selected on various platform DATs, for example, Sega Master System and Sega Genesis. Nothing in the original DAT files indicates these titles have any English support. I'm fluent in Portuguese, but I didn't expect Retool to know that. :)

Example: Game Box Serie Esportes Radicais (Brazil) in Sega Master System

**To reproduce**
DATs from No-Intro's Dat-o-Matic site.
Retool set with English as the only language filter
Region filter order: USA, Europe, Canada, UK, Australia, New Zealand, Japan, World.... (all countries as in the filter as was set up by default, only the order of the top-most has been tweaked)

**Expected behavior**
Only titles that have English language support to be included, either specified in the DAT or in other metadata the tool might have built-in

**Operating system**
Windows 10

**Retool edition**
retool-gui

**Retool version**

0.89

**Comment by unexpectedpanda** [comment]
In addition to the dat, there's also data from No-Intro's DBs that is parsed. In the example title given, it's marked as English:

https://datomatic.no-intro.org/index.php?page=show_record&s=26&n=0143

Not saying it is, just that's where the data comes from.

**Comment by jim16127** [comment]
I just personally checked the rom. The game IS IN ENGLISH. All text aside from the text in the title "Serie Esportes Radicais" is in english. 
![Capture](https://user-images.githubusercontent.com/21118480/117558496-f8e93180-b04b-11eb-9399-8173c7d36f2f.PNG)

**Comment by HVR88** [comment]
Thanks for the confirmation of the additional data-source and also confirmation of the specific title.

It looks like at the end of the day, No-Intro dats are not much more useful than Redump's for game information.

**Comment by unexpectedpanda** [comment]
Possibly at the root of it is the not so useful No-Intro rule that if there's only one language for a title, it's not included in the file name. Redump seems a little better at this when something is in a language you might not expect, but there are still surprises.

Additionally the current dat format, and hence the associated managers, aren't really set up to cope with the kind of scenarios we're playing around with. I did have a proposal for a new dat format kicking around somewhere, but it'd have to be super appealing and easy to convert to prompt a change in format.

**Comment by HVR88** [comment]
I find DATs useless for the most part and have only made use of them in the past strictly for parent/clone info - but today that's hit and miss and completely non-existent for anything disc-based. I don't make it a secret that I think the people involved in No-Intro, Redump and TOSEC are for the most part, tools, either. ;)  Piracy in the guise of preservation, about as useful a smoke-screen as a sheet of glass.

You do well by compiling other sources of information and building them into Retool. For sorting and 1G1R, all this other info will be infinitely more useful than the CRC pulled from DATs. Keeping a minimal and useful set of files will always be my goal, not discovering if I have an extra byte or two at the end of file.
