### ISSUE TITLE
Feature request: option to prefer early revisions/versions 

### ISSUE THREAD

**Issue by tomlbh** [unexpectedpanda/retool#91]
Is it possible to include an option to prioritize early revisions and/or early versions?

**Comment by unexpectedpanda** [comment]
Firstly, cheers for picking up the Linux bug, fixed now :) I really need to automate my test suite.

I have no plans to build an earlier revision feature at this point in time. In case that changes, can you give me some extra context as to why you'd like to prioritize earlier versions?

**Comment by tomlbh** [comment]
Thank you for replying,  I'm in no way a programmer so I was just following my nose. I see you've made a much more elegant solution!

For context, I've noticed that later releases are likely to have had content removed/censored or advertising added, rather than actual bug fixes applied.
Examples off the top of my head are Ocarina of Time (N64) where some textures and sounds were removed and Tomb Raider & DOOM on the PSX that had demos added and menus altered.

It's just a personal taste thing, I sure there's plenty of cases where first releases were 'not right' and later ones fixed.

**Comment by unexpectedpanda** [comment]
Thanks :)

You're right that some latest versions don't improve things. Selecting the latest title was a design choice on my behalf to keep things scalable. Individual "best" versions would require a lot of manual work and is highly subjective, and with the latest titles you get the potential benefit of bug fixes as you've noted.

It's not against the 1G1R philosophy in my mind to give an option to switch the selection to "earliest". It's still keeping only one version of a title, not every version with a slight visual difference (which some people have asked for!).

The main issue is the code base is written to expect the latest version every step of the way &mdash; it's a large job to alter that, and compensate for all the edge cases.

If it happens (and to be clear, it's a big if), "earliest" would probably only apply to production titles, with related preproduction titles being superceded by the earliest production title.

**Comment by tomlbh** [comment]
Seconded, I don't disagree with anything you've said there, and yep 'earliest' would be how the game first landed on retail shelves.

Have you seen the 1G1R tool that andrebrait has made? https://github.com/andrebrait/1g1r-romset-generator
The feature is implemented there, but doesn't work with redump DATs (the tool needs P/C dats). 

Between that tool and yours I'm sure I can get close to what I'm after. I've had moderate success by excluding the string " (Rev " in custom global filters, but that does remove entries that have only a (Rev. 1) available. Maybe I shouldn't be so lazy and just tidy up the edge cases manually :)

Anyway, great tool, I'm glad I found it, thanks for your hard work!

**Comment by unexpectedpanda** [comment]
I have seen Andre's 1G1R generator :) I haven't played too much with it as it seems the end goal is file management instead of dat output. I have peeked at the code, though, and he's definitely more accomplished than I am! It inspired me to try to write better code.

I suppose you could export a legacy dat from Retool to retain the parent/clone info, then import it into 1G1R Romset Generator to do the version flip. I'd imagine that opens the possibility of being exposed to its 1G1R algorithm though, so in addition to version flip you might get different 1G1R selections than Retool would provide.

**Comment by unexpectedpanda** [comment]
While rewriting Retool I've spent a bit of time seeing if I can enable this. While the automated portion looks possible, clone list priorities make things complicated. Special editions will always outrank originals, and any versioning that has to be manually curated through a clone list will also override any "first versions" setting.

While it's technically possible to work around with additional clone list data, it's also a lot of ongoing curation. I also have to choose my time wisely on what to focus on :)

I'm sadly going to have to shelve this for now. Maybe some time in the future.
