### ISSUE TITLE
Custom Filters get calculated too early, Having other Clones appear

### ISSUE THREAD

**Issue by katarak** [unexpectedpanda/retool#92]
**Describe the bug**
It seems to me that the Custom Filters (exclude, in my case) are calculated too early. Maybe as a pre pass to the rest of the usual filtering. This creates an issue where if I exclude a game from a region, I will get the same game from the next region in the list.

I look through the Retool generated dat to remove games I don't want for a platform. I expect that's how other people would do it too, So the data that we want to remove is based on a dat file without custom filters.
If the custom filters were to be done as a post pass, then the only data which would exist is the dat with our correct settings and then our exclusions/inclusions removed/added.

**To reproduce**

1. Using the latest 3DO dat generate a 1G1R dat.
2. You should see Flashback - The Quest for Identity (USA) (En,Fr) in the retooled dat
3. Add "Flashback - The Quest for Identity (USA) (En,Fr)" as a system exclude and retool the dat
4. Notice that "Flashback (Europe) (En,Fr)" is now in the retooled dat.

This situation can be rectified by putting "Flashback" as a partial exclude, but other games have that same problem for example excluding Out of This World (USA), adds Outer World (Japan).

Please note that I use partial excludes in all cases, I just try and make them as long as possible so they only hit 1 game (and all the discs, for example)

**Expected behavior**
If the exclusions/additions would be done on the retooled dat, then the same game from other regions would not be added to the dat. This was my expected behaviour. If I exclude Out of This World, I shouldn't get Another World, nor Outer World.

**Operating system**
- [x] Windows 10 (older versions not supported)
- [ ] Ubuntu
- [ ] Other (please specify)

**Retool edition**
- [x] retool-gui.exe
- [ ] retool.py
- [ ] retool-gui.py

**Retool version**
For the command line edition of Retool, the version is shown when you run it with no other arguments.
For the GUI edition, click **Help**, then **About**.
Retool GUI 0.10, Retool CLI 0.93

**Are you using custom global or system filters? If so, list them below**
Please see above

Global excludes:

Global includes:

System excludes:

System includes:

**What other settings are you using?**
I also exclude

- Bad Dumps
- Cover Discs
- Demos, Kiosks, Samples
- Promotional

**Additional context**

**Comment by katarak** [comment]
Another example is Myst.

Adding "Myst (USA)" to the exclude list will include "Myst (Japan)" and there's also Myst (Germany) as a 3rd option.
Removing the region so all Myst games were removed also removed 
Nishimura Kyoutarou Travel Mystery - Akugyaku no Kisetsu - Tokyo Nanki Shirahama Renzoku Satsujin Jiken (Japan)
because of "Mystery"

so my solution is to exclude
Myst (USA)
Myst (Japan)
Myst (Germany)

**Comment by unexpectedpanda** [comment]
This makes sense, although to me more as extra functionality than replacing the existing exclude filters. The existing excludes are where they are to deal with the legacy dat output, plus the earlier things are removed in the chain, the less processing overall has to be done.

Maybe something like `$Myst (USA)` that looks up the full title after the clone list match is done, then removes the whole group.

I'm working on a refactor at the moment, so I'll add this to the list for when I get to this particular set of functions.

**Comment by unexpectedpanda** [comment]
(You could cheat with Myst, btw, with `/^Myst \(.*`, but that's not going to take out anything defined by the clone list)

**Comment by katarak** [comment]
This issue pops up annoyingly on the CD-I dat.
A lot of titles have fully translated names so clearing them all out becomes a real pain.

This is all the same title, and as soon as I removed one, I had to go through the process and compare for all the other ones.

Dutch Masters of the Seventeenth Century
Hollandse Meesters uit de Zeventiende Eeuw (Netherlands)
Niederlaendischen Meister des 17. Jahrhunderts, Die (Germany)
Maestri Olandesi del Seicento, I (Italy)

**Comment by unexpectedpanda** [comment]
Ah, I definitely wasn't clear before, sorry. The current exclude/include functionality is working as intended. Its purpose isn't to observe connections between titles and remove groups at a time, but to remove/recover titles based on basic string/regex matches, nothing more.

The new functionality you've requested is slated for Retool 2.0, as the existing code base has become difficult to expand. At the moment the core has been rebuilt and it's currently being tested against the old output. I'm starting to add new features, but there's no GUI yet.

It's not a quick process. I expect it will still be some months yet.

**Comment by unexpectedpanda** [comment]
...or about a year.

This functionality is now available in v2. Wrap your user filters in `<>` and the related titles should also be removed.
