### ISSUE TITLE
SNES clones (20210625-015120)

### ISSUE THREAD

**Issue by yoasif** [unexpectedpanda/retool#96]
## Dat
The dat name where the issue is.

Nintendo - Super Nintendo Entertainment System (Parent-Clone) (20210625-015120).dat

## Issue
Where possible, include URLs to a reputable source as proof, as it helps speed up verification.

I think all of the below except the last one is pretty obvious:

Breath of Fire II - Shimei no Ko (Japan) (Rev 1)
Breath of Fire II (USA)

Breath of Fire - Ryuu no Senshi (Japan) (Rev 1)                   
Breath of Fire (USA)

Bugs Bunny - Hachamecha Daibouken (Japan)
Bugs Bunny - Rabbit Rampage (USA)

Choplifter III - Rescue-Survive (USA)
Choplifter III (Europe)

Maui Mallard in Cold Shadow (USA)
Donald in Maui Mallard (Europe)
Donald Duck no Maui Mallard (Japan)

Final Fantasy - Mystic Quest (USA) (Rev 1)
Final Fantasy USA - Mystic Quest (Japan)

Final Fight Tough (Japan)
Final Fight 3 (USA)

Hagane (Japan)
Hagane - The Final Conflict (USA)

Hoshi no Kirby 3 (Japan)
Kirby's Dream Land 3 (USA)

Hoshi no Kirby Super Deluxe (Japan) (Rev 2)
Kirby Super Star (USA)

Joe & Mac - Caveman Ninja (Europe) (En,Fr,De,Es,It,Nl)
Joe & Mac - Tatakae Genshijin (Japan)
Joe & Mac (USA)

Joe & Mac 2 - Lost in the Tropics (USA)
Joe & Mac 3 - Lost in the Tropics (Europe) (En,Fr,De)

King of Dragons, The (Japan)
King of Dragons (USA)

King of the Monsters 2 - Next Thing (Japan)
King of the Monsters 2 (USA)

Lamborghini - American Challenge (Europe)
Lamborghini American Challenge (USA)

Lost Vikings 2 (USA)
Lost Vikings II, The - Norse by Norsewest (Europe) (En,Fr,De)

Lufia (Europe)
Lufia II - Rise of the Sinistrals (USA)

Mask (Japan)
Mask, The (USA)

Parodius Da! - Shinwa kara Owarai e (Japan)
Parodius (Europe)

Phalanx - The Enforce Fighter A-144 (Japan) (En)
Phalanx (USA)

Plok! (Japan)
Plok (USA)

Rival Turf (Europe)
Rival Turf! (USA)
Rushing Beat (Japan)

R-Type III - The Third Lightning (Japan) (En)
R-Type III (USA)

SimAnt (Japan)
SimAnt - The Electronic Ant Colony (USA)

Space Invaders - The Original Game (Japan)
Space Invaders (USA)

Donkey Kong Country 2 - Diddy's Kong Quest (USA) (En,Fr) (Rev 1)
Super Donkey Kong 2 - Dixie & Diddy (Japan) (Rev 1)

Bust-A-Move (USA)
Puzzle Bobble - Bust-A-Move (Europe) (Rev 1)
Puzzle Bobble (Japan)
Not sure which revision is the latest here.

**Comment by unexpectedpanda** [comment]
Looks like No-Intro has been busy renaming systems too. I'll get to this eventually, in the meantime, please use the standard dat instead of the parent/clone.

**Comment by unexpectedpanda** [comment]
Update your clone lists, and the issue will go away :)

This is related to No-Intro removing the `(Combined)` tag from the system. Somehow I messed up uploading the hashes for the updating system to work properly, but all should be good now.
