### ISSUE TITLE
Retool v0.95 crashes on No-Intro "Commodore - Plus-4" DAT

### ISSUE THREAD

**Issue by Freeben666** [unexpectedpanda/retool#99]
**Describe the bug**
Retool crashes when processing DAT "Commodore - Plus-4  (20090105-000000).dat" from No-Intro

**To reproduce**
Clean install retool v0.95 and process the DAT

**Expected behavior**
Having a filtered DAT in output

**Operating system**
- [x] Windows 10 (older versions not supported)
- [ ] Ubuntu
- [ ] Other (please specify)

**Retool edition**
- [x] retool-gui.exe
- [ ] retool.py
- [ ] retool-gui.py

**Retool version**
- Retool GUI : 0.11
- Retool CLI : 0.95

**Are you using custom global or system filters? If so, list them below**

Global excludes: None

Global includes: None

System excludes: None

System includes: None

**What other settings are you using?**
- Regions: France > Europe > World > Unknown
- Languages : English + French

**Additional context**

```
* Reading dat file: "D:\Emulation\Tools\Retool\DATs\Commodore - Plus-4
  (20090105-000000).dat"
* Validating dat file... file is a Logiqx dat file.
* Converting dat file to a searchable format... done.
* Checking if the input dat is numbered... this isn't a numbered dat.
* Gathering stats... done.

|  DAT DETAILS
|  Description: Commodore - Plus-4
|  Author: None
|  URL: http://www.no-intro.org
|  Version: 20090105-000000

* Finding titles in regions... done.
* Finding parents across regions... done.
* Checking already excluded titles for includes... done.
Traceback (most recent call last):
  File "retool-gui.py", line 1020, in <module>
  File "retool-gui.py", line 622, in main
  File "retool.py", line 374, in main
  File "modules\output.py", line 196, in write_dat_file
  File "modules\xml.py", line 696, in header
AttributeError: 'NoneType' object has no attribute 'replace'
[12012] Failed to execute script retool-gui
```

**Comment by unexpectedpanda** [comment]
Thanks! Fixed in 0.96.
